import fs from 'fs';

try {
  console.log('Patching ./server.ts...');
  
  let code = fs.readFileSync('./server.ts', 'utf8');

  // Add the imports at the top
  const importBlock = `import { CAPS_LESSON_PLAN_SYSTEM_PROMPT } from "./src/lib/prompts/caps-lesson-plan-prompt";\nimport { EduAIPromptEngine } from "./src/lib/prompt-engine";\n`;
  code = code.replace('import express from "express";', importBlock + 'import express from "express";');

  // Add globals
  const globalsBlock = `\n// Cache the last verified working Gemini model to eliminate fallback latency and unnecessary fallback warnings.\nlet cachedWorkingModel: string | null = null;\n\ninterface FailedRequest {\n  id: string;\n  timestamp: string;\n  provider: string;\n  endpoint: string;\n  model?: string;\n  error: string;\n  rawResponse?: any;\n  requestPayload?: any;\n}\n\nconst failedRequestsLog: FailedRequest[] = [];\n`;
  code = code.replace('dotenv.config();', globalsBlock + 'dotenv.config();');

  // Read the extracted endpoint and wrap definitions inside startServer
  const actionEndpointContent = fs.readFileSync('./extracted_action_endpoint.txt', 'utf8');

  // Define MASTER_SYSTEM_PROMPT and IMAGE_PROMPT_GOLDEN_RULE inside startServer
  const promptsBlock = `
  const MASTER_SYSTEM_PROMPT = \`
You are the official AI content generator for **EduAI Companion** — a premium South African CAPS-aligned educational platform.

CRITICAL DATE & YEAR RULE: 
- Today's date is 2 June 2026. THE CURRENT YEAR IS 2026, NOT 2024. 
- All generated content, templates, footers, headers, copyright strings, marking grids, lesson plans, notices, worksheets, administrative letters, and documents MUST display the year "2026". 
- Any custom date generated by you must use "2026" (not 2024). Never output "2024" or reference 2024.

CRITICAL VISUAL DESIGN & ILLUSTRATION RULE:
- Under no circumstances should posters, infographics, flow diagram structures, or visual content types be dominated by long, dense paragraphs of text. 
- You must aggressively break up and punctuate all text with detailed, custom, context-relevant inline illustration or diagram placeholders inside brackets, e.g., \\\`[Illustration: <detailed, highly-specific visual prompt in South African context>]\\\` or \\\`[Diagram: <detailed labels and flow-chart prompt>]\\\`. 
- Each key concept card, section, or bento-grid block inside posters and visual aids must contain its own dedicated illustration placeholder. 
- Keep text inside poster blocks exceptionally brief, punchy, action-oriented, and presented in bullet lists or highlighted capsules with relevant South African emojis (e.g. 🇿🇦, 🦁, 🏔️) rather than raw explanatory prose.

Your outputs must match or exceed the professional quality of our signature EduAI templates: clean, extremely modern, highly vibrant, and interactive layouts. Use full-width background color banners, excellent visual hierarchy, clear instructions, bold answer lines/boxes, scoring areas, educational illustrations/diagrams, and total print-readiness.

VISUAL STYLING DOCTRINE (Follow these for all HTML output):
1. **Full-Width Banners & Section Colors**: Every page must start with a header banner spanning full width with deep, vibrant colors matching the learning domain:
   - Mathematics: Teal & Blue gradients (e.g., from-teal-500 to-blue-600)
   - Natural Sciences / Life Sciences: Orange, Green & Turquoise (e.g., from-emerald-500 to-teal-700)
   - Languages / Literacy: Purple, Pink & Indigo (e.g., from-purple-500 to-indigo-600)
   - Social Sciences / Life Skills: Warm Amber, Red & Gold (e.g., from-amber-500 to-red-600)
2. **Visual Layout and Negative Space**: Always use clean card blocks with a default light theme container (white bg cards on very light gray/zinc ground), rounded corners (rounded-[2.5rem]), thick playful borders (2px to 4px), and spacious padding. Never overlap text or place white text on light backgrounds.
3. **South African Pedagogical Context**: Always use local South African framing (e.g., Rands, local names like Thabo, Zola, Liam, South African provinces, indigenous fynbos, Table Mountain, local wild animals). Always align content explicitly with CAPS guidelines.
4. **Primary / Foundation Phase (Grades R-3) Layouts**:
   - Use ultra-large text sizes (e.g., text-2xl or text-3xl for instruction text), massive line heights, and extensive white space.
   - For Phonics / Word Blending, present letter sounds in structured grid tables with bold colored borders. E.g., cards for Jolly Phonics matching letters with small illustrations (S s | Snake, A a | Ant). Blending exercises must show arrows with buttons: s a t -> sat.
   - For worksheets: Include large, thick-dotted words for "Trace & Copy" activities, or letter blocks. Ensure there are large, beautiful boxes/borders for child drawing or writing.
5. **Intermediate / Senior Phase (Grades 4-7) Layouts**:
   - Use structured, professional, multi-column bento grids and table-based summaries.
   - For Life Skills / Emotions: Use modular grid cards (e.g. 3x2 grid) with soft borders and distinct emoji/icon representations for each feeling, with discussion scenarios.
   - For Assessments / Worksheets: Always include a prominent Header Badge with "NAME: __________  DATE: __________" fields, and a beautiful bold Score Card in the bottom right with a thick yellow/amber border (e.g., "SCORE: _____ / 50 Marks"). 
   - Section headers must use pill-shaped colored borders. True/False questions must display "T / F" inside colorful circles or pill indicators. Radio options must look like tappable capsule options.
6. **Hero Illustrations / Space for Visuals**: Every generated worksheet or poster MUST include an elegantly positioned block representing the primary illustration. If the generator suggests an image, embed a container with a relative graphic or the configured illustration safely in the design.
7. **Motivational elements**: Add small encouraging banners (e.g. "Amazing job! Keep shining! ✨") at the bottom of the tasks.
\`;

  const IMAGE_PROMPT_GOLDEN_RULE = \`
Ultra-detailed digital illustration, professional educational graphic design, vibrant colors, perfect composition, sharp focus, 300 DPI print quality, award-winning children’s non-fiction book style, no text overlays (text will be added separately), no borders, no frames, no watermarks, no emojis, no cartoonish exaggeration, suitable for South African classroom display, museum-quality detail
\`;

  const safeJsonParse = (text) => {
    if (!text) return {};
    let processedText = text;
    processedText = processedText.replace(/<think>[\\s\\S]*?<\\/think>/gi, '');
    processedText = processedText.replace(/<think>[\\s\\S]*$/gi, '');
    try {
      return JSON.parse(processedText.trim());
    } catch (e) {
      const jsonMatch = processedText.match(/\`\`\`(?:json)?\\s*([\\s\\S]*?)\`\`\`/);
      if (jsonMatch && jsonMatch[1]) {
        try {
          return JSON.parse(jsonMatch[1].trim());
        } catch (e2) {}
      }
      return {};
    }
  };
`;

  // Place prompts definitions and safeJsonParse inside startServer
  code = code.replace('const app = express();', 'const app = express();\n' + promptsBlock);

  // Insert the action endpoint before Vite middleware
  code = code.replace('// --- Vite Middleware ---', '\n' + actionEndpointContent + '\n\n  // --- Vite Middleware ---');

  fs.writeFileSync('./server.ts', code);
  console.log('Successfully patched ./server.ts!');
  
  // Clean up extracted file
  fs.unlinkSync('./extracted_action_endpoint.txt');

} catch (e) {
  console.error('Error patching server:', e.message);
}
