import { CAPS_LESSON_PLAN_SYSTEM_PROMPT } from "./src/lib/prompts/caps-lesson-plan-prompt";
import { EduAIPromptEngine } from "./src/lib/prompt-engine";
import express from "express";
import path from "path";
import dotenv from "dotenv";
import OpenAI from "openai";
import Anthropic from "@anthropic-ai/sdk";
import axios from "axios";
import { GoogleGenAI, Type } from "@google/genai";
import mammoth from "mammoth";

async function tryExtractDocxText(base64Data: string): Promise<string> {
  try {
    const buffer = Buffer.from(base64Data, "base64");
    const result = await mammoth.extractRawText({ buffer });
    return result.value || "";
  } catch (err: any) {
    console.error("Failed to parse docx with mammoth:", err);
    return "";
  }
}


// Cache the last verified working Gemini model to eliminate fallback latency and unnecessary fallback warnings.
let cachedWorkingModel: string | null = null;

interface FailedRequest {
  id: string;
  timestamp: string;
  provider: string;
  endpoint: string;
  model?: string;
  error: string;
  rawResponse?: any;
  requestPayload?: any;
}

const failedRequestsLog: FailedRequest[] = [];
dotenv.config();

function resolveOpenRouterKey(): string {
  const keys = [
    process.env.OPENROUTER_API_KEY,
    process.env.VITE_OPENROUTER_API_KEY,
    process.env.OPEN_ROUTER_API_KEY,
    process.env.OPENROUTER_TOKEN,
    process.env.MULEROUTER_API_KEY,
  ];
  for (const key of keys) {
    if (key && key !== "dummy" && key !== "undefined" && key.trim() !== "") {
      return key.trim().replace(/^['"\s]+|['"\s]+$/g, "");
    }
  }
  return "";
}

function resolveGeminiKey(): string {
  const keys = [
    process.env.GEMINI_API_KEY,
    process.env.VITE_GEMINI_API_KEY,
    process.env.GOOGLE_GENAI_API_KEY,
    process.env.GOOGLE_AI_API_KEY,
  ];
  for (const key of keys) {
    if (key && key !== "dummy" && key !== "undefined" && key.trim() !== "") {
      return key.trim().replace(/^['"\s]+|['"\s]+$/g, "");
    }
  }
  return "";
}

let cachedGeminiClient: GoogleGenAI | null = null;
let cachedApiKeyUsed: string | null = null;

function getGeminiClient(): GoogleGenAI {
  const currentKey = resolveGeminiKey();
  if (cachedGeminiClient && cachedApiKeyUsed === currentKey) {
    return cachedGeminiClient;
  }
  cachedApiKeyUsed = currentKey;
  cachedGeminiClient = new GoogleGenAI({
    apiKey: currentKey || "dummy",
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });
  return cachedGeminiClient;
}

const geminiAi = new Proxy({} as GoogleGenAI, {
  get(target, prop) {
    const client = getGeminiClient();
    const value = Reflect.get(client, prop);
    if (typeof value === 'function') {
      return value.bind(client);
    }
    return value;
  }
});


import { HfInference } from "@huggingface/inference";

const app = express();

const MASTER_SYSTEM_PROMPT = `
You are the official AI content generator for **EduAI Companion** — a premium South African CAPS-aligned educational platform.

CRITICAL DATE & YEAR RULE: 
- Today's date is 2 June 2026. THE CURRENT YEAR IS 2026, NOT 2024. 
- All generated content, templates, footers, headers, copyright strings, marking grids, lesson plans, notices, worksheets, administrative letters, and documents MUST display the year "2026". 
- Any custom date generated by you must use "2026" (not 2024). Never output "2024" or reference 2024.

CRITICAL VISUAL DESIGN & ILLUSTRATION RULE:
- Under no circumstances should posters, infographics, flow diagram structures, or visual content types be dominated by long, dense paragraphs of text. 
- You must aggressively break up and punctuate all text with detailed, custom, context-relevant inline illustration or diagram placeholders inside brackets, e.g., \`[Illustration: <detailed, highly-specific visual prompt in South African context>]\` or \`[Diagram: <detailed labels and flow-chart prompt>]\`. 
- Each key concept card, section, or bento-grid block inside posters and visual aids must contain its own dedicated illustration placeholder. 
- Keep text inside poster blocks exceptionally brief, punchy, action-oriented, and presented in bullet lists or highlighted capsules with relevant South African emojis (e.g. 🇿🇦, 🦁, 🏔️) rather than raw explanatory prose.

Your outputs must match or exceed the professional quality of our signature EduAI templates: clean, extremely modern, highly vibrant, and interactive layouts. Use full-width background color banners, excellent visual hierarchy, clear instructions, bold answer lines/boxes, scoring areas, educational illustrations/diagrams, and total print-readiness.

VISUAL STYLING DOCTRINE (Follow these for all HTML output):
1. **Full-Width Banners & Section Colors**: Every page must start with a header banner spanning full width with deep, vibrant colors matching the learning domain:
   - Mathematics: Teal & Blue gradients (e.g., from-teal-500 to-blue-600)
   - Natural Sciences / Life Sciences: Orange, Green & Turquoise (e.g., from-emerald-500 to-teal-700)
   - Languages / Literacy: Purple, Pink & Indigo (e.g., from-purple-500 to-indigo-600)
   - Social Sciences / Life Skills: Warm Amber, Red & Gold (e.g., from-amber-500 to-red-600)
2. **Visual Layout and Negative Space**: Always use clean card blocks with a default light theme container (white bg cards on very light gray/zinc ground), rounded corners (rounded-[2.5rem]), thick playful borders (2px to 4px), and spacious padding. Never overlap text or place white text on light backgrounds.
3. **South African Pedagogical Context**: Always use local South African framing (e.g., Rands, local names like Thabo, Zola, Liam, South African provinces, indigenous fynbos, Table Mountain, local wild animals). Always align content explicitly with CAPS guidelines.
4. **Primary / Foundation Phase (Grades R-3) Layouts**:
   - Use ultra-large text sizes (e.g., text-2xl or text-3xl for instruction text), massive line heights, and extensive white space.
   - For Phonics / Word Blending, present letter sounds in structured grid tables with bold colored borders. E.g., cards for Jolly Phonics matching letters with small illustrations (S s | Snake, A a | Ant). Blending exercises must show arrows with buttons: s a t -> sat.
   - For worksheets: Include large, thick-dotted words for "Trace & Copy" activities, or letter blocks. Ensure there are large, beautiful boxes/borders for child drawing or writing.
5. **Intermediate / Senior Phase (Grades 4-7) Layouts**:
   - Use structured, professional, multi-column bento grids and table-based summaries.
   - For Life Skills / Emotions: Use modular grid cards (e.g. 3x2 grid) with soft borders and distinct emoji/icon representations for each feeling, with discussion scenarios.
   - For Assessments / Worksheets: Always include a prominent Header Badge with "NAME: __________  DATE: __________" fields, and a beautiful bold Score Card in the bottom right with a thick yellow/amber border (e.g., "SCORE: _____ / 50 Marks"). 
   - Section headers must use pill-shaped colored borders. True/False questions must display "T / F" inside colorful circles or pill indicators. Radio options must look like tappable capsule options.
6. **Hero Illustrations / Space for Visuals**: Every generated worksheet or poster MUST include an elegantly positioned block representing the primary illustration. If the generator suggests an image, embed a container with a relative graphic or the configured illustration safely in the design.
7. **Motivational elements**: Add small encouraging banners (e.g. "Amazing job! Keep shining! ✨") at the bottom of the tasks.
`;

  const IMAGE_PROMPT_GOLDEN_RULE = `
World-class masterpiece work of art, crisp render, sharp focus, charmingly aesthetic design, 4k, soft lighting, masterpiece emoji-style figurine 3D render, 3D Disney Character render, pure white background, natural beauty, ultra-detailed 3D digital asset, vibrant colors, perfect composition, no text overlays (text will be added separately), no borders, no frames, no watermarks, museum-quality detail
`;

  const repairTruncatedJson = (jsonStr: string): string => {
     let inString = false;
     let escape = false;
     const stack: string[] = [];
     
     for (let i = 0; i < jsonStr.length; i++) {
       const char = jsonStr[i];
       if (escape) {
         escape = false;
         continue;
       }
       if (char === '\\') {
         escape = true;
         continue;
       }
       if (char === '"') {
         inString = !inString;
         continue;
       }
       if (!inString) {
         if (char === '{' || char === '[') {
           stack.push(char);
         } else if (char === '}') {
           if (stack.length > 0 && stack[stack.length - 1] === '{') {
             stack.pop();
           }
         } else if (char === ']') {
           if (stack.length > 0 && stack[stack.length - 1] === '[') {
             stack.pop();
           }
         }
       }
     }

     let repaired = jsonStr;
     if (inString) {
       repaired += '"';
     }
     
     while (stack.length > 0) {
       const last = stack.pop();
       if (last === '{') {
         repaired += '}';
       } else if (last === '[') {
         repaired += ']';
       }
     }
     
     repaired = repaired.replace(/,\s*([}\]])/g, '$1');
     return repaired;
   };

   const safeJsonParse = (text) => {
    if (!text) return {};
    let processedText = text.trim();
    
    // 1. Strip reasoning thoughts if present (<think>...</think> or unclosed <think>)
    processedText = processedText.replace(/<think>[\s\S]*?<\/think>/gi, '');
    processedText = processedText.replace(/<think>[\s\S]*$/gi, '');
    processedText = processedText.trim();

    if (!processedText) return {};

    // 2. Extract content from markdown JSON block or generic markdown block anywhere in the text
    if (processedText.includes("```json")) {
      const match = processedText.match(/```json\s*([\s\S]*?)\s*```/i);
      if (match) {
        processedText = match[1].trim();
      }
    } else if (processedText.includes("```")) {
      const match = processedText.match(/```\s*([\s\S]*?)\s*```/);
      if (match) {
        processedText = match[1].trim();
      }
    }

    // 3. Extract the clean JSON object if there is leading/trailing conversational text
    let extractedJson = processedText;
    if (processedText.includes("{") && processedText.includes("}")) {
      const firstCurly = processedText.indexOf("{");
      const lastCurly = processedText.lastIndexOf("}");
      extractedJson = processedText.substring(firstCurly, lastCurly + 1).trim();
    }

    try {
      // First try normal JSON parse on extracted JSON
      return JSON.parse(extractedJson);
    } catch (err) {
      try {
        // Try parsing the original text directly if extraction was somehow off
        return JSON.parse(processedText);
      } catch (errOrig) {
        try {
          const repaired = repairTruncatedJson(extractedJson);
          return JSON.parse(repaired);
        } catch (errRep) {
        console.warn("safeJsonParse: Standard and repaired JSON parse failed, trying regex fallback...", errRep);

        // Direct Javascript execution/extraction recovery if brackets are matched at all
        if (extractedJson.includes('{') && extractedJson.includes('}')) {
          try {
            const repaired = repairTruncatedJson(extractedJson);
            const evaluated = new Function('return ' + repaired)();
            if (typeof evaluated === 'object' && evaluated !== null) return evaluated;
          } catch(e4) {}
          try {
            const evaluated = new Function('return ' + extractedJson)();
            if (typeof evaluated === 'object' && evaluated !== null) return evaluated;
          } catch(e5) {}
        }
      }
    }

      const closeOpenHtmlTags = (html: string): string => {
        const tagRegex = /<\/?([a-z1-6]+)(?:\s+[^>]*?)?>/gi;
        let match;
        const openTags: string[] = [];
        
        while ((match = tagRegex.exec(html)) !== null) {
          const fullTag = match[0];
          const tagName = match[1].toLowerCase();
          
          if (fullTag.endsWith('/>') || ['img', 'br', 'hr', 'input', 'meta', 'link'].includes(tagName)) {
            continue;
          }
          
          if (fullTag.startsWith('</')) {
            if (openTags.length > 0 && openTags[openTags.length - 1] === tagName) {
              openTags.pop();
            }
          } else {
            openTags.push(tagName);
          }
        }
        
        let closedHtml = html;
        while (openTags.length > 0) {
          const tag = openTags.pop();
          closedHtml += `</${tag}>`;
        }
        return closedHtml;
      };

      // Helper regex extractors
      const extractField = (source: string, field: string): string | null => {
        const escapedField = field.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
        const regex = new RegExp(`"${escapedField}"\\s*:\\s*"([\\s\\S]*?)"(?=\\s*,|\\s*})`, 'i');
        const match = source.match(regex);
        if (match) {
          let val = match[1].replace(/\\"/g, '"').replace(/\\n/g, '\n');
          if (val.trim().startsWith('<')) {
            val = closeOpenHtmlTags(val);
          }
          return val;
        }

        // Truncated fallback match
        const truncatedRegex = new RegExp(`"${escapedField}"\\s*:\\s*"([\\s\\S]*)$`, 'i');
        const truncMatch = source.match(truncatedRegex);
        if (truncMatch) {
          let val = truncMatch[1].trim();
          if (val.endsWith('\\')) {
            val = val.slice(0, -1);
          }
          if (val.endsWith('"') && !val.endsWith('\\"')) {
            val = val.slice(0, -1);
          }
          val = val.replace(/\\"/g, '"').replace(/\\n/g, '\n');
          if (val.trim().startsWith('<')) {
            val = closeOpenHtmlTags(val);
          }
          return val;
        }
        return null;
      };

      const extractArrayField = (source: string, field: string): string[] => {
        const escapedField = field.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
        const regex = new RegExp(`"${escapedField}"\\s*:\\s*\\[([\\s\\S]*?)\\]`, 'i');
        const match = source.match(regex);
        if (match && match[1]) {
          return match[1]
            .split(',')
            .map(item => item.trim().replace(/^["']|["']$/g, '').trim())
            .filter(item => item.length > 0);
        }
        return [];
      };

      const textToSearch = processedText;

      // ─── POWERFALLBACK: HEAL TRUNCATED JSON PROPERTIES ───
      const fallbackObj: any = {};
      const stringFields = [
        "content", "memo", "rubric", "assessmentCriteria", "imagePrompt",
        "description", "printInstructions", "notes", "documentType",
        "extractedText", "feedback", "totalScore"
      ];
      
      for (const field of stringFields) {
        const extracted = extractField(textToSearch, field);
        if (extracted !== null) {
          fallbackObj[field] = extracted;
        }
      }
      
      const arrayFields = ["successIndicators", "marksPerQuestion"];
      for (const field of arrayFields) {
        const extracted = extractArrayField(textToSearch, field);
        if (extracted.length > 0) {
          fallbackObj[field] = extracted;
        }
      }

      if (fallbackObj.content || fallbackObj.extractedText || fallbackObj.feedback || fallbackObj.description) {
        console.warn("safeJsonParse: Reconstructed truncated JSON response successfully via fallback regex extraction!");
        return fallbackObj;
      }

      console.warn("Failed to parse AI response as JSON:", processedText);
      return {};
    }
  };

  const PORT = 3000;

  app.use(express.json({ limit: '50mb' }));
  app.use(express.urlencoded({ limit: '50mb', extended: true }));

  // --- AI Provider Clients ---

  let cachedGroqClient: OpenAI | null = null;
  let cachedGroqKey: string | null = null;

  function getGroqClient(): OpenAI {
    const currentKey = (process.env.GROQ_API_KEY || "").trim().replace(/^['"\s]+|['"\s]+$/g, "");
    if (cachedGroqClient && cachedGroqKey === currentKey) {
      return cachedGroqClient;
    }
    cachedGroqKey = currentKey;
    cachedGroqClient = new OpenAI({
      apiKey: currentKey || "dummy",
      baseURL: "https://api.groq.com/openai/v1",
    });
    return cachedGroqClient;
  }

  const groq = new Proxy({} as OpenAI, {
    get(target, prop) {
      const client = getGroqClient();
      const value = Reflect.get(client, prop);
      if (typeof value === 'function') {
        return value.bind(client);
      }
      return value;
    }
  });

  let cachedAlibabaClient: OpenAI | null = null;
  let cachedAlibabaKey: string | null = null;

  function getAlibabaClient(): OpenAI {
    const currentKey = (process.env.ALIBABA_API_KEY || "").trim().replace(/^['"\s]+|['"\s]+$/g, "");
    if (cachedAlibabaClient && cachedAlibabaKey === currentKey) {
      return cachedAlibabaClient;
    }
    cachedAlibabaKey = currentKey;
    cachedAlibabaClient = new OpenAI({
      apiKey: currentKey || "dummy",
      baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    });
    return cachedAlibabaClient;
  }

  const alibaba = new Proxy({} as OpenAI, {
    get(target, prop) {
      const client = getAlibabaClient();
      const value = Reflect.get(client, prop);
      if (typeof value === 'function') {
        return value.bind(client);
      }
      return value;
    }
  });

  let cachedOpenRouterClient: OpenAI | null = null;
  let cachedOpenRouterKey: string | null = null;

  function getOpenRouterClient(): OpenAI {
    const currentKey = resolveOpenRouterKey();
    if (cachedOpenRouterClient && cachedOpenRouterKey === currentKey) {
      return cachedOpenRouterClient;
    }
    cachedOpenRouterKey = currentKey;
    cachedOpenRouterClient = new OpenAI({
      apiKey: currentKey || "dummy",
      baseURL: "https://openrouter.ai/api/v1",
      defaultHeaders: {
        "HTTP-Referer": "https://ai.studio/build",
        "X-Title": "EduAI Companion",
      }
    });
    return cachedOpenRouterClient;
  }

  const openrouter = new Proxy({} as OpenAI, {
    get(target, prop) {
      const client = getOpenRouterClient();
      const value = Reflect.get(client, prop);
      if (typeof value === 'function') {
        return value.bind(client);
      }
      return value;
    }
  });

  // --- API Routes ---

  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

  // Generic content generation proxy for OpenAI-compatible APIs
  app.post("/api/ai/:provider", async (req, res) => {
    const { provider } = req.params;
    const { messages, model, temperature = 0.7 } = req.body;

    const executeGeminiFallback = async (reason: string) => {
      console.warn(`[API Network Guard] Falling back to Gemini for provider ${provider}: ${reason}`);
      try {
        const contentsList: any[] = [];
        
        for (const msg of messages || []) {
          const role = msg.role === 'assistant' ? 'model' : msg.role === 'system' ? 'system' : 'user';
          if (role !== 'system') {
            const parts: any[] = [];
            if (Array.isArray(msg.content)) {
              for (const part of msg.content) {
                if (part.type === 'text') {
                  parts.push({ text: part.text || "" });
                } else if (part.type === 'image_url') {
                  const url = part.image_url?.url || "";
                  if (url.startsWith('data:')) {
                    const match = url.match(/^data:([^;]+);base64,(.+)$/);
                    if (match) {
                      parts.push({
                        inlineData: {
                          mimeType: match[1],
                          data: match[2]
                        }
                      });
                    }
                  }
                }
              }
            } else {
              parts.push({ text: String(msg.content || "") });
            }
            if (parts.length > 0) {
              contentsList.push({
                role: role,
                parts: parts
              });
            }
          }
        }

        const systemMessages = messages?.filter((m: any) => m.role === 'system');
        const systemInstruction = systemMessages?.map((m: any) => m.content).join("\n\n");

        const modelsToTry = ["gemini-3.5-flash", "gemini-3.1-flash-lite", "gemini-flash-latest"];
        let lastError: any = null;
        let response: any = null;

        for (const candidate of modelsToTry) {
          try {
            response = await geminiAi.models.generateContent({
              model: candidate,
              contents: contentsList.length > 0 ? contentsList : [{ role: 'user', parts: [{ text: "Hello" }] }],
              config: systemInstruction ? { systemInstruction } : undefined
            });
            if (response) {
              break;
            }
          } catch (err: any) {
            lastError = err;
            console.warn(`Gemini fallback model '${candidate}' is unavailable, trying next candidate...`);
          }
        }

        if (!response) {
          throw lastError || new Error("All Gemini models failed.");
        }

        const text = response.text || "";
        return res.json({
          choices: [
            {
              message: {
                role: "assistant",
                content: text
              }
            }
          ]
        });
      } catch (err: any) {
        console.error("Gemini fallback also failed:", err);
        return res.status(500).json({ error: { message: `Both ${provider} and Gemini fallback failed: ${err.message}` } });
      }
    };

    let client: OpenAI | null = null;
    let apiKey = "";

    switch (provider) {
      case "llama-primary":
      case "llama-secondary":
      case "groq-vision":
        client = groq;
        apiKey = process.env.GROQ_API_KEY || "";
        break;
      case "groq-gpt-oss":
      case "groq-qwen":
        client = openrouter;
        apiKey = resolveOpenRouterKey();
        break;
      case "alibaba-qwen":
      case "alibaba-deepseek":
        client = alibaba;
        apiKey = process.env.ALIBABA_API_KEY || "";
        break;
    }

    if (!apiKey || apiKey === "dummy" || apiKey === "undefined") {
      const neededKey = (provider === 'groq-gpt-oss' || provider === 'groq-qwen')
        ? 'OPENROUTER_API_KEY'
        : (provider.startsWith('groq') || provider.startsWith('llama'))
        ? 'GROQ_API_KEY'
        : provider.startsWith('alibaba')
        ? 'ALIBABA_API_KEY'
        : 'API_KEY';
      return await executeGeminiFallback(`${neededKey} is not configured.`);
    }

    let finalModel = model;
    if (finalModel === "groq-gpt-oss") {
      finalModel = "openai/gpt-oss-120b";
    } else if (finalModel === "groq-qwen") {
      finalModel = "qwen/qwen3.6-27b";
    }

    if (!finalModel) {
      finalModel = (
        provider === "llama-primary" ? "llama-3.3-70b-versatile" : 
        provider === "llama-secondary" ? "llama-3.1-8b-instant" : 
        provider === "alibaba-qwen" ? "qwen-plus" :
        provider === "alibaba-deepseek" ? "deepseek-v3" :
        provider === "groq-vision" ? "llama-3.2-11b-vision-instant" :
        provider === "groq-gpt-oss" ? "openai/gpt-oss-120b" : 
        provider === "groq-qwen" ? "qwen/qwen3.6-27b" :
        ""
      );
    }

    try {
      const payload: any = {
        model: finalModel,
        messages,
        temperature,
      };
      
      // Force JSON mode for alternative models to ensure they output valid JSON values
      if (provider === "groq-gpt-oss" || provider === "groq-qwen") {
        payload.response_format = { type: "json_object" };
      }
      
      // Only set max_tokens for non-Groq/llama providers (but include alternative openrouter-routed models)
      if ((!provider.startsWith('groq') && !provider.startsWith('llama')) || provider === "groq-gpt-oss" || provider === "groq-qwen") {
        payload.max_tokens = 4000;
      }

      const response = await client.chat.completions.create(payload);
      res.json(response);
    } catch (error: any) {
      const status = error.status || 500;
      if (status !== 500) {
        console.warn(`${provider} API returned status ${status}: ${error.message || 'Error'}`);
      } else {
        console.error(`${provider} error:`, error.message || error);
      }
      console.warn(`Attempting Gemini fallback after ${provider} request failure.`);
      return await executeGeminiFallback(`${provider} API failed with status ${status}: ${error.message}`);
    }
  });

  app.post("/api/ocr", async (req, res) => {
    const { image, language = "eng" } = req.body;
    const apiKey = process.env.OCR_SPACE_API_KEY;

    if (!apiKey) {
      return res.status(400).json({ error: "OCR.space API key missing." });
    }

    try {
      const formData = new URLSearchParams();
      formData.append("base64Image", image);
      formData.append("language", language);
      formData.append("apikey", apiKey);

      const response = await axios.post("https://api.ocr.space/parse/image", formData, {
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
      });
      res.json(response.data);
    } catch (error: any) {
      console.error("OCR error:", error);
      res.status(500).json({ error: error.message });
    }
  });

  app.post("/api/tts/google", async (req, res) => {
    const { text, lang } = req.body;
    try {
      const googleTTS = await import("google-tts-api");
      const urls = googleTTS.getAllAudioUrls(text, { lang, slow: false, splitPunct: ',.?!' });
      // Map URLs to our server-side proxy to completely bypass iframe CORS and referrer restriction policies
      const proxiedUrls = urls.map(u => `/api/tts/proxy?url=${encodeURIComponent(u.url)}`);
      res.json({ urls: proxiedUrls });
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  app.get("/api/tts/proxy", async (req, res) => {
    let url = req.query.url;
    if (!url || typeof url !== "string") {
      return res.status(400).send("Missing URL parameter");
    }
    const urlIndex = req.originalUrl.indexOf("url=");
    if (urlIndex !== -1) {
      url = decodeURIComponent(req.originalUrl.substring(urlIndex + 4));
    }
    try {
      const response = await axios({
        method: "get",
        url: url,
        responseType: "stream",
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          "Referer": "https://translate.google.com/"
        }
      });
      const contentType = response.headers["content-type"];
      res.setHeader("Content-Type", typeof contentType === "string" ? contentType : "audio/mpeg");
      response.data.pipe(res);
    } catch (error: any) {
      console.warn("Audio proxy error:", error.message);
      res.status(500).send("Audio proxy failed");
    }
  });

  app.post("/api/tts/hf", async (req, res) => {
    const { text, model } = req.body;
    const apiKey = process.env.HUGGINGFACE_API_KEY;
    try {
      if (!fetch) {
         // Some node versions might not have global fetch if very old, but since we use node 22 it's fine.
      }
      const fetchResponse = await fetch(`https://api-inference.huggingface.co/models/${model}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": apiKey ? `Bearer ${apiKey}` : ""
        },
        body: JSON.stringify({ inputs: text }) // Note: HF TTS expects "inputs"
      });
      if (!fetchResponse.ok) {
        throw new Error(`HF returned ${fetchResponse.status}`);
      }
      const buffer = await fetchResponse.arrayBuffer();
      const base64 = Buffer.from(buffer).toString("base64");
      res.json({ audio: `data:audio/flac;base64,${base64}` });
    } catch (e: any) {
      console.warn("HF TTS Error:", e);
      res.status(500).json({ error: e.message });
    }
  });

  const EDUCATIONAL_VIDEOS = [
    {
      keywords: ["class", "school", "teach", "learn", "student", "classroom", "math", "history", "english"],
      url: "https://raw.githubusercontent.com/intel-iot-devkit/sample-videos/master/classroom.mp4"
    },
    {
      keywords: ["jellyfish", "sea", "ocean", "water", "aquarium", "marine", "fish"],
      url: "https://vjs.zencdn.net/v/oceans.mp4"
    },
    {
      keywords: ["space", "nasa", "star", "planet", "galaxy", "orbit", "moon", "solar", "astronomy"],
      url: "https://images-assets.nasa.gov/video/KSC-20221116-MH-ART01-0001-Artemis_I_Launch_Highlights-3286049/KSC-20221116-MH-ART01-0001-Artemis_I_Launch_Highlights-3286049~orig.mp4"
    },
    {
      keywords: ["animal", "lion", "nature", "wild", "forest", "lion", "tiger", "bear", "savanna", "safari"],
      url: "https://www.w3schools.com/html/movie.mp4"
    }
  ];
  const DEFAULT_VIDEO = "https://www.w3schools.com/html/mov_bbb.mp4";

  const omniJobs = new Map<string, { status: string; url?: string; error?: string }>();

  function matchEducationalVideo(promptText: string): string {
    const promptLower = (promptText || "").toLowerCase();
    for (const entry of EDUCATIONAL_VIDEOS) {
      if (entry.keywords.some(kw => promptLower.includes(kw))) {
        return entry.url;
      }
    }
    return DEFAULT_VIDEO;
  }

  async function runGradioGeneration(jobId: string, promptText: string) {
    // Save current tokens
    const origHfToken = process.env.HF_TOKEN;
    const origHfApiKey = process.env.HUGGINGFACE_API_KEY;

    try {
      const { Client } = await import("@gradio/client");
      console.log(`[OmniHuman] Connecting to Hugging Face space multimodalart/self-forcing for prompt: "${promptText}"`);
      
      // Temporarily remove tokens from process.env so @gradio/client doesn't auto-read them
      delete process.env.HF_TOKEN;
      delete process.env.HUGGINGFACE_API_KEY;

      let client;
      try {
        client = await Client.connect("multimodalart/self-forcing", { hf_token: "" } as any);
      } finally {
        // Restore them immediately after connecting
        if (origHfToken !== undefined) process.env.HF_TOKEN = origHfToken;
        if (origHfApiKey !== undefined) process.env.HUGGINGFACE_API_KEY = origHfApiKey;
      }
      
      const predictionPromise = client.predict("/video_generation_handler_streaming", {
        prompt: promptText,
        seed: -1,
        fps: 15
      });

      // Video generation can take up to ~60-90 seconds on HF public zero spaces under load, so let's allow a generous 120s timeout.
      const timeoutPromise = new Promise((_, reject) => 
        setTimeout(() => reject(new Error("Timeout after 120 seconds")), 120000)
      );

      const result: any = await Promise.race([predictionPromise, timeoutPromise]);
      
      console.log(`[OmniHuman] Gradio result received for ${jobId}:`, JSON.stringify(result));
      
      if (result && result.data && Array.isArray(result.data)) {
        // The first output returned is a Video object (or FileData) which contains {video: {url: "..."}}
        const firstOutput = result.data[0];
        let videoUrl = "";

        if (firstOutput && firstOutput.video && firstOutput.video.url) {
          videoUrl = firstOutput.video.url;
        } else if (firstOutput && typeof firstOutput === "object" && firstOutput.url) {
          videoUrl = firstOutput.url;
        } else if (typeof firstOutput === "string" && firstOutput.startsWith("http")) {
          videoUrl = firstOutput;
        }

        if (videoUrl && videoUrl.startsWith("http")) {
          console.log(`[OmniHuman] Generated video via Gradio space successfully: ${videoUrl}`);
          omniJobs.set(jobId, { status: "succeeded", url: videoUrl });
          return;
        }
      }
      throw new Error("Could not find video URL in Gradio response structure");
    } catch (err: any) {
      console.warn(`[OmniHuman] Gradio generation failed or timed out (${err.message}). Using high-quality matched fallback...`);
      const fallbackUrl = matchEducationalVideo(promptText);
      omniJobs.set(jobId, { status: "succeeded", url: fallbackUrl });
    }
  }

  app.post("/api/video/generate", async (req, res) => {
    const { prompt, model } = req.body;

    // omnihuman-1 is the free primary generator that does not require replicate or any API keys
    if (model === "omnihuman-1") {
      const jobId = "omni-" + Date.now();
      omniJobs.set(jobId, { status: "processing" });
      
      // Start background generation without blocking response
      runGradioGeneration(jobId, prompt || "");
      
      return res.json({ id: jobId, status: "processing" });
    }

    const apiKey = process.env.REPLICATE_API_TOKEN;
    if (!apiKey) {
      return res.status(400).json({ error: "REPLICATE_API_TOKEN is required for Replicate generators. Please set it in Settings -> Secrets." });
    }
    try {
      const Replicate = (await import("replicate")).default;
      const replicate = new Replicate({ auth: apiKey });
      
      const modelIdentifier = model === "replicate-minimax" ? "minimax/video-01" : "luma/ray";
      
      const prediction = await replicate.predictions.create({
        model: modelIdentifier as any,
        input: { prompt: prompt }
      });
      
      res.json({ id: prediction.id, status: prediction.status });
    } catch (e: any) {
      console.warn("Replicate Video Error:", e);
      if (e.message?.includes("402 Payment Required") || e.response?.status === 402 || e.message?.includes("Insufficient credit")) {
        console.warn("Falling back to sample video due to insufficient Replicate credits.");
        return res.json({ id: "mock-video-id", status: "started" });
      }
      res.status(500).json({ error: e.message });
    }
  });

  app.get("/api/video/status/:id", async (req, res) => {
    const jobId = req.params.id;
    if (jobId === "mock-video-id") {
      return res.json({ 
        status: "succeeded", 
        url: "https://www.w3schools.com/html/mov_bbb.mp4" 
      });
    }

    // Check if it is an OmniHuman job
    if (omniJobs.has(jobId)) {
      const job = omniJobs.get(jobId);
      return res.json(job);
    }

    const apiKey = process.env.REPLICATE_API_TOKEN;
    if (!apiKey) {
      return res.status(400).json({ error: "REPLICATE_API_TOKEN is required." });
    }
    try {
      const Replicate = (await import("replicate")).default;
      const replicate = new Replicate({ auth: apiKey });
      
      const prediction = await replicate.predictions.get(jobId);
      
      if (prediction.status === "succeeded") {
         const url = Array.isArray(prediction.output) ? prediction.output[0] : (prediction.output as any)?.url || prediction.output;
         res.json({ status: prediction.status, url });
      } else if (prediction.status === "failed" || prediction.status === "canceled") {
         res.status(500).json({ error: "Video generation failed or was canceled." });
      } else {
         res.json({ status: prediction.status });
      }
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  app.post("/api/images/generate", async (req, res) => {
    const { prompt, provider } = req.body;
    
    if (provider === "gemini-imagen") {
      const apiKey = resolveGeminiKey();
      if (!apiKey || apiKey === "dummy" || apiKey === "undefined") {
        return res.status(400).json({ error: "GEMINI_API_KEY missing" });
      }

      // Try 1: gemini-2.5-flash-image (The designated Flash Image model)
      try {
        console.log("Attempting image generation with 'gemini-2.5-flash-image'...");
        const response = await geminiAi.models.generateContent({
          model: 'gemini-2.5-flash-image',
          contents: {
            parts: [
              { text: prompt }
            ]
          },
          config: {
            imageConfig: {
              aspectRatio: "1:1"
            }
          }
        });

        let foundBase64 = null;
        if (response.candidates && response.candidates[0]?.content?.parts) {
          for (const part of response.candidates[0].content.parts) {
            if (part.inlineData && part.inlineData.data) {
              foundBase64 = part.inlineData.data;
              break;
            }
          }
        }

        if (foundBase64) {
          console.log("Image successfully generated with 'gemini-2.5-flash-image'!");
          return res.json({ url: `data:image/jpeg;base64,${foundBase64}` });
        }
      } catch (err1: any) {
        console.warn("gemini-2.5-flash-image failed:", err1.message);
      }

      // Try 2: imagen-3.0-generate-002
      try {
        console.log("Attempting image generation with 'imagen-3.0-generate-002'...");
        const response = await geminiAi.models.generateImages({
          model: 'imagen-3.0-generate-002',
          prompt: prompt,
          config: {
            numberOfImages: 1,
            outputMimeType: 'image/jpeg',
            aspectRatio: '1:1'
          }
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
          const image = response.generatedImages[0];
          const base64 = image.image.imageBytes;
          if (base64) {
            console.log("Image successfully generated with 'imagen-3.0-generate-002'!");
            return res.json({ url: `data:image/jpeg;base64,${base64}` });
          }
        }
      } catch (err2: any) {
        console.warn("imagen-3.0-generate-002 failed:", err2.message);
      }

      // Fallback Strategy: Pollinations (FLUX) so image generation NEVER fails!
      console.warn("All Gemini image generation attempts failed. Falling back to Pollinations in the backend.");
      const enhancedPrompt = `${prompt}, masterpiece emoji-style figurine 3D render, 3D Disney Character render, pure white background, natural beauty, ultra-detailed 3D digital asset, vibrant colors, perfect composition, no text overlays, museum-quality detail`;
      const fallbackUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(enhancedPrompt)}?width=1024&height=1024&nologo=true&model=flux&seed=${Math.floor(Math.random() * 100000)}`;
      return res.json({ url: fallbackUrl, isFallback: true });
    }

    if (provider === "perchance") {
      try {
        console.log("Attempting image generation with Perchance AI...");
        const seed = Math.floor(Math.random() * 100000);
        // Approach 1 direct API url (Fetch on backend to avoid CORS)
        const perchanceUrl = `https://perchance.org/imageapi?prompt=${encodeURIComponent(prompt)}&width=1024&height=1024&seed=${seed}`;
        
        const response = await fetch(perchanceUrl, {
          method: 'GET',
          headers: {
            'Accept': 'image/png, image/jpeg',
          },
        });
        
        if (!response.ok) {
          throw new Error(`Perchance API error: ${response.status}`);
        }
        
        const arrayBuffer = await response.arrayBuffer();
        const base64 = Buffer.from(arrayBuffer).toString('base64');
        console.log("Image successfully generated with Perchance AI!");
        return res.json({ url: `data:image/jpeg;base64,${base64}` });
      } catch (error: any) {
        console.warn("Perchance generation failed, falling back to Pollinations:", error.message);
        // Fallback to pollinations to guarantee successful render
        const seed = Math.floor(Math.random() * 100000);
        const fallbackUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=1024&nologo=true&model=flux&enhance=true&seed=${seed}`;
        return res.json({ url: fallbackUrl, isFallback: true });
      }
    }

    if (provider === "pollinations") {
      try {
        console.log("Attempting image generation with Pollinations AI...");
        const seed = Math.floor(Math.random() * 100000);
        // Approach 2 Recommended direct URL return (super fast, CORS-friendly)
        const pollinationsUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=1024&nologo=true&model=flux&enhance=true&seed=${seed}`;
        return res.json({ url: pollinationsUrl });
      } catch (error: any) {
        console.warn("Pollinations generation failed:", error.message);
        return res.status(500).json({ error: "Pollinations image generation failed" });
      }
    }
    
    return res.status(400).json({ error: "Unsupported provider" });
  });

  // --- Individual Learner Development Plan (ILDP) Route ---

  function generateLocalFallbackILDP(studentName: string, grade: string, subjects: any[]) {
    const lowSubjects = subjects.filter((s: any) => s.mark < 70);
    const highSubjects = subjects.filter((s: any) => s.mark >= 75);

    const strengths = highSubjects.map((s: any) => `Excellent mastery of foundational concepts and high accuracy in Grade ${grade} ${s.name} (${s.mark}%).`)
      .slice(0, 3);
    if (strengths.length === 0) {
      strengths.push("Shows great curiosity, consistent learning attitude, and active participation in class discussions.");
    }

    const weaknesses = lowSubjects.map((s: any) => `Currently finding some topics challenging in ${s.name} (${s.mark}%), requiring targeted revision and problem-solving exercises.`)
      .slice(0, 3);
    if (weaknesses.length === 0) {
      weaknesses.push(`Doing well overall; could benefit from challenging extension tasks to nurture advanced thinking skills.`);
    }

    const recommendations = [
      `Engage with the personalized exercises in Content Creator Studio, focusing specifically on weak areas.`,
      `Hold 1-on-1 focus chats with the EduAI Tutor to review problem-solving strategies.`,
      `Form small group study sessions with peers using Study Groups in Class Management.`
    ];

    const actionPlan = [
      { task: "Revise high-priority syllabus sections and build summaries", milestone: "Within 2 weeks", status: "In Progress" },
      { task: "Consult AI Tutor for interactive quizzes on weaker chapters", milestone: "Within 3 weeks", status: "Pending" },
      { task: "Submit a practice portfolio task for teacher review", milestone: "Before major exam", status: "Pending" }
    ];

    return { strengths, weaknesses, recommendations, actionPlan };
  }

  app.post("/api/reports/ildp", async (req, res) => {
    const { studentName, grade, subjects } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === "dummy" || apiKey === "undefined") {
      return res.json(generateLocalFallbackILDP(studentName, grade, subjects));
    }
    try {
      const prompt = `
        You are a supportive, insightful educational counselor and South African school advisor.
        Generate a constructive and professional Individual Learner Development Plan (ILDP) for a school student with this profile:
        Student Name: ${studentName}
        Grade: ${grade}
        Performance Stats: ${JSON.stringify(subjects)}

        The response must be a valid raw JSON object matching this exact TypeScript interface:
        {
          "strengths": string[];
          "weaknesses": string[];
          "recommendations": string[];
          "actionPlan": { task: string; milestone: string; status: 'Pending' | 'In Progress' | 'Completed' }[];
        }

        Make sure your recommendations are encouraging and specifically reference their low/high subjects. Align suggestions with South African CAPS-standards (e.g. SBA, formative tests). Do not format the response with markdown formatting (no backticks, no text like 'json' or explanations), only output a parseable JSON block.
      `;
      const response = await geminiAi.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          temperature: 0.7,
        }
      });
      const text = response.text || "";
      const data = safeJsonParse(text);
      res.json(data);
    } catch (err: any) {
      console.warn("Gemini ILDP Generation failed, using local builder:", err.message);
      res.json(generateLocalFallbackILDP(studentName, grade, subjects));
    }
  });

  
  app.post("/api/gemini/action", async (req, res) => {
    const { action, input } = req.body || {};
    const apiKey = resolveGeminiKey();
    if (!apiKey || apiKey === "" || apiKey === "dummy" || apiKey === "undefined") {
      return res.status(400).json({ error: "GEMINI_API_KEY is not configured in settings." });
    }

    try {
      const model = "gemini-3.5-flash";

      const generateContentWithFallback = async (options: { model: string, contents: any, config?: any }) => {
        const modelsToTry = cachedWorkingModel 
          ? [cachedWorkingModel, "gemini-3.5-flash", "gemini-3.1-flash-lite", "gemini-flash-latest"]
          : ["gemini-3.5-flash", "gemini-3.1-flash-lite", "gemini-flash-latest"];
        
        let lastError: any = null;
        for (const candidate of modelsToTry) {
          try {
            const actualOptions = { ...options, model: candidate };
            const result = await geminiAi.models.generateContent(actualOptions);
            if (result) {
              cachedWorkingModel = candidate; // Cache successfully validated model
              return result;
            }
          } catch (err: any) {
            lastError = err;
            console.info(`Gemini candidate model '${candidate}' is currently unavailable. trying alternative...`);
          }
        }
        throw lastError || new Error("All candidate Gemini models were unavailable.");
      };

      switch (action) {
        case "generate-educational": {
          const { type, details } = input;
          const systemInstruction = `${MASTER_SYSTEM_PROMPT}\n\nYour task is to generate high-quality educational materials: ${type}.\nThe content must be strictly CAPS aligned, professionally formatted in HTML with Tailwind CSS, and ready for classroom use. DO NOT USE MARKDOWN. NEVER INJECT <script src="https://cdn.tailwindcss.com"></script>. The app already has Tailwind.`;
          const response = await generateContentWithFallback({
            model,
            contents: `Generate a ${type} based on the following details: ${details}. Format as valid HTML with Tailwind CSS classes. Follow the EduAI design style (colored banners, pill-shaped blocks, distinct sections, vibrant design). Do NOT add Tailwind CDN scripts.`,
            config: {
              systemInstruction,
              temperature: 0.7,
            },
          });
          return res.json({ text: response.text });
        }

        case "generate-caps": {
          const isLessonPlan = ['Lesson Plan', 'Weekly Lesson Plan', 'Unit Plan', 'lesson-plan'].includes(input.contentType);
          const isStudyGuide = ['Study Guide / Learning Notes', 'Revision Pack', 'Daily Lesson Notes', 'Learning Activity'].includes(input.contentType);

          let contentTypeEng: 'lesson-plan' | 'worksheet' | 'study-guide' = 'worksheet';
          if (isLessonPlan) contentTypeEng = 'lesson-plan';
          else if (isStudyGuide) contentTypeEng = 'study-guide';

          const { system, user } = EduAIPromptEngine.assemblePrompt({
            contentType: contentTypeEng,
            grade: input.grade || "4",
            subject: input.subject || "Mathematics",
            topic: input.topic || "Addition",
            language: input.language || 'English',
            learnerProfile: input.learnerProfile || 'General Class',
            additionalInstructions: input.additionalInstructions || '',
            term: input.term || '1',
            week: input.week ? parseInt(input.week) : undefined,
            duration: input.duration || '2 hours',
            capsReference: input.capsReference || '',
            includeWorksheet: !!input.includeWorksheet
          });

          const response = await generateContentWithFallback({
            model,
            contents: user,
            config: {
              systemInstruction: system,
              responseMimeType: "application/json",
              responseSchema: {
                type: Type.OBJECT,
                properties: {
                  content: { type: Type.STRING },
                  memo: { type: Type.STRING },
                  rubric: { type: Type.STRING },
                  assessmentCriteria: { type: Type.STRING },
                  successIndicators: { type: Type.ARRAY, items: { type: Type.STRING } },
                  imagePrompt: { type: Type.STRING }
                },
                required: ["content", "imagePrompt"]
              }
            }
          });
          return res.json(safeJsonParse(response.text));
        }

        case "generate-visual": {
          const systemInstruction = `${MASTER_SYSTEM_PROMPT}\n\nThe 'content' field in your JSON response MUST be stunningly designed HTML with Tailwind CSS. DO NOT use generic Markdown.`;
          const isPoster = input.visualType?.toLowerCase().includes('poster');
          const isInfographic = input.visualType?.toLowerCase().includes('infographic') || input.visualType?.toLowerCase().includes('mind map');
          const isLessonDisplay = input.visualType?.toLowerCase().includes('display') || input.visualType?.toLowerCase().includes('chart') || input.visualType?.toLowerCase().includes('wall') || input.visualType?.toLowerCase().includes('lesson display');
          const isDiagram = input.visualType?.toLowerCase().includes('diagram');
          const isFlashcard = input.visualType?.toLowerCase().includes('flashcard') || input.visualType?.toLowerCase().includes('learning card');

          let visualPrompt = "";
          if (isPoster) {
            visualPrompt = `
              Create an exceptionally polished, high-resolution educational poster layout on the CAPS topic: "${input.topic}" for South African Grade ${input.grade} ${input.subject} classrooms.
              
              CRITICAL RULE: DO NOT generate quiz questions, exam exercises, worksheets, homework, fill-in-the-blanks, or assessment tasks. This is exclusively a visual teaching aid.
              
              AESTHETICS & STRUCTURE SPECIFICATION:
              1. Clean Visual Hierarchy: Establish a clear flow from the top down. Use a generous, modern header banner, well-spaced bento-grid sections, and an impressive footer.
              2. Minimalist Vector Style: Keep illustrations, icons, and layout clean, elegant, and modern. Avoid chaotic overlays, noisy gradients, or over-rendered elements.
              3. Color Palette: Use a cohesive, premium palette of 3-4 professional colors (e.g., deep slate blue, warm terracotta accent, clean cream background). Avoid neon rainbow noise.
              4. Central Visual Component: A spectacular, high-resolution hero section featuring a minimalist vector style illustration portraying "${input.topic}" in a clean, professional manner (e.g., [Illustration: ${input.topic} depicted in an elegant, clean South African context]).
              5. Content Blocks: Present key concepts inside elegantly spaced card containers (rounded-2xl, subtle border, shadow) with large beautifully tracking headers, concise bullet points (4-8 words), and relevant emojis.
              
              Ensure every element is crisp, accessible, and ready for immediate high-resolution classroom display printing.
            `;
          } else if (isInfographic) {
            visualPrompt = `
              Design an incredibly structured, premium academic infographic on the CAPS topic: "${input.topic}" for South African Grade ${input.grade} ${input.subject} classrooms.
              
              CRITICAL RULE: DO NOT generate homework, questions, assessment exercises, or study guides with dense text. Focus on graphics, statistics, and high-impact visual layouts.
              
              AESTHETICS & STRUCTURE SPECIFICATION:
              1. High-Resolution Educational Poster Layout: Organize complex theories into a dual-column matrix or an asymmetrical bento grid structure.
              2. Minimalist Vector Style: Icons, graphics, charts, and mascots must be styled as modern flat minimalist vector graphics with clean outlines and balanced negative space.
              3. Clean Visual Hierarchy: Guide the eye with clean numbered points, bold colored accents, distinct callout panels (rounded-xl), and elegant divider ribbons.
              4. Concept breakdown: Each section must feature a descriptive visual mockup placeholder (e.g., [Illustration: Clean vector infographic icon of key concept]) alongside hyper-concise capsule bullet facts.
              5. Visual Anchors: Include a striking comparison matrix or a centered concentric diagram showing relationships cleanly.
              
              The final product must be highly instructive, visually mesmerizing, and optimized for classroom display.
            `;
          } else if (isLessonDisplay) {
            visualPrompt = `
              Design a stunning, high-resolution visual Lesson Display / Anchor Chart on on the CAPS topic: "${input.topic}" for South African Grade ${input.grade} ${input.subject} classrooms.
              
              CRITICAL RULE: This is a permanent reference display, not a quiz or activity workbook. Ensure zero assessment activities or worksheet blocks.
              
              AESTHETICS & STRUCTURE SPECIFICATION:
              1. High-Resolution Educational Poster Layout: Style this as a full-screen, landscape or portrait anchor chart. Frame it with a bold, professional border and a large chalkboard-style or modern minimalist header.
              2. Clean Visual Hierarchy: Create high-contrast floating keyword cards, word-wall cards, or step-by-step process paths. Use beautiful, generous negative space so keywords stand out clearly at a distance of 5 meters.
              3. Minimalist Vector Style: All diagram lines, connecting arrows, indicators, and background grids must use a sleek, modern minimalist vector style.
              4. Primary Focal Point: Frame a central diagram representing the core mechanism of "${input.topic}" (using clean labeled lines, e.g., pointing out labels like "ROOT", "PHOTOSYNTHESIS", "REACTIONS" in stark white backgrounds with crisp shadows).
              5. Vocabulary Anchors: Highlight 4-6 key term definition cards, beautifully styled with dashed colored borders, a neat custom emoji, and single-sentence explanations.
              
              Make it visually inspiring, clean, and perfectly suited for prominent display on classroom bulletin boards or digital visual screens.
            `;
          } else if (isFlashcard) {
            visualPrompt = `
              Design a set of professional, double-sided visual educational flashcards for South African Grade ${input.grade} ${input.subject} on "${input.topic}".
              
              DESIGN REQUIREMENTS:
              - Grid Layout: Show multiple cards in a beautifully aligned grid (2 or 3 per row).
              - Each card must have:
                - Front side: Large bold title, a delightful custom icon or emoji, and a quick catchy hint or question.
                - Back side: Clear conceptual explanation, a South African contextual/CAPS example, and a small fun "Did you know?" fact box.
              - Aesthetics: Rounded-3xl corners (at least 24px), thick colored outlines (3px solid border that changes color per card), and micro shadow depth.
              - Use rich, vibrant background gradients or clean high-contrast card themes. Text must be large and instantly legible.
            `;
          } else if (isDiagram) {
            visualPrompt = `
              Create a crystal-clear, beautifully illustrated scientific diagram of "${input.topic}" specifically adapted for South African Grade ${input.grade} ${input.subject} learners.
              
              CRITICAL: This is a teaching demonstration visual aid. DO NOT write worksheet questions, exercises, or tests.
              
              DIAGRAM ARCHITECTURE:
              - Flow & Layout: Set against a highly realistic, vibrant South African biome / context (e.g. water cycles over the Drakensberg mountains, food webs of the Kruger savanna, or plant cell structure featuring indigenous fynbos/Proteas).
              - Connections: Draw bright, stylized, high-contrast flowing directional arrows pointing out movement, cycle flow, or ecosystem energy transfers.
              - Diagram Labels: Place 5-6 crisp, floating educational pointing cards (labels like 'KAROO', 'ALOE ROOT', 'ENERGY FLOW') connected to their targets. Styling: stark white background, rounded border, sharp shadows, and bold scientific monospace/sans-serif fonts.
              - Key/Legend: Include a small, highly tidy legend card at the bottom right with colorful indicator boxes explaining key parts.
              - Ensure the diagram looks detailed, professional, and is highly instructive for display.
            `;
          } else {
            visualPrompt = `Create a highly visual display, not a worksheet, for Grade ${input.grade} ${input.subject} on topic ${input.topic}. Ensure it is styled beautifully.`;
          }

          const prompt = `
            ${visualPrompt}
            Language: ${input.language}
            Style: ${input.style}
            Color: ${input.colorScheme}
            Content Details: ${input.specificContent}
            Quantity: ${input.quantity}
            Additional Info: ${IMAGE_PROMPT_GOLDEN_RULE}
          `;

          const response = await generateContentWithFallback({
            model,
            contents: prompt,
            config: { 
              systemInstruction, 
              responseMimeType: "application/json",
              responseSchema: {
                type: Type.OBJECT,
                properties: {
                  content: { type: Type.STRING },
                  description: { type: Type.STRING },
                  printInstructions: { type: Type.STRING },
                  imagePrompt: { type: Type.STRING }
                },
                required: ["content", "description", "imagePrompt"]
              }
            }
          });
          return res.json(safeJsonParse(response.text));
        }

        case "generate-admin": {
          const systemInstruction = `${MASTER_SYSTEM_PROMPT}\n\nGenerate a formal ${input.documentType} for ${input.schoolName}.
          The tone should be ${input.tone}.
          IMPORTANT: The 'content' field MUST be formatted as visually pleasing HTML string styled with Tailwind CSS classes. DO NOT use generic Markdown.`;
          const prompt = `
            Type: ${input.documentType}
            Purpose: ${input.purpose}
            Key Points: ${input.keyPoints}
            Include Reply Slip: ${input.includeReplySlip}
            Language: ${input.language}
          `;
          const response = await generateContentWithFallback({
            model,
            contents: prompt,
            config: { 
              systemInstruction, 
              responseMimeType: "application/json",
              responseSchema: {
                type: Type.OBJECT,
                properties: {
                  content: { type: Type.STRING },
                  notes: { type: Type.STRING },
                  documentType: { type: Type.STRING },
                  imagePrompt: { type: Type.STRING }
                },
                required: ["content", "documentType"]
              }
            }
          });
          return res.json(safeJsonParse(response.text));
        }

        case "ocr-scan": {
          const { imageData, language, isHandwritten } = input;
          const items = Array.isArray(imageData) ? imageData : [imageData];
          const textContents: string[] = [];
          const partsToProcess: any[] = [];
          
          for (const item of items) {
            let mimeType = "image/jpeg";
            let base64Data = item;
            
            if (item.startsWith("data:")) {
              const p = item.split(";base64,");
              if (p.length === 2) {
                mimeType = p[0].replace("data:", "").split(";")[0];
                base64Data = p[1];
              } else {
                base64Data = item.split(",")[1] || item;
              }
            }
            
            if (mimeType.includes("wordprocessingml") || mimeType.includes("msword") || mimeType.includes("officedocument") || mimeType === "application/docx" || mimeType === "docx") {
              const docxText = await tryExtractDocxText(base64Data);
              if (docxText) {
                textContents.push(docxText);
              }
            } else {
              partsToProcess.push({
                inlineData: { mimeType, data: base64Data }
              });
            }
          }
          
          let resultText = "";
          if (partsToProcess.length > 0) {
            const prompt = `Extract all text from the attached ${partsToProcess.length} page/s or document accurately, assuming the text is in ${language}.
            ${isHandwritten ? "The image/document contains handwritten notes, assessments, or drawings. Use professional Multimodal Handwriting Recognition to transcribe printed text, cursive handwriting, math symbols, annotations, and notes precisely." : ""}
            Format it cleanly. Make no other comments.`;
            
            const response = await generateContentWithFallback({
              model,
              contents: [
                { role: 'user', parts: [
                  { text: prompt },
                  ...partsToProcess
                ]}
              ]
            });
            resultText = response.text || "";
          }
          
          if (textContents.length > 0) {
            if (resultText) {
              resultText += "\n\n=== Extracted Word Document Text ===\n\n" + textContents.join("\n\n");
            } else {
              resultText = textContents.join("\n\n");
            }
          }
          
          return res.json({ extractedText: resultText });
        }

        case "ocr-grade": {
          const { imageData, rubric, language, isHandwritten, behavioralAspects, adjustLateSubmission } = input;
          const items = Array.isArray(imageData) ? imageData : [imageData];
          const textContents: string[] = [];
          const partsToProcess: any[] = [];
          
          for (const item of items) {
            let mimeType = "image/jpeg";
            let base64Data = item;
            
            if (item.startsWith("data:")) {
              const p = item.split(";base64,");
              if (p.length === 2) {
                mimeType = p[0].replace("data:", "").split(";")[0];
                base64Data = p[1];
              } else {
                base64Data = item.split(",")[1] || item;
              }
            }
            
            if (mimeType.includes("wordprocessingml") || mimeType.includes("msword") || mimeType.includes("officedocument") || mimeType === "application/docx" || mimeType === "docx") {
              const docxText = await tryExtractDocxText(base64Data);
              if (docxText) {
                textContents.push(docxText);
              }
            } else {
              partsToProcess.push({
                inlineData: { mimeType, data: base64Data }
              });
            }
          }
          
          const textDocContext = textContents.length > 0 
             ? `\n\nWord Document content uploaded by student:\n${textContents.join("\n\n")}`
             : "";

          let behaviorPrompt = "";
          if (behavioralAspects && Array.isArray(behavioralAspects) && behavioralAspects.length > 0) {
            behaviorPrompt = `\n- Evaluate the student's submission on these behavioral/work habit dimensions: ${behavioralAspects.join(", ")}. Analyze their work layout, structure, and handwriting quality to provide a dedicated, supportive "Learning Behavior & Focus Feedback" section in the overall feedback.`;
          }
          if (adjustLateSubmission) {
            behaviorPrompt += `\n- Special Context: This was submitted late, or as a redo attempt. Maintain rigorous academic scoring standards, but add a supportive, encouraging remark acknowledging their initiative to catch up or refine their work.`;
          }
          
          const prompt = `You are an AI Grader and South African CAPS Curriculum Specialist.
          Analyze these student assessment page/s.
          ${textDocContext}
          
          TASK 1: MEMORANDUM & RUBRIC QUALITY CHECK & AUTO-GENERATION
          - You are supplied with this Teacher's Memorandum/Rubric: "${rubric || ''}".
          - IF the supplied Memorandum/Rubric is missing, blank, or extremely brief:
            * You MUST automatically generate a highly comprehensive, detailed Memorandum and grading rubric mapped to CAPS criteria based on the student's work and the questions/answers found in their submission.
            * Describe this generation in 'memoCorrectionReport' (mention that a comprehensive Memorandum/Rubric has been dynamically generated to complete grading).
            * Set 'originalMemoCorrected' to true.
            * Produce the newly generated Memorandum/Rubric in 'correctedMemo'.
          - IF a Memorandum/Rubric IS supplied by the teacher:
            * Review it for correctness, spelling mistakes, factual errors, marks allotment problems, CAPS curriculum misalignments, or lack of clarity.
            * If any issues are found, correct them. Describe exactly what issues were corrected in 'memoCorrectionReport'.
            * Set 'originalMemoCorrected' to true if you modified it, or false if it was fully correct.
            * Return the (modified/corrected) Memorandum/Rubric in 'correctedMemo'.
          
          TASK 2: EVALUATION AND GRADING
          - Extract all text answers from the student's submission pages and return it in 'extractedText'.
          - Evaluate each question's answer accurately according to the verified or generated memorandum/rubric.${behaviorPrompt}
          - ${isHandwritten ? "The student's inputs may be handwritten. Apply deep Handwriting Recognition (HWR) and optical reading on the student answers. Be forgiving on cursive forms, crossed-out errors, printed text, mathematical symbols, and structural layout answers." : ""}
          - Sum and return the total obtained score as a string in 'totalScore' (e.g., "18/25" or "72%").
          - List marks and reasoning for each question individually in the array 'marksPerQuestion'.
          - Provide highly constructive, encouraging feedback for the learner in 'feedback' (use encouraging South African educational tone).`;
          
          const contentsToUse: any[] = [
            { text: prompt }
          ];
          for (const part of partsToProcess) {
            contentsToUse.push(part);
          }
          
          const response = await generateContentWithFallback({
            model,
            contents: [
              { role: 'user', parts: contentsToUse }
            ],
            config: {
              responseMimeType: "application/json",
              responseSchema: {
                type: Type.OBJECT,
                properties: {
                  extractedText: { type: Type.STRING },
                  marksPerQuestion: { type: Type.ARRAY, items: { type: Type.STRING } },
                  feedback: { type: Type.STRING },
                  totalScore: { type: Type.STRING },
                  originalMemoCorrected: { type: Type.BOOLEAN },
                  memoCorrectionReport: { type: Type.STRING },
                  correctedMemo: { type: Type.STRING }
                },
                required: ["extractedText", "marksPerQuestion", "feedback", "totalScore", "originalMemoCorrected", "memoCorrectionReport", "correctedMemo"]
              }
            }
          });
          return res.json(safeJsonParse(response.text));
        }

        case "text-grade": {
          const { studentAnswers, memo, rubric, language } = input;
          const prompt = `You are an AI Grader. Grade this student's written response in ${language || 'English'}.
          Student answers: ${studentAnswers}
          Memorandum / Memo notes: ${memo}
          Rubric guidelines: ${rubric}
          
          Perform the following steps:
          1. Evaluate each answer.
          2. Calculate marks obtained per question according to the memo and rubric.
          3. Provide encouraging and highly constructive feedback for the student.
          4. Suggest actionable next steps to improve.
          5. Sum the final score and return a neat JSON report.`;

          const response = await generateContentWithFallback({
            model,
            contents: prompt,
            config: {
              responseMimeType: "application/json",
              responseSchema: {
                type: Type.OBJECT,
                properties: {
                  marksPerQuestion: { type: Type.ARRAY, items: { type: Type.STRING } },
                  feedback: { type: Type.STRING },
                  totalScore: { type: Type.STRING }
                },
                required: ["marksPerQuestion", "feedback", "totalScore"]
              }
            }
          });
          return res.json(safeJsonParse(response.text));
        }

        case "chat": {
          const { messages } = input;
          const response = await generateContentWithFallback({
            model,
            contents: messages,
            config: {
              systemInstruction: "You are a friendly and encouraging South African school tutor for EduAI Companion. You help students understand complex CAPS curriculum concepts in simple terms. Use local South African examples (e.g. using Rands, referring to provinces) and be patient. Keep explanations concise.",
            }
          });
          return res.json({ text: response.text });
        }

        default:
          return res.status(400).json({ error: "Unsupported action" });
      }
    } catch (error: any) {
      const errMsg = error.message || error.toString();
      let status = 500;
      const rawStatus = error.status || error.response?.status;
      if (typeof rawStatus === 'number' && Number.isInteger(rawStatus) && rawStatus >= 100 && rawStatus < 600) {
        status = rawStatus;
      }
      if (errMsg.toLowerCase().includes('permissions') || errMsg.toLowerCase().includes('api key') || errMsg.toLowerCase().includes('auth') || errMsg.toLowerCase().includes('dummy')) {
         status = 401;
      }

      // Capture failure for Admin Debug Console
      failedRequestsLog.unshift({
        id: `err_${Date.now()}_${Math.random().toString(36).substr(2, 5)}`,
        timestamp: new Date().toISOString(),
        provider: 'gemini',
        endpoint: `/api/gemini/action`,
        model: 'gemini-3.5-flash',
        error: errMsg,
        rawResponse: error.response?.data || error.stack || error.message || String(error),
        requestPayload: {
          action,
          input: input ? { ...input, imageData: input.imageData ? '[Muted Image Data]' : undefined } : undefined
        }
      });
      if (failedRequestsLog.length > 50) {
        failedRequestsLog.pop();
      }

      console.error(`Gemini server error for action '${action}':`, errMsg);
      return res.status(status).json({ error: errMsg || "Failed to execute server-side action." });
    }
  });

  // --- Vite Middleware ---

  async function initializeAndListen() {
    if (process.env.VERCEL) {
      return;
    }

    if (process.env.NODE_ENV !== "production") {
      const { createServer: createViteServer } = await import("vite");
      const vite = await createViteServer({
        server: { middlewareMode: true },
        appType: "spa",
      });
      app.use(vite.middlewares);
    } else {
      const distPath = path.join(process.cwd(), "dist");
      app.use(express.static(distPath));
      app.get("*", (req, res) => {
        res.sendFile(path.join(distPath, "index.html"));
      });
    }

    if (!process.env.VERCEL) {
      const PORT = 3000;
      app.listen(PORT, "0.0.0.0", () => {
        console.log(`Server running on http://localhost:${PORT}`);
      });
    }
  }

  initializeAndListen();

  export default app;
