import { CAPS_LESSON_PLAN_SYSTEM_PROMPT } from "./src/lib/prompts/caps-lesson-plan-prompt";
import { EduAIPromptEngine } from "./src/lib/prompt-engine";
import express from "express";
import path from "path";
import dotenv from "dotenv";
import OpenAI from "openai";
import Anthropic from "@anthropic-ai/sdk";
import axios from "axios";
import { GoogleGenAI, Type } from "@google/genai";


// Cache the last verified working Gemini model to eliminate fallback latency and unnecessary fallback warnings.
let cachedWorkingModel: string | null = null;

interface FailedRequest {
  id: string;
  timestamp: string;
  provider: string;
  endpoint: string;
  model?: string;
  error: string;
  rawResponse?: any;
  requestPayload?: any;
}

const failedRequestsLog: FailedRequest[] = [];
dotenv.config();

let cachedGeminiClient: GoogleGenAI | null = null;
let cachedApiKeyUsed: string | null = null;

function getGeminiClient(): GoogleGenAI {
  const currentKey = (process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY || "").trim().replace(/^['"\s]+|['"\s]+$/g, "");
  if (cachedGeminiClient && cachedApiKeyUsed === currentKey) {
    return cachedGeminiClient;
  }
  cachedApiKeyUsed = currentKey;
  cachedGeminiClient = new GoogleGenAI({
    apiKey: currentKey || "dummy",
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });
  return cachedGeminiClient;
}

const geminiAi = new Proxy({} as GoogleGenAI, {
  get(target, prop) {
    const client = getGeminiClient();
    const value = Reflect.get(client, prop);
    if (typeof value === 'function') {
      return value.bind(client);
    }
    return value;
  }
});


import { HfInference } from "@huggingface/inference";

const app = express();

const MASTER_SYSTEM_PROMPT = `
You are the official AI content generator for **EduAI Companion** — a premium South African CAPS-aligned educational platform.

CRITICAL DATE & YEAR RULE: 
- Today's date is 2 June 2026. THE CURRENT YEAR IS 2026, NOT 2024. 
- All generated content, templates, footers, headers, copyright strings, marking grids, lesson plans, notices, worksheets, administrative letters, and documents MUST display the year "2026". 
- Any custom date generated by you must use "2026" (not 2024). Never output "2024" or reference 2024.

CRITICAL VISUAL DESIGN & ILLUSTRATION RULE:
- Under no circumstances should posters, infographics, flow diagram structures, or visual content types be dominated by long, dense paragraphs of text. 
- You must aggressively break up and punctuate all text with detailed, custom, context-relevant inline illustration or diagram placeholders inside brackets, e.g., \`[Illustration: <detailed, highly-specific visual prompt in South African context>]\` or \`[Diagram: <detailed labels and flow-chart prompt>]\`. 
- Each key concept card, section, or bento-grid block inside posters and visual aids must contain its own dedicated illustration placeholder. 
- Keep text inside poster blocks exceptionally brief, punchy, action-oriented, and presented in bullet lists or highlighted capsules with relevant South African emojis (e.g. 🇿🇦, 🦁, 🏔️) rather than raw explanatory prose.

Your outputs must match or exceed the professional quality of our signature EduAI templates: clean, extremely modern, highly vibrant, and interactive layouts. Use full-width background color banners, excellent visual hierarchy, clear instructions, bold answer lines/boxes, scoring areas, educational illustrations/diagrams, and total print-readiness.

VISUAL STYLING DOCTRINE (Follow these for all HTML output):
1. **Full-Width Banners & Section Colors**: Every page must start with a header banner spanning full width with deep, vibrant colors matching the learning domain:
   - Mathematics: Teal & Blue gradients (e.g., from-teal-500 to-blue-600)
   - Natural Sciences / Life Sciences: Orange, Green & Turquoise (e.g., from-emerald-500 to-teal-700)
   - Languages / Literacy: Purple, Pink & Indigo (e.g., from-purple-500 to-indigo-600)
   - Social Sciences / Life Skills: Warm Amber, Red & Gold (e.g., from-amber-500 to-red-600)
2. **Visual Layout and Negative Space**: Always use clean card blocks with a default light theme container (white bg cards on very light gray/zinc ground), rounded corners (rounded-[2.5rem]), thick playful borders (2px to 4px), and spacious padding. Never overlap text or place white text on light backgrounds.
3. **South African Pedagogical Context**: Always use local South African framing (e.g., Rands, local names like Thabo, Zola, Liam, South African provinces, indigenous fynbos, Table Mountain, local wild animals). Always align content explicitly with CAPS guidelines.
4. **Primary / Foundation Phase (Grades R-3) Layouts**:
   - Use ultra-large text sizes (e.g., text-2xl or text-3xl for instruction text), massive line heights, and extensive white space.
   - For Phonics / Word Blending, present letter sounds in structured grid tables with bold colored borders. E.g., cards for Jolly Phonics matching letters with small illustrations (S s | Snake, A a | Ant). Blending exercises must show arrows with buttons: s a t -> sat.
   - For worksheets: Include large, thick-dotted words for "Trace & Copy" activities, or letter blocks. Ensure there are large, beautiful boxes/borders for child drawing or writing.
5. **Intermediate / Senior Phase (Grades 4-7) Layouts**:
   - Use structured, professional, multi-column bento grids and table-based summaries.
   - For Life Skills / Emotions: Use modular grid cards (e.g. 3x2 grid) with soft borders and distinct emoji/icon representations for each feeling, with discussion scenarios.
   - For Assessments / Worksheets: Always include a prominent Header Badge with "NAME: __________  DATE: __________" fields, and a beautiful bold Score Card in the bottom right with a thick yellow/amber border (e.g., "SCORE: _____ / 50 Marks"). 
   - Section headers must use pill-shaped colored borders. True/False questions must display "T / F" inside colorful circles or pill indicators. Radio options must look like tappable capsule options.
6. **Hero Illustrations / Space for Visuals**: Every generated worksheet or poster MUST include an elegantly positioned block representing the primary illustration. If the generator suggests an image, embed a container with a relative graphic or the configured illustration safely in the design.
7. **Motivational elements**: Add small encouraging banners (e.g. "Amazing job! Keep shining! ✨") at the bottom of the tasks.
`;

  const IMAGE_PROMPT_GOLDEN_RULE = `
Ultra-detailed digital illustration, professional educational graphic design, vibrant colors, perfect composition, sharp focus, 300 DPI print quality, award-winning children’s non-fiction book style, no text overlays (text will be added separately), no borders, no frames, no watermarks, no emojis, no cartoonish exaggeration, suitable for South African classroom display, museum-quality detail
`;

  const safeJsonParse = (text) => {
    if (!text) return {};
    let processedText = text;
    processedText = processedText.replace(/<think>[\s\S]*?<\/think>/gi, '');
    processedText = processedText.replace(/<think>[\s\S]*$/gi, '');
    try {
      return JSON.parse(processedText.trim());
    } catch (e) {
      const jsonMatch = processedText.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (jsonMatch && jsonMatch[1]) {
        try {
          return JSON.parse(jsonMatch[1].trim());
        } catch (e2) {}
      }
      return {};
    }
  };

  const PORT = 3000;

  app.use(express.json({ limit: '10mb' }));

  // --- AI Provider Clients ---

  let cachedGroqClient: OpenAI | null = null;
  let cachedGroqKey: string | null = null;

  function getGroqClient(): OpenAI {
    const currentKey = (process.env.GROQ_API_KEY || "").trim().replace(/^['"\s]+|['"\s]+$/g, "");
    if (cachedGroqClient && cachedGroqKey === currentKey) {
      return cachedGroqClient;
    }
    cachedGroqKey = currentKey;
    cachedGroqClient = new OpenAI({
      apiKey: currentKey || "dummy",
      baseURL: "https://api.groq.com/openai/v1",
    });
    return cachedGroqClient;
  }

  const groq = new Proxy({} as OpenAI, {
    get(target, prop) {
      const client = getGroqClient();
      const value = Reflect.get(client, prop);
      if (typeof value === 'function') {
        return value.bind(client);
      }
      return value;
    }
  });

  let cachedAlibabaClient: OpenAI | null = null;
  let cachedAlibabaKey: string | null = null;

  function getAlibabaClient(): OpenAI {
    const currentKey = (process.env.ALIBABA_API_KEY || "").trim().replace(/^['"\s]+|['"\s]+$/g, "");
    if (cachedAlibabaClient && cachedAlibabaKey === currentKey) {
      return cachedAlibabaClient;
    }
    cachedAlibabaKey = currentKey;
    cachedAlibabaClient = new OpenAI({
      apiKey: currentKey || "dummy",
      baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    });
    return cachedAlibabaClient;
  }

  const alibaba = new Proxy({} as OpenAI, {
    get(target, prop) {
      const client = getAlibabaClient();
      const value = Reflect.get(client, prop);
      if (typeof value === 'function') {
        return value.bind(client);
      }
      return value;
    }
  });

  // --- API Routes ---

  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

  // Generic content generation proxy for OpenAI-compatible APIs
  app.post("/api/ai/:provider", async (req, res) => {
    const { provider } = req.params;
    const { messages, model, temperature = 0.7 } = req.body;

    let client: OpenAI | null = null;
    let apiKey = "";

    switch (provider) {
      case "llama-primary":
      case "llama-secondary":
      case "groq-vision":
        client = groq;
        apiKey = process.env.GROQ_API_KEY || "";
        break;
      case "alibaba-qwen":
      case "alibaba-deepseek":
        client = alibaba;
        apiKey = process.env.ALIBABA_API_KEY || "";
        break;
    }

    if (!apiKey || apiKey === "dummy" || apiKey === 'undefined') {
      return res.status(400).json({ error: { message: `Provider ${provider} is not configured. Please add the ${provider === 'alibaba-qwen' ? 'ALIBABA_API_KEY' : 'API_KEY'} in the application settings.` }});
    }

    try {
      const response = await client.chat.completions.create({
        model: model || (
          provider === "llama-primary" ? "llama-3.3-70b-versatile" : 
          provider === "llama-secondary" ? "llama-3.1-8b-instant" : 
          provider === "alibaba-qwen" ? "qwen-plus" :
          provider === "alibaba-deepseek" ? "deepseek-v3" :
          provider === "groq-vision" ? "llama-3.2-11b-vision-instant" :
          ""
        ),
        messages,
        temperature,
        max_completion_tokens: 8192,
      });
      res.json(response);
    } catch (error: any) {
      const status = error.status || 500;
      if (status !== 500) {
        console.warn(`${provider} API returned status ${status}: ${error.message || 'Error'}`);
      } else {
        console.error(`${provider} error:`, error.message || error);
      }
      res.status(status).json({ 
        error: error.message,
        provider,
        code: error.code,
        type: error.type 
      });
    }
  });

  app.post("/api/ocr", async (req, res) => {
    const { image, language = "eng" } = req.body;
    const apiKey = process.env.OCR_SPACE_API_KEY;

    if (!apiKey) {
      return res.status(400).json({ error: "OCR.space API key missing." });
    }

    try {
      const formData = new URLSearchParams();
      formData.append("base64Image", image);
      formData.append("language", language);
      formData.append("apikey", apiKey);

      const response = await axios.post("https://api.ocr.space/parse/image", formData, {
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
      });
      res.json(response.data);
    } catch (error: any) {
      console.error("OCR error:", error);
      res.status(500).json({ error: error.message });
    }
  });

  app.post("/api/tts/google", async (req, res) => {
    const { text, lang } = req.body;
    try {
      const googleTTS = await import("google-tts-api");
      const urls = googleTTS.getAllAudioUrls(text, { lang, slow: false, splitPunct: ',.?!' });
      // Map URLs to our server-side proxy to completely bypass iframe CORS and referrer restriction policies
      const proxiedUrls = urls.map(u => `/api/tts/proxy?url=${encodeURIComponent(u.url)}`);
      res.json({ urls: proxiedUrls });
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  app.get("/api/tts/proxy", async (req, res) => {
    const { url } = req.query;
    if (!url || typeof url !== "string") {
      return res.status(400).send("Missing URL parameter");
    }
    try {
      const response = await axios({
        method: "get",
        url: url,
        responseType: "stream",
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          "Referer": "https://translate.google.com/"
        }
      });
      const contentType = response.headers["content-type"];
      res.setHeader("Content-Type", typeof contentType === "string" ? contentType : "audio/mpeg");
      response.data.pipe(res);
    } catch (error: any) {
      console.warn("Audio proxy error:", error.message);
      res.status(500).send("Audio proxy failed");
    }
  });

  app.post("/api/tts/hf", async (req, res) => {
    const { text, model } = req.body;
    const apiKey = process.env.HUGGINGFACE_API_KEY;
    try {
      if (!fetch) {
         // Some node versions might not have global fetch if very old, but since we use node 22 it's fine.
      }
      const fetchResponse = await fetch(`https://api-inference.huggingface.co/models/${model}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": apiKey ? `Bearer ${apiKey}` : ""
        },
        body: JSON.stringify({ inputs: text }) // Note: HF TTS expects "inputs"
      });
      if (!fetchResponse.ok) {
        throw new Error(`HF returned ${fetchResponse.status}`);
      }
      const buffer = await fetchResponse.arrayBuffer();
      const base64 = Buffer.from(buffer).toString("base64");
      res.json({ audio: `data:audio/flac;base64,${base64}` });
    } catch (e: any) {
      console.warn("HF TTS Error:", e);
      res.status(500).json({ error: e.message });
    }
  });

  app.post("/api/video/generate", async (req, res) => {
    const { prompt, model } = req.body;
    const apiKey = process.env.REPLICATE_API_TOKEN;
    if (!apiKey) {
      return res.status(400).json({ error: "REPLICATE_API_TOKEN is required. Please set it in Settings -> Secrets." });
    }
    try {
      const Replicate = (await import("replicate")).default;
      const replicate = new Replicate({ auth: apiKey });
      
      const modelIdentifier = model === "replicate-minimax" ? "minimax/video-01" : "luma/ray";
      
      const prediction = await replicate.predictions.create({
        model: modelIdentifier as any,
        input: { prompt: prompt }
      });
      
      res.json({ id: prediction.id, status: prediction.status });
    } catch (e: any) {
      console.warn("Replicate Video Error:", e);
      if (e.message?.includes("402 Payment Required") || e.response?.status === 402 || e.message?.includes("Insufficient credit")) {
        console.warn("Falling back to sample video due to insufficient Replicate credits.");
        return res.json({ id: "mock-video-id", status: "started" });
      }
      res.status(500).json({ error: e.message });
    }
  });

  app.get("/api/video/status/:id", async (req, res) => {
    if (req.params.id === "mock-video-id") {
      // Simulate processing delay, then return a sample nature/educational video
      return res.json({ 
        status: "succeeded", 
        url: "https://www.w3schools.com/html/mov_bbb.mp4" 
      });
    }

    const apiKey = process.env.REPLICATE_API_TOKEN;
    if (!apiKey) {
      return res.status(400).json({ error: "REPLICATE_API_TOKEN is required." });
    }
    try {
      const Replicate = (await import("replicate")).default;
      const replicate = new Replicate({ auth: apiKey });
      
      const prediction = await replicate.predictions.get(req.params.id);
      
      if (prediction.status === "succeeded") {
         const url = Array.isArray(prediction.output) ? prediction.output[0] : (prediction.output as any)?.url || prediction.output;
         res.json({ status: prediction.status, url });
      } else if (prediction.status === "failed" || prediction.status === "canceled") {
         res.status(500).json({ error: "Video generation failed or was canceled." });
      } else {
         res.json({ status: prediction.status });
      }
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  app.post("/api/images/generate", async (req, res) => {
    const { prompt, provider } = req.body;
    
    if (provider === "gemini-imagen") {
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey || apiKey === "dummy" || apiKey === "undefined") {
        return res.status(400).json({ error: "GEMINI_API_KEY missing" });
      }

      // Try 1: gemini-2.5-flash-image (The designated Flash Image model)
      try {
        console.log("Attempting image generation with 'gemini-2.5-flash-image'...");
        const response = await geminiAi.models.generateContent({
          model: 'gemini-2.5-flash-image',
          contents: {
            parts: [
              { text: prompt }
            ]
          },
          config: {
            imageConfig: {
              aspectRatio: "1:1"
            }
          }
        });

        let foundBase64 = null;
        if (response.candidates && response.candidates[0]?.content?.parts) {
          for (const part of response.candidates[0].content.parts) {
            if (part.inlineData && part.inlineData.data) {
              foundBase64 = part.inlineData.data;
              break;
            }
          }
        }

        if (foundBase64) {
          console.log("Image successfully generated with 'gemini-2.5-flash-image'!");
          return res.json({ url: `data:image/jpeg;base64,${foundBase64}` });
        }
      } catch (err1: any) {
        console.warn("gemini-2.5-flash-image failed:", err1.message);
      }

      // Try 2: imagen-3.0-generate-002
      try {
        console.log("Attempting image generation with 'imagen-3.0-generate-002'...");
        const response = await geminiAi.models.generateImages({
          model: 'imagen-3.0-generate-002',
          prompt: prompt,
          config: {
            numberOfImages: 1,
            outputMimeType: 'image/jpeg',
            aspectRatio: '1:1'
          }
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
          const image = response.generatedImages[0];
          const base64 = image.image.imageBytes;
          if (base64) {
            console.log("Image successfully generated with 'imagen-3.0-generate-002'!");
            return res.json({ url: `data:image/jpeg;base64,${base64}` });
          }
        }
      } catch (err2: any) {
        console.warn("imagen-3.0-generate-002 failed:", err2.message);
      }

      // Fallback Strategy: Pollinations (FLUX) so image generation NEVER fails!
      console.warn("All Gemini image generation attempts failed. Falling back to Pollinations in the backend.");
      const enhancedPrompt = `${prompt}, professional children's educational book illustration style, pencil sketch and clean watercolor painting blend, rich vibrant colors, high detail, no text overlays, South African classroom display, 300 DPI`;
      const fallbackUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(enhancedPrompt)}?width=1024&height=1024&nologo=true&model=flux&seed=${Math.floor(Math.random() * 100000)}`;
      return res.json({ url: fallbackUrl, isFallback: true });
    }

    if (provider === "alibaba-qwen-image") {
      const apiKey = process.env.ALIBABA_API_KEY;
      if (!apiKey || apiKey === "dummy" || apiKey === "undefined") {
        return res.status(400).json({ error: "ALIBABA_API_KEY missing" });
      }

      try {
        const response = await alibaba.images.generate({
          model: 'qwen-image-2.0-pro-2026-04-22',
          prompt: prompt,
          n: 1,
          size: "1024x1024",
        });
        return res.json({ url: response.data[0].url });
      } catch (error: any) {
        console.warn("Alibaba image warn:", error.message);
        return res.status(500).json({ error: error.message || "Failed to generate image via Alibaba" });
      }
    }

    if (provider === "huggingface") {
      const apiKey = process.env.HUGGINGFACE_API_KEY;
      if (!apiKey) return res.status(400).json({ error: "HUGGINGFACE_API_KEY missing" });
      
      try {
        const hf = new HfInference(apiKey);
        const imageBlob = await hf.textToImage({
          model: 'black-forest-labs/FLUX.1-schnell',
          inputs: prompt,
          parameters: { negative_prompt: 'blurry' }
        });
        const arrayBuffer = await (imageBlob as any).arrayBuffer();
        const base64 = Buffer.from(arrayBuffer).toString('base64');
        return res.json({ url: `data:image/jpeg;base64,${base64}` });
      } catch (error: any) {
        console.warn("HuggingFace image warn:", error.message);
        return res.status(500).json({ error: error.message || "Failed to generate image via HuggingFace" });
      }
    }
    
    return res.status(400).json({ error: "Unsupported provider" });
  });

  // --- Individual Learner Development Plan (ILDP) Route ---

  function generateLocalFallbackILDP(studentName: string, grade: string, subjects: any[]) {
    const lowSubjects = subjects.filter((s: any) => s.mark < 70);
    const highSubjects = subjects.filter((s: any) => s.mark >= 75);

    const strengths = highSubjects.map((s: any) => `Excellent mastery of foundational concepts and high accuracy in Grade ${grade} ${s.name} (${s.mark}%).`)
      .slice(0, 3);
    if (strengths.length === 0) {
      strengths.push("Shows great curiosity, consistent learning attitude, and active participation in class discussions.");
    }

    const weaknesses = lowSubjects.map((s: any) => `Currently finding some topics challenging in ${s.name} (${s.mark}%), requiring targeted revision and problem-solving exercises.`)
      .slice(0, 3);
    if (weaknesses.length === 0) {
      weaknesses.push(`Doing well overall; could benefit from challenging extension tasks to nurture advanced thinking skills.`);
    }

    const recommendations = [
      `Engage with the personalized exercises in Content Creator Studio, focusing specifically on weak areas.`,
      `Hold 1-on-1 focus chats with the EduAI Tutor to review problem-solving strategies.`,
      `Form small group study sessions with peers using Study Groups in Class Management.`
    ];

    const actionPlan = [
      { task: "Revise high-priority syllabus sections and build summaries", milestone: "Within 2 weeks", status: "In Progress" },
      { task: "Consult AI Tutor for interactive quizzes on weaker chapters", milestone: "Within 3 weeks", status: "Pending" },
      { task: "Submit a practice portfolio task for teacher review", milestone: "Before major exam", status: "Pending" }
    ];

    return { strengths, weaknesses, recommendations, actionPlan };
  }

  app.post("/api/reports/ildp", async (req, res) => {
    const { studentName, grade, subjects } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === "dummy" || apiKey === "undefined") {
      return res.json(generateLocalFallbackILDP(studentName, grade, subjects));
    }
    try {
      const prompt = `
        You are a supportive, insightful educational counselor and South African school advisor.
        Generate a constructive and professional Individual Learner Development Plan (ILDP) for a school student with this profile:
        Student Name: ${studentName}
        Grade: ${grade}
        Performance Stats: ${JSON.stringify(subjects)}

        The response must be a valid raw JSON object matching this exact TypeScript interface:
        {
          "strengths": string[];
          "weaknesses": string[];
          "recommendations": string[];
          "actionPlan": { task: string; milestone: string; status: 'Pending' | 'In Progress' | 'Completed' }[];
        }

        Make sure your recommendations are encouraging and specifically reference their low/high subjects. Align suggestions with South African CAPS-standards (e.g. SBA, formative tests). Do not format the response with markdown formatting (no backticks, no text like 'json' or explanations), only output a parseable JSON block.
      `;
      const response = await geminiAi.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          temperature: 0.7,
        }
      });
      const text = response.text || "";
      const trimmed = text.trim();
      const cleanJson = trimmed.startsWith("```") ? trimmed.replace(/^```json\s*/i, "").replace(/```$/, "").trim() : trimmed;
      const data = JSON.parse(cleanJson);
      res.json(data);
    } catch (err: any) {
      console.warn("Gemini ILDP Generation failed, using local builder:", err.message);
      res.json(generateLocalFallbackILDP(studentName, grade, subjects));
    }
  });

  
  app.post("/api/gemini/action", async (req, res) => {
    const { action, input } = req.body || {};
    const apiKey = (process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY || "").trim().replace(/^['"\s]+|['"\s]+$/g, "");
    if (!apiKey || apiKey === "" || apiKey === "dummy" || apiKey === "undefined") {
      return res.status(400).json({ error: "GEMINI_API_KEY is not configured in settings." });
    }

    try {
      const model = "gemini-3.5-flash";

      const generateContentWithFallback = async (options: { model: string, contents: any, config?: any }) => {
        const modelsToTry = cachedWorkingModel 
          ? [cachedWorkingModel, "gemini-3.5-flash", "gemini-3.1-flash-lite", "gemini-flash-latest"]
          : ["gemini-3.5-flash", "gemini-3.1-flash-lite", "gemini-flash-latest"];
        
        let lastError: any = null;
        for (const candidate of modelsToTry) {
          try {
            const actualOptions = { ...options, model: candidate };
            const result = await geminiAi.models.generateContent(actualOptions);
            if (result) {
              cachedWorkingModel = candidate; // Cache successfully validated model
              return result;
            }
          } catch (err: any) {
            lastError = err;
            console.info(`Gemini candidate model '${candidate}' is currently unavailable. trying alternative...`);
          }
        }
        throw lastError || new Error("All candidate Gemini models were unavailable.");
      };

      switch (action) {
        case "generate-educational": {
          const { type, details } = input;
          const systemInstruction = `${MASTER_SYSTEM_PROMPT}\n\nYour task is to generate high-quality educational materials: ${type}.\nThe content must be strictly CAPS aligned, professionally formatted in HTML with Tailwind CSS, and ready for classroom use. DO NOT USE MARKDOWN. NEVER INJECT <script src="https://cdn.tailwindcss.com"></script>. The app already has Tailwind.`;
          const response = await generateContentWithFallback({
            model,
            contents: `Generate a ${type} based on the following details: ${details}. Format as valid HTML with Tailwind CSS classes. Follow the EduAI design style (colored banners, pill-shaped blocks, distinct sections, vibrant design). Do NOT add Tailwind CDN scripts.`,
            config: {
              systemInstruction,
              temperature: 0.7,
            },
          });
          return res.json({ text: response.text });
        }

        case "generate-caps": {
          const isLessonPlan = input.contentType === 'Lesson Plan';
          const isStudyGuide = input.contentType === 'Study Guide / Learning Notes';
          const isWorksheet = input.contentType === 'Worksheet';

          let contentTypeEng: 'lesson-plan' | 'worksheet' | 'study-guide' = 'worksheet';
          if (isLessonPlan) contentTypeEng = 'lesson-plan';
          else if (isStudyGuide) contentTypeEng = 'study-guide';
          else if (isWorksheet) contentTypeEng = 'worksheet';

          const { system, user } = EduAIPromptEngine.assemblePrompt({
            contentType: contentTypeEng,
            grade: input.grade || "4",
            subject: input.subject || "Mathematics",
            topic: input.topic || "Addition",
            language: input.language || 'English',
            learnerProfile: input.learnerProfile || 'General Class',
            additionalInstructions: input.additionalInstructions || '',
            term: input.term || '1',
            week: input.week ? parseInt(input.week) : undefined,
            duration: input.duration || '2 hours',
            capsReference: input.capsReference || '',
            includeWorksheet: !!input.includeWorksheet
          });

          const response = await generateContentWithFallback({
            model,
            contents: user,
            config: {
              systemInstruction: system,
              responseMimeType: "application/json",
              responseSchema: {
                type: Type.OBJECT,
                properties: {
                  content: { type: Type.STRING },
                  memo: { type: Type.STRING },
                  rubric: { type: Type.STRING },
                  assessmentCriteria: { type: Type.STRING },
                  successIndicators: { type: Type.ARRAY, items: { type: Type.STRING } },
                  imagePrompt: { type: Type.STRING }
                },
                required: ["content", "imagePrompt"]
              }
            }
          });
          return res.json(safeJsonParse(response.text));
        }

        case "generate-visual": {
          const systemInstruction = `${MASTER_SYSTEM_PROMPT}\n\nThe 'content' field in your JSON response MUST be stunningly designed HTML with Tailwind CSS. DO NOT use generic Markdown.`;
          const isPoster = input.visualType?.toLowerCase().includes('poster');
          const isInfographic = input.visualType?.toLowerCase().includes('infographic') || input.visualType?.toLowerCase().includes('mind map');
          const isDiagram = input.visualType?.toLowerCase().includes('diagram');
          const isFlashcard = input.visualType?.toLowerCase().includes('flashcard') || input.visualType?.toLowerCase().includes('learning card');

          let visualPrompt = "";
          if (isPoster) {
            visualPrompt = `
              Create a stunning, print-ready, highly visual classroom display poster for South African Grade ${input.grade} ${input.subject} learners on the CAPS topic: "${input.topic}".
              
              CRITICAL RULE: DO NOT write any worksheets, exercises, questions, answers, fill-in-the-blanks, or assessment tasks. This is strictly a visual aid for display and illustrative purposes during lessons.
              
              DESIGN RESTRUCTURING - IMPLEMENT ONE OF THESE REVERSE-ENGINEERED SHOW-STOPPING CLASSROOM STYLES:
              Style Option A) CHALKBOARD INSPIRATIONAL/MOTIVATIONAL DISPLAY style:
              - Background: A deep charcoal or slate black chalkboard texture with subtle hand-drawn chalk dust and grid lines.
              - Header: A bold, multi-colored hand-written 3D chalk styled title (using text shadows, hand-copied lettering feel with playful vibrant colors like chalk yellow, sky blue outline, hot pink).
              - Central Visual: A stylized, handcrafted center-piece drawing illustrating the theme (e.g. a chalk-drawn tree of knowledge, interactive brain gears, or a scientific symbol).
              - Surrounding Layout: Draw 5-7 beautifully color-coded thought bubbles, clouds, or capsule containers with dashed or scribbled colorful chalk borders radiating outward.
              - Content: Inside each bubble, include highly motivational, brief, key facts or growth quotes of 4-8 words (e.g., "Mistakes mean I am learning!", "Math is my superpower!", "Try, improve, succeed!").
              - Accents: Fill empty corners with small fun school-themed chalkboard doodles (pencils, rulers, clocks, books, stars, small lightbulbs, musical notes).
              
              Style Option B) NATURE / WILDLIFE / DISCOVERY LANDSCAPE style:
              - Background & Frame: An elegant, solid, thick primary accent border (like standard National Geographic warm mustard-yellow or terracotta).
              - Title: Large, display-oriented title in high-contrast crisp sans-serif with subtle text shadows.
              - Central Artwork: A breathtaking scenic illustration of a South African landscape (e.g., golden-hour savanna, Drakensberg peaks, Table Mountain, or green fynbos reserve). Include kids in school uniforms holding notebooks and exploring, seeing local fauna and flora (Lions, Springboks, Proteas, Aloe) in their habitats.
              - Information Layout: Position 3-4 beautifully semi-transparent white-boarded informational callout boxes overlapping the landscape. Use thin primary-colored borders, tiny playful emojis, and highly legibly structured bold summaries of 1-2 key facts.
            `;
          } else if (isFlashcard) {
            visualPrompt = `
              Design a set of professional, double-sided visual educational flashcards for South African Grade ${input.grade} ${input.subject} on "${input.topic}".
              
              DESIGN REQUIREMENTS:
              - Grid Layout: Show multiple cards in a beautifully aligned grid (2 or 3 per row).
              - Each card must have:
                - Front side: Large bold title, a delightful custom icon or emoji, and a quick catchy hint or question.
                - Back side: Clear conceptual explanation, a South African contextual/CAPS example, and a small fun "Did you know?" fact box.
              - Aesthetics: Rounded-3xl corners (at least 24px), thick colored outlines (3px solid border that changes color per card), and micro shadow depth.
              - Use rich, vibrant background gradients or clean high-contrast card themes. Text must be large and instantly legible.
            `;
          } else if (isInfographic) {
            visualPrompt = `
              Design an incredibly structured, premium academic infographic/mind-map comparison chart on "${input.topic}" for Grade ${input.grade} ${input.subject}.
              
              CRITICAL RULE: DO NOT generate worksheet questions, exercises, or homework. This is a visual display cheat-sheet.
              
              AESTHETICS - CHOOSE ONE OF THESE COMPANION INFOGRAPHIC BLUEPRINTS:
              Structure A) HIGH-CONTRAST DUAL-COLUMN CONCEPT OVERVIEW (e.g., Growth vs Fixed Mindset comparison):
              - Main Header: A playful curved ribbon or banner spanning the top with a gorgeous title in bold, professional display typography.
              - Interactive Mascots: Place two cute characters at the top of their respective columns (e.g., styled as adorable mini cartoon brains wearing glasses—one frowning, one smiling).
              - Matrix Grid: A neat comparison grid. The left column (defeatist/negative views) is styled with a soft pastel red/pink background and card borders. The right column (positive reframes) is styled with a gorgeous soft mint green background and emerald card borders.
              - Connectivity: Connect corresponding row concepts with subtle dotted lines and bright arrow selectors to guide the eye. Use short 5-word phrases.
              
              Structure B) ASYMMETRICAL BENTO GRID:
              - Center-piece: A central bold circular capsule containing the primary topic, using thick shadows and bright rings.
              - Bento Grid: Surround the center with 4-5 neat rectangular cards of unequal sizes (bento grid) styled beautifully.
              - Cards: Each card has its own clean theme color (Fuchsia, Sky Blue, Forest Green, Amber), a large modern outline icon/emoji, and uses a bulleted structure for CAPS key theories.
            `;
          } else if (isDiagram) {
            visualPrompt = `
              Create a crystal-clear, beautifully illustrated scientific diagram of "${input.topic}" specifically adapted for South African Grade ${input.grade} ${input.subject} learners.
              
              CRITICAL: This is a teaching demonstration visual aid. DO NOT write worksheet questions, exercises, or tests.
              
              DIAGRAM ARCHITECTURE:
              - Flow & Layout: Set against a highly realistic, vibrant South African biome / context (e.g. water cycles over the Drakensberg mountains, food webs of the Kruger savanna, or plant cell structure featuring indigenous fynbos/Proteas).
              - Connections: Draw bright, stylized, high-contrast flowing directional arrows pointing out movement, cycle flow, or ecosystem energy transfers.
              - Diagram Labels: Place 5-6 crisp, floating educational pointing cards (labels like 'KAROO', 'ALOE ROOT', 'ENERGY FLOW') connected to their targets. Styling: stark white background, rounded border, sharp shadows, and bold scientific monospace/sans-serif fonts.
              - Key/Legend: Include a small, highly tidy legend card at the bottom right with colorful indicator boxes explaining key parts.
              - Ensure the diagram looks detailed, professional, and is highly instructive for display.
            `;
          } else {
            visualPrompt = `Create a highly visual display, not a worksheet, for Grade ${input.grade} ${input.subject} on topic ${input.topic}. Ensure it is styled beautifully.`;
          }

          const prompt = `
            ${visualPrompt}
            Language: ${input.language}
            Style: ${input.style}
            Color: ${input.colorScheme}
            Content Details: ${input.specificContent}
            Quantity: ${input.quantity}
            Additional Info: ${IMAGE_PROMPT_GOLDEN_RULE}
          `;

          const response = await generateContentWithFallback({
            model,
            contents: prompt,
            config: { 
              systemInstruction, 
              responseMimeType: "application/json",
              responseSchema: {
                type: Type.OBJECT,
                properties: {
                  content: { type: Type.STRING },
                  description: { type: Type.STRING },
                  printInstructions: { type: Type.STRING },
                  imagePrompt: { type: Type.STRING }
                },
                required: ["content", "description", "imagePrompt"]
              }
            }
          });
          return res.json(safeJsonParse(response.text));
        }

        case "generate-admin": {
          const systemInstruction = `${MASTER_SYSTEM_PROMPT}\n\nGenerate a formal ${input.documentType} for ${input.schoolName}.
          The tone should be ${input.tone}.
          IMPORTANT: The 'content' field MUST be formatted as visually pleasing HTML string styled with Tailwind CSS classes. DO NOT use generic Markdown.`;
          const prompt = `
            Type: ${input.documentType}
            Purpose: ${input.purpose}
            Key Points: ${input.keyPoints}
            Include Reply Slip: ${input.includeReplySlip}
            Language: ${input.language}
          `;
          const response = await generateContentWithFallback({
            model,
            contents: prompt,
            config: { 
              systemInstruction, 
              responseMimeType: "application/json",
              responseSchema: {
                type: Type.OBJECT,
                properties: {
                  content: { type: Type.STRING },
                  notes: { type: Type.STRING },
                  documentType: { type: Type.STRING },
                  imagePrompt: { type: Type.STRING }
                },
                required: ["content", "documentType"]
              }
            }
          });
          return res.json(safeJsonParse(response.text));
        }

        case "ocr-scan": {
          const { imageData, language } = input;
          const prompt = `Extract all text from the attached image accurately, assuming the text is in ${language}.
          Format it cleanly. Make no other comments.`;
          const response = await generateContentWithFallback({
            model,
            contents: [
              { role: 'user', parts: [
                { text: prompt },
                { inlineData: { mimeType: "image/jpeg", data: imageData.split(',')[1] } }
              ]}
            ]
          });
          return res.json({ extractedText: response.text });
        }

        case "ocr-grade": {
          const { imageData, rubric, language } = input;
          const prompt = `You are an AI Grader. Analyze the attached image of a student's assessment in ${language}.
          Reference this rubric: ${rubric}.
          1. Extract the text from the image (OCR).
          2. Grade each question according to the rubric.
          3. Provide constructive feedback for the student.
          4. Summarize the total score.`;
          const response = await generateContentWithFallback({
            model,
            contents: [
              { role: 'user', parts: [
                { text: prompt },
                { inlineData: { mimeType: "image/jpeg", data: imageData.split(',')[1] } }
              ]}
            ],
            config: {
              responseMimeType: "application/json",
              responseSchema: {
                type: Type.OBJECT,
                properties: {
                  extractedText: { type: Type.STRING },
                  marksPerQuestion: { type: Type.ARRAY, items: { type: Type.STRING } },
                  feedback: { type: Type.STRING },
                  totalScore: { type: Type.STRING }
                },
                required: ["extractedText", "marksPerQuestion", "feedback", "totalScore"]
              }
            }
          });
          return res.json(safeJsonParse(response.text));
        }

        case "chat": {
          const { messages } = input;
          const response = await generateContentWithFallback({
            model,
            contents: messages,
            config: {
              systemInstruction: "You are a friendly and encouraging South African school tutor for EduAI Companion. You help students understand complex CAPS curriculum concepts in simple terms. Use local South African examples (e.g. using Rands, referring to provinces) and be patient. Keep explanations concise.",
            }
          });
          return res.json({ text: response.text });
        }

        default:
          return res.status(400).json({ error: "Unsupported action" });
      }
    } catch (error: any) {
      const errMsg = error.message || error.toString();
      let status = 500;
      const rawStatus = error.status || error.response?.status;
      if (typeof rawStatus === 'number' && Number.isInteger(rawStatus) && rawStatus >= 100 && rawStatus < 600) {
        status = rawStatus;
      }
      if (errMsg.toLowerCase().includes('permissions') || errMsg.toLowerCase().includes('api key') || errMsg.toLowerCase().includes('auth') || errMsg.toLowerCase().includes('dummy')) {
         status = 401;
      }

      // Capture failure for Admin Debug Console
      failedRequestsLog.unshift({
        id: `err_${Date.now()}_${Math.random().toString(36).substr(2, 5)}`,
        timestamp: new Date().toISOString(),
        provider: 'gemini',
        endpoint: `/api/gemini/action`,
        model: 'gemini-3.5-flash',
        error: errMsg,
        rawResponse: error.response?.data || error.stack || error.message || String(error),
        requestPayload: {
          action,
          input: input ? { ...input, imageData: input.imageData ? '[Muted Image Data]' : undefined } : undefined
        }
      });
      if (failedRequestsLog.length > 50) {
        failedRequestsLog.pop();
      }

      console.error(`Gemini server error for action '${action}':`, errMsg);
      return res.status(status).json({ error: errMsg || "Failed to execute server-side action." });
    }
  });

  // --- Vite Middleware ---

  async function initializeAndListen() {
    if (process.env.VERCEL) {
      return;
    }

    if (process.env.NODE_ENV !== "production") {
      const { createServer: createViteServer } = await import("vite");
      const vite = await createViteServer({
        server: { middlewareMode: true },
        appType: "spa",
      });
      app.use(vite.middlewares);
    } else {
      const distPath = path.join(process.cwd(), "dist");
      app.use(express.static(distPath));
      app.get("*", (req, res) => {
        res.sendFile(path.join(distPath, "index.html"));
      });
    }

    if (!process.env.VERCEL) {
      const PORT = 3000;
      app.listen(PORT, "0.0.0.0", () => {
        console.log(`Server running on http://localhost:${PORT}`);
      });
    }
  }

  initializeAndListen();

  export default app;
