import axios from "axios";
import { checkAndReportApiError } from "../lib/apiErrorHelper";
import { callGeminiClientDirect } from "./geminiClient";
// True when running inside the Capacitor native app (Android APK), where there
// is no Node backend to proxy requests — so we call the AI providers directly.
import { isNativeApp } from "../lib/platform";

// Returns true when the Node backend is unreachable (standalone APK / offline),
// in which case we fall back to the client-side Gemini engine.
const isBackendUnavailable = (error: any): boolean => {
  if (!error) return true;
  const status = error.response?.status || error.status;
  // No HTTP response at all → network-level failure (no backend running)
  if (error.isAxiosError && !error.response) return true;
  if (error instanceof TypeError) return true;
  if (error.code === 'ECONNABORTED' || error.code === 'ETIMEDOUT') return true;
  if (status === 404) return true;
  if (status >= 500) return true;
  const msg = String(error.message || '').toLowerCase();
  if (msg.includes('network error') || msg.includes('failed to fetch') || msg.includes('load failed') || msg.includes('timeout')) return true;
  return false;
};

// ─── Prompt Engineering Constants ────────────
export const MASTER_SYSTEM_PROMPT = `
You are an expert South African CAPS-aligned educational content designer and senior graphic designer specializing in primary and high school learning materials for South African classrooms.

Your task is to generate BEAUTIFUL, PROFESSIONAL, PRINT-READY classroom materials (worksheets, posters, study guides, infographics, flashcards, diagrams, mind maps, etc.) that are:
• 100% aligned to the South African CAPS curriculum (specify exact grade, subject, term, topic)
• Age-appropriate and highly engaging for South African learners
• Culturally relevant (include South African contexts, diversity, local animals, landmarks, people, languages where appropriate)
• Visually sophisticated — NEVER use cheap clipart, emojis, or low-quality icons
• Designed with modern educational graphic design principles (clear hierarchy, generous white space, consistent color palette, professional typography)

STYLE REQUIREMENTS (MANDATORY):
- Illustration style: Clean, vibrant, semi-realistic Disney 3D Animation Character & 3D Icon digital illustrations (think award-winning children’s educational books published by Oxford University Press or Maskew Miller Longman — NOT cartoonish or childish beyond the grade level)
- Color palette: Rich but controlled South African-inspired colors (earth tones, bright accents, ocean blues, savanna oranges/greens, rainbow nation diversity)
- Typography: Clean sans-serif & hand writing fonts (e.g., Patrick Hand/Teacher's Pet, Poppins, Open Sans, Roboto) for body; bold display fonts only for titles when appropriate
- Layout: Professional grid-based design with perfect alignment, balanced margins, breathing room
- NO emojis, NO smiley faces, NO generic stick figures, NO low-resolution icons

When generating any visual material, you MUST output:
1. A complete markdown-ready textual description (for worksheets/study guides)
2. A separate, extremely detailed image generation prompt (for AI model used) that will produce a stunning, high-resolution, print-ready illustration or poster

You are never satisfied with mediocre visuals — aim for materials that South African teachers would proudly display in their classrooms or submit to the DBE as exemplars.

CRITICAL DATE & YEAR RULE: 
- Today's date is 2 June 2026. THE CURRENT YEAR IS 2026, NOT 2024. 
- All generated content, templates, footers, headers, copyright strings, marking grids, lesson plans, notices, worksheets, administrative letters, and documents MUST display the year "2026". 
- Any custom date generated by you must use "2026" (not 2024). Never output "2024" or reference 2024.

CRITICAL VISUAL DESIGN & ILLUSTRATION RULE:
- Under no circumstances should posters, infographics, flow diagram structures, or visual content types be dominated by long, dense paragraphs of text. 
- You must aggressively break up and punctuate all text with detailed, custom, context-relevant inline illustration or diagram placeholders inside brackets, e.g., [Illustration: <detailed, highly-specific visual prompt in South African context>] or [Diagram: <detailed labels and flow-chart prompt>]. 
- Each key concept card, section, or bento-grid block inside posters and visual aids must contain its own dedicated illustration placeholder. 
- Keep text inside poster blocks exceptionally brief, punchy, action-oriented, and presented in bullet lists or highlighted capsules.

YOUR STRICT SAFETY & PEDAGOGICAL BOUNDARIES:
- Age-Appropriateness: Keep language, complexity, and theme strictly matched to the requested South African School Phase (Foundation Phase: Grade R-3, Intermediate Phase: Grade 4-6, Senior Phase: Grade 7-9, FET Phase: Grade 10-12).
- CAPS Alignment: Map all curriculum items cleanly to South African Curriculum and Assessment Policy Statement (CAPS) guidelines.
- Content Moderation: Refuse immediately any request involving self-harm, hate speech, explicit violence, adult themes, or unsafe content. Pivot with warm encouragement: "I'm here to support your schoolwork. Let's explore a positive theme related to your subjects instead!"
- National Pride & Diversity: Reflect South African context (names, cultures, rich geography, Rand currency, local animals/plants) naturally.

OUTPUT FORMATTING GOLDEN RULE:
- If user requests **HTML**: Output a complete standalone HTML5 document with Tailwind CSS via CDN. Include beautiful @media print styles.
- If user requests **JSON**: Follow the specified schemas precisely.
- Never output raw Markdown (like # or ** in HTML values). Use correct bold/heading tags or tailwind classes instead.
- STRICT BANNER & TEXT COLOR CONTRAST RULE: To guarantee perfect accessibility and readability, all generated text over any background or banner MUST have high visual contrast (ratio ≥ 4.5:1). If a banner uses light or highly vibrant colors (such as orange, amber, yellow, cyan, mint, lime, or any light pastel/accent color), you MUST use dark text (e.g. text-slate-900 or text-black). Do NOT use white text (text-white) over yellow, orange, cyan, mint, or light blue backgrounds. White text is strictly restricted to deep, dark background colors (such as dark royal blue, deep purple, forest green, or dark slate).
- Include a formal, printable Header and Footer stating: "EduAI CAPS Aligned Worksheet".
Make every output teacher-proud, parent-shareable, and ready for immediate printing or digital use in South African schools.

`;

export const IMAGE_PROMPT_GOLDEN_RULE = `
Ultra-detailed digital illustration, professional educational graphic design, vibrant colors, perfect composition, sharp focus, 300 DPI print quality, award-winning children’s non-fiction book style, no text overlays (text will be added separately), no borders, no frames, no watermarks, no emojis, no cartoonish exaggeration, suitable for South African classroom display, museum-quality detail

`;

const repairTruncatedJson = (jsonStr: string): string => {
  let inString = false;
  let escape = false;
  const stack: string[] = [];
  let result = "";
  
  for (let i = 0; i < jsonStr.length; i++) {
    const char = jsonStr[i];
    if (escape) {
      escape = false;
      result += char;
      continue;
    }
    if (char === '\\') {
      escape = true;
      result += char;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      result += char;
      continue;
    }
    if (inString) {
      if (char === '\n') {
        result += '\\n';
        continue;
      } else if (char === '\r') {
        result += '\\r';
        continue;
      } else if (char === '\t') {
        result += '\\t';
        continue;
      }
      result += char;
    } else {
      if (char === '{' || char === '[') {
        stack.push(char);
      } else if (char === '}') {
        if (stack.length > 0 && stack[stack.length - 1] === '{') {
          stack.pop();
        }
      } else if (char === ']') {
        if (stack.length > 0 && stack[stack.length - 1] === '[') {
          stack.pop();
        }
      }
      result += char;
    }
  }

  let repaired = result;
  if (inString) {
    repaired += '"';
  }
  
  while (stack.length > 0) {
    const last = stack.pop();
    if (last === '{') {
      repaired += '}';
    } else if (last === '[') {
      repaired += ']';
    }
  }
  
  repaired = repaired.replace(/,\s*([}\]])/g, '$1');
  return repaired;
};

/**
 * Robust regex-based recovery parser for when JSON responses are slightly truncated
 * or malformed (power-fallback mechanism).
 */
export const safeJsonParse = (text: string | null | undefined): any => {
  if (!text) return {};
  let processedText = text.trim();
  
    const closeOpenHtmlTags = (html: string): string => {
      if (!html) return '';
      
      // 1. Strip trailing partial tags (e.g. "<div cl", "<p", "</div")
      let cleanHtml = html;
      const lastTagStart = cleanHtml.lastIndexOf('<');
      if (lastTagStart !== -1) {
        const lastTagEnd = cleanHtml.indexOf('>', lastTagStart);
        if (lastTagEnd === -1) {
          cleanHtml = cleanHtml.substring(0, lastTagStart);
        }
      }

      // 2. Standard tag closing
      const tagRegex = /<\/?([a-z1-6]+)(?:\s+[^>]*?)?>/gi;
      let match;
      const openTags: string[] = [];
      const voidTags = ['img', 'br', 'hr', 'input', 'meta', 'link', 'area', 'base', 'col', 'embed', 'keygen', 'param', 'source', 'track', 'wbr'];
      
      while ((match = tagRegex.exec(cleanHtml)) !== null) {
        const fullTag = match[0];
        const tagName = match[1].toLowerCase();
        
        if (fullTag.endsWith('/>') || voidTags.includes(tagName)) {
          continue;
        }
        
        if (fullTag.startsWith('</')) {
          const lastIdx = openTags.lastIndexOf(tagName);
          if (lastIdx !== -1) {
            openTags.splice(lastIdx);
          }
        } else {
          openTags.push(tagName);
        }
      }
      
      let closedHtml = cleanHtml;
      while (openTags.length > 0) {
        const tag = openTags.pop();
        closedHtml += `</${tag}>`;
      }
      return closedHtml;
    };

  const cleanMarkdownInValue = (val: any): any => {
    if (typeof val === 'string') {
      let clean = val.trim();
      clean = clean.replace(/^```(?:html|xml|json|markdown)?\s*/i, "");
      clean = clean.replace(/\s*```$/, "");
      clean = clean.trim();
      if (clean.includes('<') && clean.includes('>')) {
        return closeOpenHtmlTags(clean);
      }
      return clean;
    } else if (Array.isArray(val)) {
      return val.map(cleanMarkdownInValue);
    } else if (typeof val === 'object' && val !== null) {
      const res: any = {};
      for (const [k, v] of Object.entries(val)) {
        res[k] = cleanMarkdownInValue(v);
      }
      return res;
    }
    return val;
  };

  // 1. Strip reasoning thoughts if present (<think>...</think> or unclosed <think>)
  processedText = processedText.replace(/<think>[\s\S]*?<\/think>/gi, '');
  processedText = processedText.replace(/<think>[\s\S]*$/gi, '');
  processedText = processedText.trim();

  if (!processedText) return {};

  // 2. Strip markdown code block wrappers (both closed AND unclosed like ```json at start)
  processedText = processedText.replace(/^```(?:json|html|xml|markdown)?\s*/i, '');
  processedText = processedText.replace(/\s*```$/i, '');
  processedText = processedText.trim();

  // If input is direct raw HTML without JSON object structure
  if (processedText.startsWith('<div') || processedText.startsWith('<section') || processedText.startsWith('<article') || processedText.startsWith('<!DOCTYPE') || processedText.startsWith('<html')) {
    return { content: closeOpenHtmlTags(processedText), imagePrompt: "Educational classroom scene" };
  }

  // 3. Extract JSON object from first '{'
  let extractedJson = processedText;
  const firstCurly = processedText.indexOf('{');
  if (firstCurly !== -1) {
    const lastCurly = processedText.lastIndexOf('}');
    if (lastCurly > firstCurly) {
      extractedJson = processedText.substring(firstCurly, lastCurly + 1).trim();
    } else {
      extractedJson = processedText.substring(firstCurly).trim();
    }
  }

  try {
    // First try normal JSON parse on extracted JSON
    return cleanMarkdownInValue(JSON.parse(extractedJson));
  } catch (err) {
    try {
      // Try parsing the original text directly if extraction was somehow off
      return cleanMarkdownInValue(JSON.parse(processedText));
    } catch (errOrig) {
      try {
        const repaired = repairTruncatedJson(extractedJson);
        return cleanMarkdownInValue(JSON.parse(repaired));
      } catch (errRep) {
        try {
          const repaired = repairTruncatedJson(processedText);
          return cleanMarkdownInValue(JSON.parse(repaired));
        } catch (errRep2) {
          if (extractedJson.includes('{')) {
            try {
              const repaired = repairTruncatedJson(extractedJson);
              const evaluated = new Function('return ' + repaired)();
              if (typeof evaluated === 'object' && evaluated !== null) return cleanMarkdownInValue(evaluated);
            } catch(e4) {}
          }
        }
      }
    }

    // Helper regex extractors
    const extractField = (source: string, field: string): string | null => {
      const escapedField = field.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
      const closedRegex = new RegExp(`"${escapedField}"\\s*:\\s*"([\\s\\S]*?)"(?=\\s*,|\\s*})`, 'i');
      const match = source.match(closedRegex);
      if (match && match[1]) {
        let val = match[1].replace(/\\"/g, '"').replace(/\\n/g, '\n');
        if (val.trim().startsWith('<')) {
          val = closeOpenHtmlTags(val);
        }
        return val;
      }

      // Truncated fallback match
      const truncRegex = new RegExp(`"${escapedField}"\\s*:\\s*"([\\s\\S]*?)(?:"\\s*,\\s*"[a-zA-Z0-9_]+"|$)`, 'i');
      const truncMatch = source.match(truncRegex);
      if (truncMatch && truncMatch[1]) {
        let val = truncMatch[1].trim();
        if (val.endsWith('\\')) val = val.slice(0, -1);
        if (val.endsWith('"') && !val.endsWith('\\"')) val = val.slice(0, -1);
        val = val.replace(/\\"/g, '"').replace(/\\n/g, '\n');
        if (val.trim().startsWith('<')) {
          val = closeOpenHtmlTags(val);
        }
        return val;
      }
      return null;
    };

    const extractArrayField = (source: string, field: string): string[] => {
      const escapedField = field.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
      const regex = new RegExp(`"${escapedField}"\\s*:\\s*\\[([\\s\\S]*?)\\]`, 'i');
      const match = source.match(regex);
      if (match && match[1]) {
        return match[1]
          .split(',')
          .map(item => item.trim().replace(/^["']|["']$/g, '').trim())
          .filter(item => item.length > 0);
      }
      return [];
    };

    const textToSearch = processedText;

    // ─── POWERFALLBACK: HEAL TRUNCATED JSON PROPERTIES ───
    const fallbackObj: any = {};
    const stringFields = [
      "content", "memo", "rubric", "assessmentCriteria", "imagePrompt",
      "description", "printInstructions", "notes", "documentType",
      "extractedText", "feedback", "totalScore"
    ];
    
    for (const field of stringFields) {
      const extracted = extractField(textToSearch, field);
      if (extracted !== null) {
        fallbackObj[field] = extracted;
      }
    }
    
    const arrayFields = ["successIndicators", "marksPerQuestion"];
    for (const field of arrayFields) {
      const extracted = extractArrayField(textToSearch, field);
      if (extracted.length > 0) {
        fallbackObj[field] = extracted;
      }
    }

    if (fallbackObj.content || fallbackObj.extractedText || fallbackObj.feedback || fallbackObj.description) {
      console.warn("safeJsonParse: Reconstructed truncated JSON response successfully via fallback regex extraction!");
      return cleanMarkdownInValue(fallbackObj);
    }

    console.warn("Failed to parse AI response as JSON:", processedText);
    return {};
  }
};

// ─── Secure Server Action Routing ─────────

/**
 * Route proxy calls to the secure full-stack backend
 */
export const generateEducationalContent = async (type: string, details: string) => {
  // Native app: no backend — call Gemini directly.
  if (isNativeApp()) {
    const result = await callGeminiClientDirect("generate-educational", { type, details });
    return result.text || "";
  }

  try {
    const response = await axios.post("/api/gemini/action", {
      action: "generate-educational",
      input: { type, details }
    }, {
      // Serverless backends (e.g. Vercel) hard-kill long generations; without a
      // client-side timeout the request can hang forever and the UI appears to
      // "time out". Abort after 60s so we seamlessly fall back to the
      // on-device Gemini engine below instead of leaving the user stuck.
      timeout: 60000
    });
    
    let resultText = response.data.text || "";
    // Clean up any top-level markdown wrappers if the AI wrapped the entire response in a code block
    resultText = resultText.trim();
    if (resultText.startsWith('```')) {
      const lines = resultText.split('\n');
      if (lines.length > 1 && lines[0].startsWith('```')) {
        lines.shift();
      }
      if (lines.length > 0 && lines[lines.length - 1].startsWith('```')) {
        lines.pop();
      }
      resultText = lines.join('\n').trim();
    }
    
    return resultText;
  } catch (error: any) {
    if (isBackendUnavailable(error)) {
      console.warn("[AI Routing] Backend unavailable — using client-side Gemini engine.");
      try {
        const result = await callGeminiClientDirect("generate-educational", { type, details });
        return result.text || "";
      } catch (clientErr: any) {
        checkAndReportApiError(clientErr, "Gemini");
        throw clientErr;
      }
    }
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

function isContentTruncated(content: string): boolean {
  if (!content) return false;
  const trimmed = content.trim();
  if (trimmed.length < 300) return false;
  const lastPart = trimmed.slice(-60);
  const endsProperly = /[.!?)}>\]"]\s*$/.test(lastPart) || /<\/(div|section|article|table|p|ul|ol|li|h[1-6])>\s*$/i.test(lastPart);
  return !endsProperly;
}

const _fetchActionSingleBackend = async (action: string, input: any, onProgress?: (partial: any) => void) => {
  if (onProgress) {
    const response = await fetch("/api/gemini/action", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        action,
        input,
        stream: true
      })
    });
    
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    
    const reader = response.body?.getReader();
    const decoder = new TextDecoder("utf-8");
    let fullText = "";
    let leftover = "";
    let lastUpdateTime = 0;
    
    if (reader) {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        
        const chunk = leftover + decoder.decode(value, { stream: true });
        const lines = chunk.split("\n");
        leftover = lines.pop() || "";
        
        for (const line of lines) {
          const trimmedLine = line.trim();
          if (trimmedLine.startsWith("data: ")) {
            const dataStr = trimmedLine.substring(6);
            try {
              const data = JSON.parse(dataStr);
              if (data.error) throw new Error(data.error);
              if (data.chunk) {
                fullText += data.chunk;
                const now = Date.now();
                if (now - lastUpdateTime > 150) {
                  const parsed = safeJsonParse(fullText);
                  if (parsed && Object.keys(parsed).length > 0) {
                    onProgress(parsed);
                    lastUpdateTime = now;
                  }
                }
              }
              if (data.final) {
                fullText = data.final;
              }
            } catch (e: any) {
              if (e.message && e.message !== "Unexpected end of JSON input" && !e.message.includes("Unexpected token")) {
                throw e;
              }
            }
          }
        }
      }
    }
    const parsed = safeJsonParse(fullText);
    if (parsed && Object.keys(parsed).length > 0) {
      onProgress(parsed);
    }
    if (!parsed || Object.keys(parsed).length === 0) {
      return { content: fullText || "Error: No content generated.", imagePrompt: "Classroom scene" };
    }
    return parsed;
  } else {
    const response = await axios.post("/api/gemini/action", {
      action,
      input
    });
    const parsed = response.data;
    if (!parsed || Object.keys(parsed).length === 0) {
      return { content: "Error: No content generated.", imagePrompt: "Classroom scene" };
    }
    return parsed;
  }
};

// Wrapper that transparently falls back to the client-side Gemini engine when
// the Node backend is unreachable (e.g. inside the standalone Android APK).
const _fetchActionSingle = async (action: string, input: any, onProgress?: (partial: any) => void) => {
  // Native app (Capacitor): there is no backend at all — and Capacitor's local
  // server can answer unknown routes with a 200 HTML page, which would prevent
  // an error-based fallback. So go straight to the client-side engine.
  if (isNativeApp()) {
    try {
      const result = await callGeminiClientDirect(action, input);
      if (onProgress) onProgress(result);
      if (!result || Object.keys(result).length === 0) {
        return { content: "Error: No content generated.", imagePrompt: "Classroom scene" };
      }
      return result;
    } catch (clientErr: any) {
      checkAndReportApiError(clientErr, "Gemini");
      throw clientErr;
    }
  }

  try {
    return await _fetchActionSingleBackend(action, input, onProgress);
  } catch (error: any) {
    if (!isBackendUnavailable(error)) {
      throw error;
    }
    console.warn(`[AI Routing] Backend unavailable for '${action}' — using client-side Gemini engine.`);
    try {
      const result = await callGeminiClientDirect(action, input);
      if (onProgress) onProgress(result);
      if (!result || Object.keys(result).length === 0) {
        return { content: "Error: No content generated.", imagePrompt: "Classroom scene" };
      }
      return result;
    } catch (clientErr: any) {
      checkAndReportApiError(clientErr, "Gemini");
      throw clientErr;
    }
  }
};

const executeWithContinuation = async (action: string, input: any, onProgress?: (partial: any) => void) => {
  let attempts = 0;
  let accumulatedContent = "";
  let lastResult: any = null;

  while (attempts < 3) {
    const currentInput = attempts === 0 ? input : { ...input, existingContent: accumulatedContent };
    
    const result = await _fetchActionSingle(action, currentInput, (partial) => {
      if (onProgress && partial) {
        const combined = {
          ...partial,
          content: accumulatedContent ? (accumulatedContent + "\n" + (partial.content || "")) : (partial.content || "")
        };
        onProgress(combined);
      }
    });

    const newContent = result.content || "";
    if (attempts === 0) {
      accumulatedContent = newContent;
    } else {
      accumulatedContent += "\n" + newContent;
    }

    lastResult = { ...result, content: accumulatedContent };
    if (onProgress) {
      onProgress(lastResult);
    }

    if (!isContentTruncated(newContent) || newContent.length < 500) {
      break;
    }
    attempts++;
  }

  return lastResult;
};

export const generateCAPSContent = async (input: any, onProgress?: (partial: any) => void) => {
  try {
    return await executeWithContinuation("generate-caps", input, onProgress);
  } catch (error: any) {
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const generateVisualAid = async (input: any, onProgress?: (partial: any) => void) => {
  try {
    return await executeWithContinuation("generate-visual", input, onProgress);
  } catch (error: any) {
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const generateAdminDoc = async (input: any, onProgress?: (partial: any) => void) => {
  try {
    return await executeWithContinuation("generate-admin", input, onProgress);
  } catch (error: any) {
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const runOCRScan = async (imageData: string | string[], language: string = 'English', isHandwritten: boolean = true) => {
  if (isNativeApp()) {
    return await callGeminiClientDirect("ocr-scan", { imageData, language, isHandwritten });
  }
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "ocr-scan",
      input: { imageData, language, isHandwritten }
    });
    return response.data;
  } catch (error: any) {
    if (isBackendUnavailable(error)) {
      return await callGeminiClientDirect("ocr-scan", { imageData, language, isHandwritten });
    }
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const runOCRAndGrade = async (imageData: string | string[], rubric: string, language: string = 'English', isHandwritten: boolean = true, behavioralAspects?: string[], adjustLateSubmission?: boolean) => {
  if (isNativeApp()) {
    return await callGeminiClientDirect("ocr-grade", { imageData, rubric, language, isHandwritten, behavioralAspects, adjustLateSubmission });
  }
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "ocr-grade",
      input: { imageData, rubric, language, isHandwritten, behavioralAspects, adjustLateSubmission }
    });
    return response.data;
  } catch (error: any) {
    if (isBackendUnavailable(error)) {
      return await callGeminiClientDirect("ocr-grade", { imageData, rubric, language, isHandwritten, behavioralAspects, adjustLateSubmission });
    }
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const runTextGrade = async (studentAnswers: string, memo: string, rubric: string, language: string = 'English') => {
  if (isNativeApp()) {
    return await callGeminiClientDirect("text-grade", { studentAnswers, memo, rubric, language });
  }
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "text-grade",
      input: { studentAnswers, memo, rubric, language }
    });
    return response.data;
  } catch (error: any) {
    if (isBackendUnavailable(error)) {
      return await callGeminiClientDirect("text-grade", { studentAnswers, memo, rubric, language });
    }
    console.error("Express /api/gemini/action failed text-grade:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const chatWithTutor = async (messages: any[]) => {
  if (isNativeApp()) {
    const result = await callGeminiClientDirect("chat", { messages });
    return result.text || "";
  }
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "chat",
      input: { messages }
    });
    return response.data.text;
  } catch (error: any) {
    if (isBackendUnavailable(error)) {
      const result = await callGeminiClientDirect("chat", { messages });
      return result.text || "";
    }
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};
