import axios from "axios";
import { checkAndReportApiError } from "../lib/apiErrorHelper";

// ─── Prompt Engineering Constants ────────────
export const MASTER_SYSTEM_PROMPT = `
You are the world's most advanced, deeply helpful, and empathetic AI educational assistant, specifically designed to support the South African national school system. You serve teachers, learners, parents, and administrative staff from Grade R through Grade 12 (and Grade 13/matric transition phase).

CRITICAL DATE & YEAR RULE: 
- Today's date is 2 June 2026. THE CURRENT YEAR IS 2026, NOT 2024. 
- All generated content, templates, footers, headers, copyright strings, marking grids, lesson plans, notices, worksheets, administrative letters, and documents MUST display the year "2026". 
- Any custom date generated by you must use "2026" (not 2024). Never output "2024" or reference 2024.

CRITICAL VISUAL DESIGN & ILLUSTRATION RULE:
- Under no circumstances should posters, infographics, flow diagram structures, or visual content types be dominated by long, dense paragraphs of text. 
- You must aggressively break up and punctuate all text with detailed, custom, context-relevant inline illustration or diagram placeholders inside brackets, e.g., \`[Illustration: <detailed, highly-specific visual prompt>]\` or \`[Diagram: <detailed labels and flow-chart prompt>]\`. 
- Each key concept card, section, or bento-grid block inside posters and visual aids must contain its own dedicated illustration placeholder. 
- Keep text inside poster blocks exceptionally brief, punchy, action-oriented, and presented in bullet lists or highlighted capsules with relevant South African emojis (e.g. 🇿🇦, 🦁, 🏔️) rather than raw explanatory prose.

Your outputs must match or exceed the professional quality of our signature EduAI templates: clean, extremely modern, highly vibrant, and interactive layouts. Use full-width background color banners, excellent visual hierarchy, clear instructions, bold answer lines/boxes, scoring areas, educational illustrations/diagrams, and total print-readiness.

YOUR STRICT SAFETY & PEDAGOGICAL BOUNDARIES:
- Age-Appropriateness: Keep language, complexity, and theme strictly matched to the requested South African School Phase (Foundation Phase: Grade R-3, Intermediate Phase: Grade 4-6, Senior Phase: Grade 7-9, FET Phase: Grade 10-12).
- CAPS Alignment: Map all curriculum items cleanly to South African Curriculum and Assessment Policy Statement (CAPS) guidelines.
- Content Moderation: Refuse immediately any request involving self-harm, hate speech, explicit violence, adult themes, or unsafe content. Pivot with warm encouragement: "I'm here to support your schoolwork. Let's explore a positive theme related to your subjects instead!"
- National Pride & Diversity: Reflect South African context (names, cultures, rich geography, Rand currency, local animals/plants) naturally.

OUTPUT FORMATTING GOLDEN RULE:
- If user requests **HTML**: Output a complete standalone HTML5 document with Tailwind CSS via CDN. Include beautiful @media print styles.
- If user requests **JSON**: Follow the specified schemas precisely.
- Never output raw Markdown (like # or ** in HTML values). Use correct bold/heading tags or tailwind classes instead.
- Include a formal, printable Header and Footer stating: "EduAI CAPS Aligned Worksheet".
Make every output teacher-proud, parent-shareable, and ready for immediate printing or digital use in South African schools.
`;

export const IMAGE_PROMPT_GOLDEN_RULE = `
World-class masterpiece work of art, crisp render, sharp focus, charmingly aesthetic design, 4k, soft lighting, masterpiece emoji-style figurine 3D render, 3D Disney Character render, pure white background, natural beauty, ultra-detailed 3D digital asset, vibrant colors, perfect composition, no text overlays (text will be added separately), no borders, no frames, no watermarks, museum-quality detail
`;

const repairTruncatedJson = (jsonStr: string): string => {
  let inString = false;
  let escape = false;
  const stack: string[] = [];
  
  for (let i = 0; i < jsonStr.length; i++) {
    const char = jsonStr[i];
    if (escape) {
      escape = false;
      continue;
    }
    if (char === '\\') {
      escape = true;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      continue;
    }
    if (!inString) {
      if (char === '{' || char === '[') {
        stack.push(char);
      } else if (char === '}') {
        if (stack.length > 0 && stack[stack.length - 1] === '{') {
          stack.pop();
        }
      } else if (char === ']') {
        if (stack.length > 0 && stack[stack.length - 1] === '[') {
          stack.pop();
        }
      }
    }
  }

  let repaired = jsonStr;
  if (inString) {
    repaired += '"';
  }
  
  while (stack.length > 0) {
    const last = stack.pop();
    if (last === '{') {
      repaired += '}';
    } else if (last === '[') {
      repaired += ']';
    }
  }
  
  repaired = repaired.replace(/,\s*([}\]])/g, '$1');
  return repaired;
};

/**
 * Robust regex-based recovery parser for when JSON responses are slightly truncated
 * or malformed (power-fallback mechanism).
 */
export const safeJsonParse = (text: string | null | undefined): any => {
  if (!text) return {};
  let processedText = text.trim();
  
  // 1. Strip reasoning thoughts if present (<think>...</think> or unclosed <think>)
  processedText = processedText.replace(/<think>[\s\S]*?<\/think>/gi, '');
  processedText = processedText.replace(/<think>[\s\S]*$/gi, '');
  processedText = processedText.trim();

  if (!processedText) return {};

  // 2. Extract content from markdown JSON block or generic markdown block anywhere in the text
  if (processedText.includes("```json")) {
    const match = processedText.match(/```json\s*([\s\S]*?)\s*```/i);
    if (match) {
      processedText = match[1].trim();
    }
  } else if (processedText.includes("```")) {
    const match = processedText.match(/```\s*([\s\S]*?)\s*```/);
    if (match) {
      processedText = match[1].trim();
    }
  }

  // 3. Extract the clean JSON object if there is leading/trailing conversational text
  let extractedJson = processedText;
  if (processedText.includes("{") && processedText.includes("}")) {
    const firstCurly = processedText.indexOf("{");
    const lastCurly = processedText.lastIndexOf("}");
    extractedJson = processedText.substring(firstCurly, lastCurly + 1).trim();
  }

  try {
    // First try normal JSON parse on extracted JSON
    return JSON.parse(extractedJson);
  } catch (err) {
    try {
      // Try parsing the original text directly if extraction was somehow off
      return JSON.parse(processedText);
    } catch (errOrig) {
      try {
        const repaired = repairTruncatedJson(extractedJson);
        return JSON.parse(repaired);
      } catch (errRep) {
        console.warn("safeJsonParse: Standard and repaired JSON parse failed, trying regex fallback...", errRep);

        // Direct Javascript execution/extraction recovery if brackets are matched at all
        if (extractedJson.includes('{') && extractedJson.includes('}')) {
          try {
            const repaired = repairTruncatedJson(extractedJson);
            const evaluated = new Function('return ' + repaired)();
            if (typeof evaluated === 'object' && evaluated !== null) return evaluated;
          } catch(e4) {}
          try {
            const evaluated = new Function('return ' + extractedJson)();
            if (typeof evaluated === 'object' && evaluated !== null) return evaluated;
          } catch(e5) {}
        }
      }
    }

    const closeOpenHtmlTags = (html: string): string => {
      const tagRegex = /<\/?([a-z1-6]+)(?:\s+[^>]*?)?>/gi;
      let match;
      const openTags: string[] = [];
      
      while ((match = tagRegex.exec(html)) !== null) {
        const fullTag = match[0];
        const tagName = match[1].toLowerCase();
        
        if (fullTag.endsWith('/>') || ['img', 'br', 'hr', 'input', 'meta', 'link'].includes(tagName)) {
          continue;
        }
        
        if (fullTag.startsWith('</')) {
          if (openTags.length > 0 && openTags[openTags.length - 1] === tagName) {
            openTags.pop();
          }
        } else {
          openTags.push(tagName);
        }
      }
      
      let closedHtml = html;
      while (openTags.length > 0) {
        const tag = openTags.pop();
        closedHtml += `</${tag}>`;
      }
      return closedHtml;
    };

    // Helper regex extractors
    const extractField = (source: string, field: string): string | null => {
      const escapedField = field.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
      const regex = new RegExp(`"${escapedField}"\\s*:\\s*"([\\s\\S]*?)"(?=\\s*,|\\s*})`, 'i');
      const match = source.match(regex);
      if (match) {
        let val = match[1].replace(/\\"/g, '"').replace(/\\n/g, '\n');
        if (val.trim().startsWith('<')) {
          val = closeOpenHtmlTags(val);
        }
        return val;
      }

      // Truncated fallback match
      const truncatedRegex = new RegExp(`"${escapedField}"\\s*:\\s*"([\\s\\S]*)$`, 'i');
      const truncMatch = source.match(truncatedRegex);
      if (truncMatch) {
        let val = truncMatch[1].trim();
        if (val.endsWith('\\')) {
          val = val.slice(0, -1);
        }
        if (val.endsWith('"') && !val.endsWith('\\"')) {
          val = val.slice(0, -1);
        }
        val = val.replace(/\\"/g, '"').replace(/\\n/g, '\n');
        if (val.trim().startsWith('<')) {
          val = closeOpenHtmlTags(val);
        }
        return val;
      }
      return null;
    };

    const extractArrayField = (source: string, field: string): string[] => {
      const escapedField = field.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
      const regex = new RegExp(`"${escapedField}"\\s*:\\s*\\[([\\s\\S]*?)\\]`, 'i');
      const match = source.match(regex);
      if (match && match[1]) {
        return match[1]
          .split(',')
          .map(item => item.trim().replace(/^["']|["']$/g, '').trim())
          .filter(item => item.length > 0);
      }
      return [];
    };

    const textToSearch = processedText;

    // ─── POWERFALLBACK: HEAL TRUNCATED JSON PROPERTIES ───
    const fallbackObj: any = {};
    const stringFields = [
      "content", "memo", "rubric", "assessmentCriteria", "imagePrompt",
      "description", "printInstructions", "notes", "documentType",
      "extractedText", "feedback", "totalScore"
    ];
    
    for (const field of stringFields) {
      const extracted = extractField(textToSearch, field);
      if (extracted !== null) {
        fallbackObj[field] = extracted;
      }
    }
    
    const arrayFields = ["successIndicators", "marksPerQuestion"];
    for (const field of arrayFields) {
      const extracted = extractArrayField(textToSearch, field);
      if (extracted.length > 0) {
        fallbackObj[field] = extracted;
      }
    }

    if (fallbackObj.content || fallbackObj.extractedText || fallbackObj.feedback || fallbackObj.description) {
      console.warn("safeJsonParse: Reconstructed truncated JSON response successfully via fallback regex extraction!");
      return fallbackObj;
    }

    console.warn("Failed to parse AI response as JSON:", processedText);
    return {};
  }
};

// ─── Secure Server Action Routing ─────────

/**
 * Route proxy calls to the secure full-stack backend
 */
export const generateEducationalContent = async (type: string, details: string) => {
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "generate-educational",
      input: { type, details }
    });
    return response.data.text;
  } catch (error: any) {
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const generateCAPSContent = async (input: any) => {
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "generate-caps",
      input
    });
    return response.data;
  } catch (error: any) {
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const generateVisualAid = async (input: any) => {
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "generate-visual",
      input
    });
    return response.data;
  } catch (error: any) {
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const generateAdminDoc = async (input: any) => {
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "generate-admin",
      input
    });
    return response.data;
  } catch (error: any) {
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const runOCRScan = async (imageData: string | string[], language: string = 'English', isHandwritten: boolean = true) => {
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "ocr-scan",
      input: { imageData, language, isHandwritten }
    });
    return response.data;
  } catch (error: any) {
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const runOCRAndGrade = async (imageData: string | string[], rubric: string, language: string = 'English', isHandwritten: boolean = true, behavioralAspects?: string[], adjustLateSubmission?: boolean) => {
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "ocr-grade",
      input: { imageData, rubric, language, isHandwritten, behavioralAspects, adjustLateSubmission }
    });
    return response.data;
  } catch (error: any) {
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const runTextGrade = async (studentAnswers: string, memo: string, rubric: string, language: string = 'English') => {
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "text-grade",
      input: { studentAnswers, memo, rubric, language }
    });
    return response.data;
  } catch (error: any) {
    console.error("Express /api/gemini/action failed text-grade:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};

export const chatWithTutor = async (messages: any[]) => {
  try {
    const response = await axios.post("/api/gemini/action", {
      action: "chat",
      input: { messages }
    });
    return response.data.text;
  } catch (error: any) {
    console.error("Express /api/gemini/action failed:", error.message || error);
    checkAndReportApiError(error, "Gemini");
    throw error;
  }
};
