/**
 * Canonical content-template contract (docs/CONTENT_TEMPLATE.md).
 *
 * Three guarantees must hold for EVERY generated document:
 *   1. ONCE     — the compliance labels appear exactly once.
 *   2. GRADIENT — no top banner is a single flat colour.
 *   3. FOOTER   — one canonical footer line, word for word.
 *
 * `npm run verify:template` proves the same contract end-to-end for the static
 * demos; this suite proves it for arbitrary model output shapes.
 */
import { describe, expect, it } from 'vitest';
import {
  EDUAI_COMPLIANCE_LABELS,
  EDUAI_TEMPLATE_FOOTER_LINE,
  buildCAPSCode,
  isCurrentTemplateOutput,
  wrapWithTemplate,
} from '../src/lib/contentTemplate';

/** A realistic "messy" model document: its own banner, badge spam and footer. */
const messyModelOutput = `
<section style="background:#002395;color:#fff;padding:20px;border-radius:12px;">
  <h1>Data Handling — Grade 2 Mathematics</h1>
  <p>CAPS Code: FP-MATH-G2-T3-DH01</p>
  <div>🇿🇦 ✅ CAPS Aligned ✅ NPA Compliant ✅ POPIA Compliant (2026) ✅ SIAS Level 1 Inclusive ✅ WP6 Differentiated</div>
</section>
<div class="card">
  <h2>Activity 1</h2>
  <ul><li>Count the objects and draw a tally.</li></ul>
</div>
<footer>Generated by AI · CAPS Aligned · NPA Compliant</footer>
`;

const meta = {
  title: 'Data Handling',
  subject: 'Mathematics',
  grade: '2',
  term: 'Term 3',
  contentType: 'Worksheet',
  date: '02/10/2026',
};

describe('wrapWithTemplate — contract', () => {
  const wrapped = wrapWithTemplate(messyModelOutput, meta);

  it('produces a non-empty document for valid input', () => {
    expect(wrapped.length).toBeGreaterThan(500);
  });

  it('returns empty input untouched', () => {
    expect(wrapWithTemplate('', meta)).toBe('');
    expect(wrapWithTemplate('   ', meta)).toBe('   ');
  });

  it('ONCE — renders the compliance labels exactly one time', () => {
    const occurrences = wrapped.split(EDUAI_COMPLIANCE_LABELS).length - 1;
    expect(occurrences).toBe(1);
  });

  it('ONCE — strips model-authored compliance copies from the body', () => {
    const badgeCount = (wrapped.match(/POPIA Compliant/gi) || []).length;
    expect(badgeCount).toBe(1);
  });

  it('FOOTER — contains the canonical footer line word for word', () => {
    expect(wrapped).toContain(EDUAI_TEMPLATE_FOOTER_LINE);
  });

  it('FOOTER — removes the model-authored footer', () => {
    expect(wrapped).not.toContain('Generated by AI');
  });

  it('GRADIENT — the top banner is a two-colour gradient, never a flat fill', () => {
    // `applyBannerGradients` guarantees the topmost banner/header element is a
    // gradient. The host compliance banner is inserted first, so it is the top
    // banner and it must carry the canonical navy → blue gradient.
    const firstBanner = wrapped.match(
      /<(?:header|section)[^>]*(?:eduai-compliance-banner|class\s*=\s*"[^"]*banner)[^>]*>/i,
    )?.[0];
    expect(firstBanner, 'a top banner element should exist').toBeTruthy();
    const style = firstBanner!.match(/background(?:-image)?\s*:\s*([^;"]+)/i)?.[1] ?? '';
    expect(style).toMatch(/linear-gradient\(/i);
    expect(style).toMatch(/#1e3a5f/i);
    expect(style).toMatch(/#2563eb/i);
  });

  it('GRADIENT — header wash is also a gradient', () => {
    const header = wrapped.match(/<header class="site-header"[\s\S]*?>/i)?.[0] ?? '';
    expect(header).toMatch(/linear-gradient\(/i);
  });

  it('GRADIENT — gradient definitions never degrade to one stop', () => {
    const gradients = wrapped.match(/linear-gradient\([^)]*\)/gi) || [];
    expect(gradients.length).toBeGreaterThan(0);
    for (const gradient of gradients) {
      expect(gradient.split(',').length).toBeGreaterThanOrEqual(3);
    }
  });

  it('keeps the document title and marks the output as template-native', () => {
    expect(wrapped).toContain('Data Handling');
    expect(isCurrentTemplateOutput(wrapped)).toBe(true);
  });

  it('is idempotent — wrapping twice changes nothing', () => {
    expect(wrapWithTemplate(wrapped, meta)).toBe(wrapped);
  });
});

describe('buildCAPSCode', () => {
  it('honours an explicit CAPS code', () => {
    expect(buildCAPSCode({ ...meta, capsCode: 'FP-MATH-G2-T3-DH01' })).toBe('FP-MATH-G2-T3-DH01');
  });

  it('derives a phase-prefixed code when none is supplied', () => {
    expect(buildCAPSCode(meta)).toMatch(/^FP-MATH-G2-T3-[A-Z]{2,3}01$/);
  });

  it('maps grades to the correct CAPS phase prefix', () => {
    const codeFor = (grade: string) => buildCAPSCode({ ...meta, grade, title: 'Fractions' });
    expect(codeFor('R')).toMatch(/^FP-/);
    expect(codeFor('3')).toMatch(/^FP-/);
    expect(codeFor('5')).toMatch(/^IP-/);
    expect(codeFor('8')).toMatch(/^SP-/);
    expect(codeFor('11')).toMatch(/^FET-/);
  });

  it('never emits an empty code for sparse metadata', () => {
    const code = buildCAPSCode({});
    expect(code).toMatch(/^EDU-GEN-GX-T1-[A-Z]{2,3}01$/);
  });
});
