/**
 * Canonical content-template contract (docs/CONTENT_TEMPLATE.md).
 *
 * Three guarantees must hold for EVERY generated document:
 *   1. ONCE     — ONE banner holds the title, every label and the compliance
 *                 data; nothing at the top of the page is duplicated.
 *   2. GRADIENT — the banner is a two-colour VERTICAL gradient, and the page
 *                 header is a very light blue bar at 70% transparency.
 *   3. FOOTER   — one canonical footer line, word for word.
 *
 * `npm run verify:template` proves the same contract end-to-end for the static
 * demos; this suite proves it for arbitrary model output shapes.
 */
import { describe, expect, it } from 'vitest';
import {
  BANNER_PALETTES,
  BANNER_PALETTE_IDS,
  EDUAI_BANNER_GRADIENT,
  EDUAI_COMPLIANCE_LABELS,
  EDUAI_HEADER_TINT,
  EDUAI_TEMPLATE_FOOTER_LINE,
  bannerGradientFor,
  bannerPaletteFor,
  buildCAPSCode,
  buildTemplateComplianceBannerHTML,
  contrastWithWhite,
  isBannerGradient,
  isCurrentTemplateOutput,
  isKnownBannerGradient,
  wrapWithTemplate,
} from '../src/lib/contentTemplate';
import { ADMIN_TYPES, TEACHING_CATEGORIES, VISUAL_TYPES } from '../src/lib/contentTypes';

/** A realistic "messy" model document: its own banner, badge spam and footer. */
const messyModelOutput = `
<section style="background:#002395;color:#fff;padding:20px;border-radius:12px;">
  <h1>Data Handling — Grade 2 Mathematics</h1>
  <p>CAPS Code: FP-MATH-G2-T3-DH01</p>
  <div>🇿🇦 ✅ CAPS Aligned ✅ NPA Compliant ✅ POPIA Compliant (2026) ✅ SIAS Level 1 Inclusive ✅ WP6 Differentiated</div>
</section>
<section class="compliance-strip">
  <span class="stamp">✅ CAPS Aligned</span><span class="stamp">✅ NPA Compliant</span>
</section>
<div class="lesson-meta"><span class="meta-pill">Grade 2</span><span class="meta-pill">Mathematics</span><span class="meta-pill">Worksheet</span></div>
<h1 class="lesson-title">Data Handling</h1>
<div class="card">
  <h2>Activity 1</h2>
  <ul><li>Count the objects and draw a tally.</li></ul>
</div>
<footer>Generated by AI · CAPS Aligned · NPA Compliant</footer>
`;

const meta = {
  title: 'Data Handling',
  subject: 'Mathematics',
  grade: '2',
  term: 'Term 3',
  contentType: 'Worksheet',
  date: '02/10/2026',
  school: 'Springfield Primary',
  teacher: 'Mrs Ndlovu',
};

describe('wrapWithTemplate — contract', () => {
  const wrapped = wrapWithTemplate(messyModelOutput, meta);

  it('produces a non-empty document for valid input', () => {
    expect(wrapped.length).toBeGreaterThan(500);
  });

  it('returns empty input untouched', () => {
    expect(wrapWithTemplate('', meta)).toBe('');
    expect(wrapWithTemplate('   ', meta)).toBe('   ');
  });

  it('ONCE — renders the compliance labels exactly one time', () => {
    const occurrences = wrapped.split(EDUAI_COMPLIANCE_LABELS).length - 1;
    expect(occurrences).toBe(1);
  });

  it('ONCE — strips model-authored compliance copies from the body', () => {
    const badgeCount = (wrapped.match(/POPIA Compliant/gi) || []).length;
    expect(badgeCount).toBe(1);
  });

  it('ONCE — leaves exactly one banner in the whole document', () => {
    const banners = (wrapped.match(/class="[^"]*\beduai-compliance-banner\b/gi) || []).length;
    expect(banners).toBe(1);
  });

  it('ONCE — the single banner carries the title, every label and the date', () => {
    const banner = wrapped.slice(wrapped.indexOf('class="eduai-compliance-banner'));
    const bannerMarkup = banner.slice(0, banner.indexOf('</section>'));
    expect(bannerMarkup).toContain('Data Handling');
    expect(bannerMarkup).toContain('Grade 2');
    expect(bannerMarkup).toContain('Mathematics');
    expect(bannerMarkup).toContain('Worksheet');
    expect(bannerMarkup).toContain('Term 3');
    expect(bannerMarkup).toContain('02/10/2026');
    expect(bannerMarkup).toContain('Springfield Primary');
    expect(bannerMarkup).toContain('Mrs Ndlovu');
    expect(bannerMarkup).toContain('CAPS Code');
    expect(bannerMarkup).toContain(EDUAI_COMPLIANCE_LABELS);
  });

  it('ONCE — the document title / metadata are not repeated above the banner', () => {
    const beforeBanner = wrapped.slice(0, wrapped.indexOf('class="eduai-compliance-banner'));
    expect(beforeBanner).not.toContain('Data Handling');
    expect(beforeBanner).not.toContain('Mathematics');
    // The page header is brand-only now.
    expect(beforeBanner).toContain('EDUAI COMPANION 2026');
  });

  it('ONCE — drops the model-authored duplicate banner and title block', () => {
    expect(wrapped).not.toContain('Data Handling — Grade 2 Mathematics');
    expect(wrapped).not.toContain('CAPS Code: FP-MATH-G2-T3-DH01');
    expect((wrapped.match(/CAPS\s*Code/gi) || []).length).toBe(1);
    // The repeated <h1 class="lesson-title"> block is gone too: only the banner
    // renders a title.
    expect((wrapped.match(/<h1[^>]*class="[^"]*\blesson-title\b/gi) || []).length).toBe(1);
  });

  it('FOOTER — contains the canonical footer line word for word', () => {
    expect(wrapped).toContain(EDUAI_TEMPLATE_FOOTER_LINE);
    expect(wrapped).not.toContain('Generated by AI');
  });

  it('GRADIENT — the banner is a two-colour VERTICAL gradient in the WORKSHEET palette', () => {
    const firstBanner = wrapped.match(
      /<(?:header|section)[^>]*(?:eduai-compliance-banner|class\s*=\s*"[^"]*banner)[^>]*>/i,
    )?.[0];
    expect(firstBanner, 'a top banner element should exist').toBeTruthy();
    const style = firstBanner!.match(/background(?:-image)?\s*:\s*([^;"]+)/i)?.[1] ?? '';
    // Content type is "Worksheet" → the bright orange → magenta palette, never
    // the old navy default and never a solid fill.
    expect(style).toBe(bannerGradientFor('Worksheet'));
    expect(style).toBe(BANNER_PALETTES.worksheet.gradient);
    expect(style).not.toBe(EDUAI_BANNER_GRADIENT);
    expect(style).toMatch(/linear-gradient\(180deg/i);
    expect(style).toMatch(/#c2410c/i);
    expect(style).toMatch(/#be185d/i);
  });

  it('GRADIENT — the document publishes its palette as a scoped custom property', () => {
    expect(wrapped).toContain(`--eduai-banner-gradient: ${bannerGradientFor('Worksheet')}`);
    // The model repaint rules and the stylesheet safety nets both read the var.
    expect(wrapped).toMatch(/background(-image)?:\s*var\(--eduai-banner-gradient/);
  });

  it('GRADIENT — every gradient definition keeps two stops or more', () => {
    const gradients = wrapped.match(/linear-gradient\([^)]*\)/gi) || [];
    expect(gradients.length).toBeGreaterThan(0);
    for (const gradient of gradients) {
      expect(gradient.split(',').length).toBeGreaterThanOrEqual(3);
    }
  });

  it('HEADER — very light blue, 70% transparent', () => {
    const header = wrapped.match(/<header class="site-header"[\s\S]*?>/i)?.[0] ?? '';
    expect(header).toMatch(/linear-gradient\(180deg/i);
    expect(header).toContain(EDUAI_HEADER_TINT);
    expect(header).toMatch(/rgba\(219,\s*234,\s*254,\s*0\.30\)/);
    // Never a solid fill.
    expect(header).not.toMatch(/background:\s*#(?!.*gradient)/i);
  });

  it('keeps the document title and marks the output as template-native', () => {
    expect(wrapped).toContain('Data Handling');
    expect(isCurrentTemplateOutput(wrapped)).toBe(true);
  });

  it('is idempotent — wrapping twice changes nothing', () => {
    expect(wrapWithTemplate(wrapped, meta)).toBe(wrapped);
  });
});

describe('buildTemplateComplianceBannerHTML — the single banner', () => {
  it('renders the title, pills and compliance line inside one element', () => {
    const banner = buildTemplateComplianceBannerHTML(meta);
    expect((banner.match(/<section\b/g) || []).length).toBe(1);
    expect(banner).toContain('Data Handling');
    expect(banner).toContain('Grade 2');
    expect(banner).toContain('Term 3');
    expect(banner).toContain('02/10/2026');
    expect(banner).toContain('CAPS Code');
    expect(banner).toContain('🇿🇦');
    expect(banner).toMatch(/data-eduai-palette="worksheet"/);
    expect(banner).toContain(`background: ${bannerGradientFor('Worksheet')}`);
    expect(banner).toMatch(/linear-gradient\(180deg, #c2410c 0%, #be185d 100%\)/);
  });

  it('never repeats a pill value twice', () => {
    const banner = buildTemplateComplianceBannerHTML({ ...meta, subject: 'Worksheet' });
    expect((banner.match(/>Worksheet</g) || []).length).toBe(1);
  });

  it('normalises dates to SA DD/MM/YYYY', () => {
    expect(buildTemplateComplianceBannerHTML({ ...meta, date: '2026-10-03' })).toContain('03/10/2026');
    expect(buildTemplateComplianceBannerHTML({ ...meta, date: '2026/10/03' })).toContain('03/10/2026');
  });
});

describe('buildCAPSCode', () => {
  it('honours an explicit CAPS code', () => {
    expect(buildCAPSCode({ ...meta, capsCode: 'FP-MATH-G2-T3-DH01' })).toBe('FP-MATH-G2-T3-DH01');
  });

  it('derives a phase-prefixed code when none is supplied', () => {
    expect(buildCAPSCode(meta)).toMatch(/^FP-MATH-G2-T3-[A-Z]{2,3}01$/);
  });

  it('maps grades to the correct CAPS phase prefix', () => {
    const codeFor = (grade: string) => buildCAPSCode({ ...meta, grade, title: 'Fractions' });
    expect(codeFor('R')).toMatch(/^FP-/);
    expect(codeFor('3')).toMatch(/^FP-/);
    expect(codeFor('5')).toMatch(/^IP-/);
    expect(codeFor('8')).toMatch(/^SP-/);
    expect(codeFor('11')).toMatch(/^FET-/);
  });

  it('never emits an empty code for sparse metadata', () => {
    const code = buildCAPSCode({});
    expect(code).toMatch(/^EDU-GEN-GX-T1-[A-Z]{2,3}01$/);
  });
});

/**
 * The bands models actually open a document with: a school letterhead, a CAPS
 * reference bar, a "formal assessment header" and a metadata strip — all
 * repeating what the ONE banner shows. Every one of them is absorbed into the
 * banner (data preserved once) and deleted from the page (space preserved).
 */
const multiBandModelOutput = `
<header class="school-header">
  <h1>Sunrise Primary School</h1>
  <p>EMIS: 123456 | Gauteng Province | District: Ekurhuleni</p>
</header>
<div class="caps-bar" style="background:#002395;color:#fff">CAPS Reference: Mathematics Grade 5 Term 2 — Data Handling | ATP Week 4</div>
<div class="meta" style="background:#007749;color:#fff">Subject: Mathematics | Grade: 5 | Term: 2 | Date: 04/10/2026 | Total Marks: 20 | Duration: 45 minutes</div>
<header class="banner" style="background:#de3831"><h1>Data Handling — Grade 5 Mathematics</h1></header>
<article class="card">
  <h2>Activity 1</h2>
  <p>Count the tally marks and complete the table. Then draw a bar graph of the results and answer the questions that follow.</p>
</article>
`;

describe('collapseLeadingChrome — every top band folds into the ONE banner', () => {
  const wrapped = wrapWithTemplate(multiBandModelOutput, {
    title: 'Data Handling',
    subject: 'Mathematics',
    grade: '5',
    term: 'Term 2',
    contentType: 'Worksheet',
    date: '04/10/2026',
  });

  it('leaves exactly one banner and one copy of every label', () => {
    expect((wrapped.match(/class="[^"]*\beduai-compliance-banner\b/gi) || []).length).toBe(1);
    expect((wrapped.match(/CAPS\s*Code/gi) || []).length).toBe(1);
    expect((wrapped.match(/POPIA Compliant/gi) || []).length).toBe(1);
    expect((wrapped.match(/CAPS Aligned/gi) || []).length).toBe(1);
  });

  it('removes the model school header, CAPS bar, meta strip and duplicate banner', () => {
    expect(wrapped).not.toContain('school-header');
    expect(wrapped).not.toContain('caps-bar');
    expect(wrapped).not.toContain('class="meta"');
    expect(wrapped).not.toContain('Data Handling — Grade 5 Mathematics');
  });

  it('moves the harvested values into the one banner instead of losing them', () => {
    const banner = wrapped.slice(wrapped.indexOf('class="eduai-compliance-banner'), wrapped.indexOf('</section>'));
    expect(banner).toContain('School: Sunrise Primary School');
    expect(banner).toContain('Total: 20 marks');
    expect(banner).toContain('45 minutes');
    expect(banner).toContain('ATP: Week 4');
    expect(banner).toContain('Mathematics Grade 5 Term 2 — Data Handling');
  });

  it('keeps the real content untouched', () => {
    expect(wrapped).toContain('Count the tally marks and complete the table');
  });

  it('never eats a hero illustration or a genuine section heading', () => {
    const poster = wrapWithTemplate(
      `<div class="poster-container"><div class="hero-section"><p>Big illustration here</p></div><div class="content-card"><h3>Save water</h3></div></div>`,
      { title: 'Water Wise Poster', subject: 'Natural Sciences', grade: '4', contentType: 'Poster' },
    );
    expect(poster).toContain('Big illustration here');
    expect(poster).toContain('Save water');

    const heroBand = wrapWithTemplate(
      `<div class="hero" style="background:#002395;color:#fff"><h1>Water Wise Poster</h1><p>Grade 4 · Natural Sciences</p></div><p>Turn off the tap while brushing.</p>`,
      { title: 'Water Wise Poster', subject: 'Natural Sciences', grade: '4', contentType: 'Poster' },
    );
    expect(heroBand).not.toContain('class="hero"');
    expect(heroBand).toContain('Turn off the tap while brushing.');
  });

  it('collapses a band nested in a whole-document wrapper', () => {
    const nested = wrapWithTemplate(
      `<div class="poster-container"><div class="banner" style="background:#2563eb"><h1>Water Wise Poster</h1><p>Grade 4 Natural Sciences · Term 3</p></div><div class="content-card"><h3>Save water</h3></div></div>`,
      { title: 'Water Wise Poster', subject: 'Natural Sciences', grade: '4', contentType: 'Poster' },
    );
    expect(nested).not.toContain('class="banner"');
    expect(nested).toContain('Save water');
  });
});

describe('SA pipeline — the same ONE-banner contract for structured documents', () => {
  it('absorbs model-authored bands in an HTML payload (buildFullHTML)', async () => {
    const { buildFullHTML } = await import('../src/lib/templates/sa-html-templates');
    const data = {
      metadata: {
        title: 'Data Handling',
        subject: 'Mathematics',
        grade: '5',
        phase: 'Intermediate Phase',
        term: 2,
        contentType: 'worksheet',
        generatedDate: '04/10/2026',
      },
      sections: [{ sectionId: 1, heading: 'Activity 1', content: '<p>Count the tallies.</p>', bloomsLevel: null, marks: null }],
      content: `<header class="school-header"><h1>Sunrise Primary School</h1><p>EMIS: 123456</p></header>
        <div class="caps-bar" style="background:#002395;color:#fff">CAPS Aligned | NPA Compliant | POPIA Compliant (2026) | SIAS Level 1 Inclusive | WP6 Differentiated</div>
        <div class="section"><div class="section-heading">Activity 1</div><div class="section-body"><p>Count the tallies.</p></div></div>`,
    } as any;

    const html = buildFullHTML(data, []);
    expect((html.match(/class="[^"]*\beduai-compliance-banner\b/gi) || []).length).toBe(1);
    expect((html.match(/CAPS Aligned/g) || []).length).toBe(1);
    expect((html.match(/POPIA Compliant/g) || []).length).toBe(1);
    expect(html).not.toContain('school-header');
    expect(html).not.toContain('caps-bar');
    expect(html).toContain('Count the tallies.');
  });

  it('renders every generated band on a two-colour VERTICAL gradient (never a solid fill)', async () => {
    const { SA_BASE_CSS } = await import('../src/lib/templates/sa-html-templates');
    const bands = ['\\.section-heading', '\\.diff-core \\.diff-header', '\\.diff-extended \\.diff-header', '\\.diff-simplified \\.diff-header', '\\.npa-table th', '\\.marks-table th'];
    for (const band of bands) {
      const rule = new RegExp(`${band}\\s*\\{[^}]*\\}`, 'i').exec(SA_BASE_CSS)?.[0] ?? '';
      expect(rule, `${band} should exist`).not.toBe('');
      expect(rule, `${band} must use a 180deg gradient`).toMatch(/linear-gradient\(180deg/i);
    }
  });
});

describe('banner palettes — a bright two-colour gradient per content type', () => {
  it('ships at least eight palettes and every gradient is two-stop 180deg', () => {
    expect(BANNER_PALETTE_IDS.length).toBeGreaterThanOrEqual(8);
    for (const id of BANNER_PALETTE_IDS) {
      const palette = BANNER_PALETTES[id];
      expect(palette.gradient, `${id} gradient`).toBe(
        `linear-gradient(180deg, ${palette.from} 0%, ${palette.to} 100%)`,
      );
      expect(isBannerGradient(palette.gradient), `${id} shape`).toBe(true);
      expect(isKnownBannerGradient(palette.gradient), `${id} known`).toBe(true);
      expect(palette.from, `${id} has two DIFFERENT stops`).not.toBe(palette.to);
      expect(palette.gradient.split(',').length).toBe(3);
      expect(palette.gradient).toMatch(/180deg/);
    }
  });

  it('keeps white banner text legible on both stops of every palette', () => {
    for (const id of BANNER_PALETTE_IDS) {
      const { from, to } = BANNER_PALETTES[id];
      expect(contrastWithWhite(from), `${id} top stop`).toBeGreaterThanOrEqual(4.5);
      expect(contrastWithWhite(to), `${id} bottom stop`).toBeGreaterThanOrEqual(4.5);
    }
  });

  it('uses a DIFFERENT palette for different content types (never one navy default)', () => {
    const sample: Record<string, string> = {
      'Lesson Plan': 'lesson',
      'Worksheet': 'worksheet',
      'Controlled Test': 'assessment',
      'Marking Memo': 'memo',
      'Educational Poster': 'poster',
      'Flashcards (Term + Definition)': 'cards',
      'Letter to Parents': 'admin',
      'Participation Certificate': 'certificate',
      'SIAS Individualized Learning Plan': 'intervention',
      'Interactive Foundation Learning Pack': 'foundation',
    };
    for (const [contentType, expectedId] of Object.entries(sample)) {
      expect(bannerPaletteFor(contentType).id, contentType).toBe(expectedId);
    }
    // …and each of those gradients is distinct from every other one.
    const gradients = Object.keys(sample).map((type) => bannerGradientFor(type));
    expect(new Set(gradients).size).toBe(gradients.length);
    // The workbook types never fall back to the brand navy pair.
    for (const type of Object.keys(sample)) {
      expect(bannerGradientFor(type)).not.toBe(EDUAI_BANNER_GRADIENT);
    }
  });

  it('maps EVERY content type the Content Creator offers onto a named palette', () => {
    const offered = [
      ...Object.values(TEACHING_CATEGORIES),
      ...Object.values(VISUAL_TYPES),
      ...Object.values(ADMIN_TYPES),
    ].flat();
    expect(offered.length).toBeGreaterThan(40);
    const unmapped = offered.filter((type) => bannerPaletteFor(type).id === 'brand');
    expect(unmapped, `types without a palette: ${unmapped.join(', ')}`).toEqual([]);
  });

  it('falls back to the brand palette only for unrecognised types, and honours an override', () => {
    expect(bannerPaletteFor(undefined).id).toBe('brand');
    expect(bannerPaletteFor('Untitled Generation').id).toBe('brand');
    expect(bannerPaletteFor('Worksheet', 'certificate').id).toBe('certificate');
    expect(bannerPaletteFor('Worksheet', 'not-a-palette').id).toBe('worksheet');
  });

  it('wraps the same body in a different-coloured banner per content type', () => {
    const body = '<h2>Activity 1</h2><p>Count the tallies.</p>';
    const worksheets = wrapWithTemplate(body, { title: 'Data Handling', contentType: 'Worksheet' });
    const exams = wrapWithTemplate(body, { title: 'Data Handling', contentType: 'Controlled Test' });
    expect(worksheets).toContain(bannerGradientFor('Worksheet'));
    expect(exams).toContain(bannerGradientFor('Controlled Test'));
    expect(worksheets).not.toContain(bannerGradientFor('Controlled Test'));
    // Both still honour the whole contract: one banner, one gradient, one footer.
    for (const doc of [worksheets, exams]) {
      expect((doc.match(/class="[^"]*\beduai-compliance-banner\b/gi) || []).length).toBe(1);
      expect(doc).toMatch(/data-eduai-palette="[a-z]+"/);
      expect(doc).toContain(EDUAI_TEMPLATE_FOOTER_LINE);
    }
    // An explicit palette pins the colours even when the type maps elsewhere.
    const pinned = wrapWithTemplate(body, { title: 'Data Handling', contentType: 'Worksheet', palette: 'certificate' });
    expect(pinned).toContain(BANNER_PALETTES.certificate.gradient);
    expect(pinned).not.toContain(BANNER_PALETTES.worksheet.gradient);
  });

  it('repaints model-authored banners in the DOCUMENT palette, not the brand pair', () => {
    const doc = wrapWithTemplate(
      '<header class="banner" style="background:#007749"><h1>Revision Cards</h1></header><p>Body.</p>',
      { title: 'Revision Cards', contentType: 'Flashcards (Term + Definition)' },
    );
    expect(doc).toContain(`--eduai-banner-gradient: ${BANNER_PALETTES.cards.gradient}`);
    expect(doc).not.toMatch(/background(-image)?:\s*linear-gradient\(180deg, #1e3a5f/);
  });
});
