import type { FoundationTemplate } from './types';
import { AWARD_FIELDS } from './shared';

/**
 * Awards for good academic achievement — Grade R–3.
 *
 * Each award is a real document (not a placeholder): a certificate body the
 * learner can be handed, plus a small follow-up learning artefact so the praise
 * keeps working after the assembly. CAPS references follow the Foundation Phase
 * reporting conventions (7-point scale in Grades 1–3, 4-level criterion-related
 * recording in Grade R).
 */
export const AWARD_TEMPLATES: FoundationTemplate[] = [
    {
        id: 'award-academic-excellence',
        kind: 'award',
        title: 'Certificate of Academic Excellence',
        subtitle: 'For outstanding achievement across the CAPS learning areas · Grades 1–3',
        blurb:
            'A bright, cartoon-bordered award for learners who achieved excellence in a subject or term, with a goal-setting strip the learner completes on receiving it.',
        grades: ['1', '2', '3'],
        learningArea: 'General',
        theme: 'sunny',
        art: 'elly-trophy',
        pages: 1,
        tags: ['term-end', 'assembly', 'parent meeting', 'Meritorious–Outstanding'],
        fields: AWARD_FIELDS,
        caps: {
            contentArea: 'Reporting and record-keeping (CAPS Foundation Phase assessment policy)',
            skills: [
                'recognising and naming achievement',
                'reflecting on own learning ("I can …")',
                'oral presentation of the award in assembly',
            ],
            terms: ['Term 1 · Week 10', 'Term 2 · Week 10', 'Term 3 · Week 10', 'Term 4 · Week 9'],
            asRef: 'SASL 1.9–1.11 — reporting to parents & record-keeping',
            blooms: ['Evaluate'],
            timeOnTask: '5 min to fill in · 10 min in assembly',
            setting: 'Assembly / award',
            marks: undefined,
            capsNote:
                'Recognition is issued against the 1–7 national rating codes: Level 7 (80–100 %) Outstanding, Level 6 (70–79 %) Meritorious, Level 5 (60–69 %) Achievement.',
        },
        blocks: [
            {
                kind: 'certificate',
                id: 'cert',
                title: 'Official award',
                awardTitle: 'Academic Excellence',
                levelRibbon: 'Level 7 · Outstanding Achievement · CAPS',
                citation:
                    'This certificate is proudly awarded to {learner} of {class} at {school} for excellent academic achievement in {term}.',
                reason: '{reason}',
                message: 'Your hard work, neat writing and careful thinking make our class proud. Keep reaching for the stars!',
                signatures: ['teacher', 'principal'],
                stickers: 5,
            },
            {
                kind: 'task',
                id: 'goals',
                title: 'My next goal — finished by the learner',
                titleXi: 'Injongo yam elandelayo',
                instruction:
                    'Colour a star for how you feel, then complete the sentences in your best handwriting before you put this certificate in your portfolio.',
                instructionLabel: 'Bhala',
                items: [
                    { text: 'The subject I am happiest in is …', lines: 1, marks: 1 },
                    { text: 'My best work this term was …', lines: 2, marks: 1 },
                    { text: 'Next term I want to get better at …', lines: 2, marks: 1 },
                    { text: 'One thing my family can help me with at home is …', lines: 2, marks: 1 },
                ],
            },
            {
                kind: 'callout',
                id: 'teacher-use',
                title: 'How to award this in class',
                tone: 'teacher',
                lines: [
                    'Print at 100 % on A4 colour (or 2 sheets per page for desk copies) and hand it over in front of the class — Foundation Phase learners need the audience.',
                    'Read the citation aloud so the whole class hears exactly which behaviour is being praised, e.g. "for excellent achievement in Mathematics".',
                    'Photograph or scan signed awards into the learner portfolio of evidence; CAPS requires records of recognition to travel with the class file.',
                    'For Grade R, record the award as a Level 4 (Fully competent) comment on the criterion-related checklist rather than a percentage.',
                ],
            },
            {
                kind: 'callout',
                id: 'inclusion',
                title: 'Inclusive education — every learner can shine',
                tone: 'inclusion',
                lines: [
                    'Learners who struggle academically can receive this certificate for a specific, observable strength (neat handwriting, helping a friend read, finishing all 5 tasks).',
                    'Read the certificate aloud and pair it with a tactile star sticker for learners with a visual impairment.',
                    'Translate the personal message into the learner\'s home language at the bottom so caregivers at the parent meeting can share the moment.',
                ],
            },
        ],
        options: { hideMemo: true },
    },
    {
        id: 'award-star-of-the-term',
        kind: 'award',
        title: 'Star of the Term Award',
        subtitle: 'Big praise with a colour-in medal · Grades R–3',
        blurb:
            'A cheerful one-page award where the learner colours in their own medal and writes why they earned it — perfect for Grade R and Grade 1 learners who cannot yet read long text.',
        grades: ['R', '1', '2', '3'],
        learningArea: 'General',
        theme: 'bubblegum',
        art: 'medal-star',
        pages: 1,
        tags: ['Grade R', 'colour-in', 'self-esteem', 'oral work'],
        fields: AWARD_FIELDS,
        caps: {
            contentArea: 'Personal and Social Well-being (self-esteem) · cross-curricular recognition',
            skills: [
                'naming own strengths',
                'listening to a certificate being read aloud',
                'colouring inside a shape (fine motor control)',
            ],
            terms: ['Term 1 · Week 10', 'Term 2 · Week 10', 'Term 3 · Week 10', 'Term 4 · Week 9'],
            asRef: 'Life Skills — Personal Well-being: "I can do things for myself"',
            blooms: ['Understand', 'Apply'],
            timeOnTask: '10 min',
            setting: 'Assembly / award',
            capsNote:
                'Grade R is recorded criterion-related: Fully competent (4) · Largely competent (3) · Partially competent (2) · Not yet competent (1). Use those words — not percentages — on Grade R awards.',
        },
        blocks: [
            {
                kind: 'certificate',
                id: 'cert',
                title: 'Our Star of the Term',
                awardTitle: 'Star of the Term',
                levelRibbon: 'I am a super learner! ⭐',
                citation: 'Yabonisa umzamo omkhulu ekilasini · Shone off with wonderful effort in class: {learner}',
                reason: '{reason}',
                message: 'We love learning with you! — {class}',
                signatures: ['teacher', 'parent'],
                stickers: 6,
            },
            {
                kind: 'colour-circle',
                id: 'medal',
                title: 'Colour my medal',
                titleXi: 'Penda imedaile yam',
                instruction: 'Colour the star gold, the ribbon pink and the circles with your favourite colours. Do not colour outside the lines!',
                actions: ['colour'],
                palette: [
                    ['gold', '#ffdf40'],
                    ['pink', '#FF69B4'],
                    ['blue', '#2563eb'],
                    ['green', '#2ed573'],
                ],
                layout: 'grid',
                items: [
                    { text: '★', caption: 'medal star' },
                    { text: '●', caption: 'left circle' },
                    { text: '●', caption: 'right circle' },
                    { text: '◆', caption: 'little diamond' },
                ],
            },
            {
                kind: 'trace',
                id: 'sentence',
                title: 'Trace and copy my praise sentence',
                instructionLabel: 'Landela emgceni',
                style: 'font',
                items: [{ model: 'I am a star!', repeats: 2 }],
                frames: ['I am good at …'],
            },
            {
                kind: 'callout',
                id: 'parent',
                title: 'Note to parents / caregivers',
                tone: 'parent',
                lines: [
                    'Please stick this award where your child can see it at home and ask them to read or tell you why they earned it.',
                    'Sign the parent line so we know the praise reached home — no extra homework is attached.',
                ],
            },
        ],
        options: { hideMemo: true },
    },
    {
        id: 'award-reading-superstar',
        kind: 'award',
        title: 'Reading Superstar Award',
        subtitle: 'Home Language · Reading and Viewing · Grades 1–3',
        blurb:
            'Certifies a learner who has grown as a reader, with a book log strip and a "tell us about it" oral prompt so the award doubles as a Reading and Viewing assessment record.',
        grades: ['1', '2', '3'],
        learningArea: 'Home Language',
        theme: 'grape',
        art: 'elly-reading',
        pages: 1,
        tags: ['reading', 'portfolio', 'oral assessment', 'book log'],
        fields: AWARD_FIELDS,
        caps: {
            contentArea: 'Reading and Viewing (independent reading for enjoyment and comprehension)',
            skills: [
                'reading agreed number of words per minute with accuracy',
                'retelling a story in the correct sequence',
                'recommending a book with a reason',
            ],
            terms: ['Term 1 · Weeks 2–10', 'Term 2 · Weeks 2–10', 'Term 3 · Weeks 2–10', 'Term 4 · Weeks 2–9'],
            asRef: 'AS 2 — reading and viewing for knowledge and enjoyment',
            blooms: ['Apply', 'Analyse', 'Evaluate'],
            timeOnTask: '12 min',
            setting: 'Assembly / award',
            marks: 10,
            capsNote:
                'CAPS Home Language Grades 1–3 requires daily informal reading plus one formal reading assessment per term; this award can carry the oral retell mark into the portfolio.',
            memo: [
                { ref: 'Log', answer: 'Any 5 titles read independently (or shared reading for struggling readers); ticks verified by the parent/caregiver.', marks: 5 },
                { ref: 'Retell', answer: 'Learner states beginning–middle–end with 3 details; 2 marks if sequence correct, 1 mark for details.', marks: 3 },
                { ref: 'Recommend', answer: 'Learner names a book and gives one clear reason (e.g. "because the taxi driver helps everybody").', marks: 2 },
            ],
        },
        blocks: [
            {
                kind: 'certificate',
                id: 'cert',
                title: 'Reading Superstar',
                awardTitle: 'Reading Superstar',
                levelRibbon: 'I read … books this term!',
                citation: 'Awarded to {learner} of {class} for wonderful progress in reading independently and for enjoying books in {term}.',
                reason: '{reason}',
                signatures: ['teacher', 'principal'],
                stickers: 4,
            },
            {
                kind: 'checklist',
                id: 'log',
                title: 'My book log — 5 stars, 5 books',
                instruction: 'Write a book you read on each star line. Ask your reader-helper (parent, teacher or friend) to tick it.',
                instructionLabel: 'Funda',
                style: 'star',
                items: [
                    'Book 1: ______________________________________________',
                    'Book 2: ______________________________________________',
                    'Book 3: ______________________________________________',
                    'Book 4: ______________________________________________',
                    'Book 5: ______________________________________________',
                ],
                footer: 'I read for ______ minutes altogether this week.',
            },
            {
                kind: 'task',
                id: 'tell',
                title: 'Tell us about your favourite book',
                instruction: 'Answer in full sentences. This becomes your oral Reading and Viewing record.',
                items: [
                    { text: 'What is the name of the book?', lines: 1, marks: 1 },
                    { text: 'Who is the main character? What is that person like?', lines: 2, marks: 3 },
                    { text: 'What happened at the END of the story?', lines: 2, marks: 3 },
                    { text: 'Would you recommend it to a friend? Why?', lines: 1, marks: 3 },
                ],
                marks: 10,
            },
            {
                kind: 'memo',
                id: 'memo',
                title: 'Oral/reading memo & marking guide',
                items: [
                    { ref: 'Log', answer: '5 titles recorded with an adult tick = 5 marks (1 per book).', marks: 5 },
                    { ref: 'Tell 1', answer: 'Any sensible title, spelt phonetically is accepted at this level.', marks: 1 },
                    { ref: 'Tell 2', answer: 'Character named (1) + 2 appropriate traits, e.g. kind, brave, helpful.', marks: 3 },
                    { ref: 'Tell 3', answer: 'Ending retold with a clear event (2) + one supporting detail (1).', marks: 3 },
                    { ref: 'Tell 4', answer: 'Recommendation with a reason = 2; recommendation only = 1.', marks: 3 },
                ],
                total: 10,
            },
        ],
    },
    {
        id: 'award-number-whiz',
        kind: 'award',
        title: 'Number Whiz Award',
        subtitle: 'Mathematics · Numbers, Operations and Relationships · Grades 1–3',
        blurb:
            'A maths-flavoured award with a quick-recall grid the learner completes in front of the class — great evidence for the weekly mental maths record.',
        grades: ['1', '2', '3'],
        learningArea: 'Mathematics',
        theme: 'lagoon',
        art: 'elly-counting',
        pages: 1,
        tags: ['mental maths', 'number bonds', 'quick recall', 'assembly'],
        fields: AWARD_FIELDS,
        caps: {
            contentArea: 'Numbers, Operations and Relationships (mental maths / rapid recall)',
            skills: [
                'number bonds and addition/subtraction facts',
                'skip counting for multiplication tables',
                'explaining a calculation strategy out loud',
            ],
            terms: ['Term 1 · Week 10', 'Term 2 · Week 10', 'Term 3 · Week 10', 'Term 4 · Week 9'],
            asRef: 'CAPS Maths mental maths: 10 minutes of every lesson',
            blooms: ['Know', 'Apply'],
            timeOnTask: '8 min',
            setting: 'Assembly / award',
            marks: 12,
            capsNote:
                'Number ranges honoured: Grade 1 to 100, Grade 2 to 200, Grade 3 to at least 1 000 with common fractions (CAPS Foundation Phase Mathematics).',
            memo: [
                { ref: 'A', answer: 'Grade 1: bonds to 10 · Grade 2: bonds to 20 · Grade 3: bonds to 100 (e.g. 65 + 35 = 100).', marks: 6 },
                { ref: 'B', answer: 'Skip counting forwards/backwards in the grade table (Gr 1: 2s, 5s, 10s · Gr 2: 2,3,4,5 · Gr 3: 6–9).', marks: 3 },
                { ref: 'C', answer: 'Learner names one strategy: counting on, doubling, building up / breaking down, or using the number line.', marks: 3 },
            ],
        },
        blocks: [
            {
                kind: 'certificate',
                id: 'cert',
                title: 'Number Whiz',
                awardTitle: 'Number Whiz',
                levelRibbon: 'Fast fingers · faster thinking! 🔢',
                citation: 'Awarded to {learner} of {class} for excellent achievement in Mathematics during {term}.',
                reason: '{reason}',
                signatures: ['teacher', 'principal'],
                stickers: 4,
            },
            {
                kind: 'grid',
                id: 'recall',
                variant: 'boxes',
                title: 'A · My lightning-round facts',
                instruction: 'Write the answer in each box. Your teacher will time you for 3 minutes.',
                instructionLabel: 'Bala',
                columns: ['1', '2', '3', '4', '5', '6'],
                rows: ['+ ?', '− ?'],
                cellSize: 14,
            },
            {
                kind: 'task',
                id: 'explain',
                title: 'B & C · Show your thinking',
                items: [
                    { text: 'Count on in your best table and write the sequence (6 numbers).', lines: 1, marks: 3 },
                    { text: 'Explain HOW you worked out 47 + 28. Use a picture, a number line or words.', lines: 3, marks: 3 },
                ],
                marks: 6,
            },
            {
                kind: 'memo',
                id: 'memo',
                title: 'Mental maths memo',
                items: [
                    { ref: 'A', answer: 'Any 6 correct facts within the grade range = 6 marks (½ mark each is not used; 1 mark each).', marks: 6 },
                    { ref: 'B', answer: 'Correct sequence with a constant difference, e.g. 6; 12; 18; 24; 30; 36.', marks: 3 },
                    { ref: 'C', answer: 'Accept 47 + 28 = 47 + 30 − 2 = 75, or number-line jumps, or 40 + 20 = 60, 7 + 8 = 15, 60 + 15 = 75.', marks: 3 },
                ],
                total: 12,
            },
        ],
    },
    {
        id: 'award-praise-slips',
        kind: 'award',
        title: 'Cut-out Praise Slips & Sticker Awards',
        subtitle: '4 slips per page · daily recognition for Grades R–3',
        blurb:
            'A strip of four card-sized praise slips (behaviour, effort, kindness, maths) to cut out, fill in and hand over instantly, each with a sticker circle and a parent signature line.',
        grades: ['R', '1', '2', '3'],
        learningArea: 'General',
        theme: 'tangerine',
        art: 'sticker-sheet',
        pages: 1,
        tags: ['daily', 'behaviour', 'sticker', 'cut-out'],
        fields: AWARD_FIELDS,
        caps: {
            contentArea: 'Social Well-being (classroom conduct) · informal daily assessment record',
            skills: ['recognising specific positive behaviour', 'sticking and writing a reason', 'taking praise home to a caregiver'],
            terms: ['Term 1 · Weeks 1–10', 'Term 2 · Weeks 1–10', 'Term 3 · Weeks 1–10', 'Term 4 · Weeks 1–9'],
            asRef: 'Informal / daily checks (CAPS Foundation Phase programme of assessment)',
            blooms: ['Understand', 'Evaluate'],
            timeOnTask: '1 min per slip',
            setting: 'Classroom',
            capsNote:
                'Informal assessment is recorded daily in Grade 1 and weekly in Grades 2–3. Praise slips are a legitimate, quick record of social and academic behaviour for the class file.',
        },
        blocks: [
            {
                kind: 'cards',
                id: 'slips',
                title: 'Print, cut and hand out',
                instruction:
                    'Print on A4 card, cut on the dashed lines, fill in the learner\'s name and the reason. Learners stick the slip into their homework diary or take it home.',
                instructionLabel: 'Sika · Namathisela',
                perRow: 1,
                cut: 'dashed',
                cardFields: [
                    { label: 'Awarded to' },
                    { label: 'Because' },
                    { label: 'Teacher' },
                    { label: 'Parent sign' },
                ],
                cards: [
                    { face: '⭐ STAR EFFORT', caption: 'You never gave up on a single question.', symbol: '💪', note: 'Level: effort · record in the class file' },
                    { face: '🧮 MATHS MASTER', caption: 'Your number work is neat and correct.', symbol: '➕', note: 'Level: academic · Mathematics' },
                    { face: '📚 SUPER READER', caption: 'You read aloud with expression and confidence.', symbol: '📖', note: 'Level: academic · Home Language' },
                    { face: '🤝 KIND FRIEND', caption: 'You helped a classmate and made our class safe.', symbol: '💛', note: 'Level: social well-being' },
                ],
            },
            {
                kind: 'reward',
                id: 'sticker',
                title: 'My sticker tracker — 10 slips, 10 stickers',
                instruction: 'Stick one sticker in each circle. When the row is full, choose a class prize (5 minutes outside, line leader, or a book to take home).',
                praise: ['Every slip you earn is proof that you are learning!', 'Tick each sticker as it lands so nobody argues later.'],
                slots: 10,
            },
            {
                kind: 'callout',
                id: 'tip',
                title: 'Teaching tip — praise the work, not the child',
                tone: 'tip',
                lines: [
                    'Name the behaviour ("you checked your subtraction by adding back") so other learners copy the strategy, not just the result.',
                    'Give every learner at least one slip per fortnight; in Foundation Phase the fastest learners soak up all the airtime.',
                    'For Grade R, pair the slip with a stamp on the hand — the paper alone means very little at that age.',
                ],
            },
        ],
        options: { hideMemo: true },
    },
    {
        id: 'award-effort-improvement',
        kind: 'award',
        title: 'Brilliant Effort & Improvement Award',
        subtitle: 'Big jumps in marks, not only top marks · Grades R–3',
        blurb:
            'The award that keeps learners motivated: recognises the biggest improvement in a learning area, with a before/after marks box and a self-talk strip.',
        grades: ['R', '1', '2', '3'],
        learningArea: 'General',
        theme: 'meadow',
        art: 'doodle-supplies',
        pages: 1,
        tags: ['motivation', 'growth mindset', 'improvement', 'parent meeting'],
        fields: AWARD_FIELDS,
        caps: {
            contentArea: 'Progress tracking & reporting (CAPS record-keeping)',
            skills: ['comparing own work over time', 'identifying what helped', 'setting one achievable target'],
            terms: ['Term 2 · Week 10', 'Term 3 · Week 10', 'Term 4 · Week 9'],
            asRef: 'SASL — progress must be tracked and reported, not only ranked',
            blooms: ['Analyse', 'Evaluate'],
            timeOnTask: '8 min',
            setting: 'Assembly / award',
            capsNote:
                'Award the biggest gain per rating level (e.g. from Level 2 Elementary to Level 4 Competent), so learners who are not top of the class still compete for it.',
        },
        blocks: [
            {
                kind: 'certificate',
                id: 'cert',
                title: 'Brilliant Effort',
                awardTitle: 'Brilliant Effort & Improvement',
                levelRibbon: 'Look how far you have come! 🌱',
                citation: 'Presented to {learner} of {class} for the biggest improvement in {reason} between {term} and the end of term.',
                reason: '{reason}',
                signatures: ['teacher', 'principal', 'parent'],
                stickers: 3,
            },
            {
                kind: 'task',
                id: 'compare',
                title: 'My learning journey',
                instruction: 'Complete the boxes with your own marks, then finish the sentences.',
                items: [
                    { text: 'Earlier this year I scored … marks out of …', lines: 1, marks: 1 },
                    { text: 'Now I score … marks out of …', lines: 1, marks: 1 },
                    { text: 'What helped me improve? (Tick 2)', options: ['extra practice at home', 'listening in class', 'reading every night', 'asking for help', 'checking my work', 'my study buddy'], lines: 1, marks: 2 },
                    { text: 'My target for next term is …', lines: 2, marks: 2 },
                ],
                marks: 6,
            },
            {
                kind: 'callout',
                id: 'parent',
                title: 'Note to parents / caregivers',
                tone: 'parent',
                lines: [
                    'Improvement is the strongest predictor of later school success — please celebrate this award as loudly as a top mark.',
                    'Ten minutes of reading or number talk at home, four times a week, is enough to keep this curve going.',
                ],
            },
        ],
        options: { hideMemo: true },
    },
];

export default AWARD_TEMPLATES;
