import type { FoundationTemplate } from './types';
import { CLASSROOM_FIELDS } from './shared';

/**
 * Classroom exercises — oral, pair, group, card-game and movement work.
 *
 * These are the daily-programme activities CAPS expects in the Foundation
 * Phase: 20–30 minutes of guided, mostly ORAL work where the teacher
 * facilitates and records on a checklist. Everything is printable as cut-out
 * cards or a station circuit, so a teacher can run it with no projector.
 */
export const CLASSROOM_TEMPLATES: FoundationTemplate[] = [
    {
        id: 'ce-grR-phonics-sound-bingo',
        kind: 'classroom',
        title: 'Sound Bingo — Initial Letter Game',
        subtitle: 'Home Language Grade R · Phonics & Print Awareness · whole-class game',
        blurb:
            'A 4-round listening game with cut-out bingo boards, caller cards and movement breaks, so Grade R learners hear a sound, find the picture and jump up when they get a line.',
        grades: ['R', '1'],
        learningArea: 'Home Language',
        theme: 'bubblegum',
        art: 'kids-classroom',
        pages: 1,
        tags: ['game', 'oral', 'listening', 'no prep'],
        fields: CLASSROOM_FIELDS,
        caps: {
            contentArea: 'Phonics and Print Awareness · Listening and Speaking',
            skills: [
                'identify the initial sound in a familiar word',
                'listen to a spoken cue and respond by pointing / moving',
                'say the word aloud for the class to check',
            ],
            terms: ['Term 1 · Weeks 3–10', 'Term 2 · Weeks 1–5'],
            asRef: 'HL Gr R: listening & speaking + phonics (oral, not written, assessment)',
            blooms: ['Know', 'Understand', 'Apply'],
            timeOnTask: '20 min (4 rounds × 4 min + 4 min wrap-up)',
            setting: 'Classroom',
            capsNote:
                'CAPS Foundation Phase language teaching is daily and mostly oral in Grade R; games like this are legitimate teaching time, not "free time".',
        },
        blocks: [
            {
                kind: 'callout',
                id: 'howto',
                title: 'How to run the game (teacher script)',
                tone: 'teacher',
                lines: [
                    'Seat learners in a circle on the rug with one board each. Give every learner a handful of beans, bottle caps or pebbles as counters.',
                    'Say the sound, then the word, then the sound again: "/m/ … moon … /m/". Learners hunt for the moon picture and cover it.',
                    'First learner to cover 3 in a line shouts "BINGO!" and must say all three words to win the round.',
                    'Round 4 is the movement round: instead of covering, learners hop like a frog to the letter card taped on the wall.',
                    'Record names on the class checklist as they win — this is your weekly oral assessment evidence.',
                ],
            },
            {
                kind: 'cards',
                id: 'caller',
                title: 'Caller cards — cut out and shuffle',
                instruction: 'Print, cut and put the cards in a little bag. Pick one, say the FIRST SOUND clearly, then the word.',
                instructionLabel: 'Phulaphula · Thetha',
                perRow: 4,
                cut: 'dashed',
                cards: [
                    { face: '/m/', caption: 'moon 🌙', symbol: '🌙', note: 'm · m · moon' },
                    { face: '/s/', caption: 'sun ☀️', symbol: '☀️', note: 's · s · sun' },
                    { face: '/a/', caption: 'ant 🐜', symbol: '🐜', note: 'a · a · ant' },
                    { face: '/t/', caption: 'table 🪑', symbol: '🪑', note: 't · t · table' },
                    { face: '/p/', caption: 'pan 🍳', symbol: '🍳', note: 'p · p · pan' },
                    { face: '/b/', caption: 'ball ⚽', symbol: '⚽', note: 'b · b · ball' },
                    { face: '/d/', caption: 'dog 🐶', symbol: '🐶', note: 'd · d · dog' },
                    { face: '/f/', caption: 'fish 🐟', symbol: '🐟', note: 'f · f · fish' },
                ],
            },
            {
                kind: 'cards',
                id: 'boards',
                title: 'Player boards — 4 squares each (print 8 copies)',
                perRow: 4,
                cut: 'scalloped',
                cards: [
                    { face: '🌙  ☀️  🐜  🪑', caption: 'Board A' },
                    { face: '🍳    🐶  ', caption: 'Board B' },
                    { face: '🌙  🐶  🍳  ', caption: 'Board C' },
                    { face: '☀️  🪑    🐜', caption: 'Board D' },
                ],
            },
            {
                kind: 'movement',
                id: 'move',
                title: 'Round 4 · Hop to the sound',
                instruction: 'Stand up. Listen to the sound on the caller card and hop to the matching letter taped on the wall.',
                space: 'Clear rug area · 4 letter cards taped at low height',
                steps: [
                    { text: 'Teacher shows a letter card and says the sound.', symbol: '🅰️', reps: 'whole class' },
                    { text: 'Learners hop like a frog to the wall with that letter.', symbol: '🐸', reps: '× 4 letters' },
                    { text: 'Everyone claps the sound 3 times together.', symbol: '👏', reps: '3 claps' },
                    { text: 'Sit down slowly, hands up, ready for the next card.', symbol: '🪑', reps: 'calm down' },
                ],
            },
            {
                kind: 'checklist',
                id: 'record',
                title: 'Oral assessment checklist (record as they play)',
                instruction: 'Tick when the learner identifies the sound WITHOUT looking at a friend. Note names of learners to re-teach tomorrow.',
                items: [
                    'Hears /m/ and points to moon — ____ learners',
                    'Hears /s/ and points to sun — ____ learners',
                    'Produces the initial sound when shown a picture — ____ learners',
                    'Needs re-teaching tomorrow (names): ______________________',
                ],
                footer: 'To re-teach: repeat rounds 1–2 with only 2 letters, then re-test on the mat tomorrow.',
            },
            {
                kind: 'callout',
                id: 'inclusion',
                title: 'Barriers to learning — adaptations',
                tone: 'inclusion',
                lines: [
                    'Hearing impairment: hold the picture card facing the learner and use an exaggerated mouth shape; pair them with a buddy who says the word.',
                    'Learners with poor motor control: use large foam counters, or let the learner point instead of covering.',
                    'Anxious learners: give them the caller job for one round — hearing the sound from the front of the room builds confidence fast.',
                ],
            },
        ],
        options: { hideMemo: true },
    },
    {
        id: 'ce-gr1-2-hl-picture-talk-pairs',
        kind: 'classroom',
        title: 'Pair Talk: Describe the Picture',
        subtitle: 'Home Language Grades 1–2 · Listening & Speaking · structured talk frames',
        blurb:
            'Turn-and-talk cards with sentence frames so every learner speaks for 2 minutes at a time, plus a listening job for the partner and a teacher tick-list.',
        grades: ['1', '2'],
        learningArea: 'Home Language',
        theme: 'sunny',
        art: 'elly-reading',
        pages: 1,
        tags: ['oral', 'pair work', 'talk frames', 'speaking'],
        fields: CLASSROOM_FIELDS,
        caps: {
            contentArea: 'Listening and Speaking (conversation, describing, answering in full sentences)',
            skills: [
                'speak audibly about a picture for 3–5 sentences',
                'answer a partner\'s question in a full sentence',
                'listen without interrupting and add one idea',
            ],
            terms: ['Term 1 · Weeks 4–8', 'Term 3 · Weeks 2–6'],
            asRef: 'AS 1 — learning through listening, speaking, discussing',
            blooms: ['Understand', 'Apply', 'Analyse'],
            timeOnTask: '15 min pairs + 5 min class share',
            setting: 'Classroom',
            marks: 10,
            capsNote:
                'CAPS expects oral work to be planned, not incidental: give talk time, then record achievement against 3 simple criteria.',
            memo: [
                { ref: 'Speak', answer: '3+ sentences about the picture with 2 details (who, what, where) = 4 marks.', marks: 4 },
                { ref: 'Answer', answer: 'Full-sentence answer to the partner\'s question = 3 marks.', marks: 3 },
                { ref: 'Listen', answer: 'Did not interrupt + added one idea = 3 marks.', marks: 3 },
            ],
        },
        blocks: [
            {
                kind: 'cards',
                id: 'prompt',
                title: 'Talk cards — one per pair, cut out',
                instruction: 'Partner A talks for 1 minute. Partner B listens and ticks. Then swap.',
                perRow: 3,
                cards: [
                    { face: '🌧️', caption: 'A rainy day outside the school' },
                    { face: '', caption: 'A family eating together at home' },
                    { face: '🦒', caption: 'Animals at the zoo on a school trip' },
                    { face: '🚐', caption: 'The busy taxi rank in the morning' },
                    { face: '🎂', caption: 'A birthday party in the hall' },
                    { face: '📚', caption: 'Reading in the library corner' },
                ],
            },
            {
                kind: 'oral-pairs',
                id: 'frames',
                title: 'Talk frames (keep these on the table)',
                frames: [
                    'I can see ______.',
                    'The ______ is ______ing.',
                    'I think they feel ______ because ______.',
                    'This reminds me of ______.',
                ],
                prompts: [
                    'What is happening in the picture?',
                    'Who is in the picture?',
                    'What sound can you hear?',
                    'What would happen next?',
                    'Do you like it? Why?',
                ],
                listenFor: 'Tick when your partner says a FULL sentence and gives you ONE reason.',
            },
            {
                kind: 'task',
                id: 'record',
                title: 'Switch roles, then write it',
                instruction: 'Now Partner B talks. Afterwards, each learner writes the best sentence they heard from their partner.',
                items: [
                    { text: 'My partner said: ______________________________________________', lines: 1, marks: 2 },
                    { text: 'One thing I would add to the picture:', lines: 2, marks: 2 },
                ],
                marks: 4,
            },
            {
                kind: 'rubric',
                id: 'rubric',
                title: 'Oral assessment grid (mark while you circulate)',
                criteria: ['Speaks clearly', 'Uses full sentences', 'Adds detail/reason', 'Listens to partner'],
                levels: ['4 · Fully competent', '3 · Largely competent', '2 · Partially competent', '1 · Not yet competent'],
                cells: [
                    ['Audible to the whole group', 'Audible to partner only', 'Mumbles, needs prompting', 'Will not speak yet'],
                    ['All answers full sentences', 'Mostly full sentences', 'Single words / phrases', 'Points only'],
                    ['2+ details and a reason', 'One detail', 'Repeats the question', 'No detail'],
                    ['Waits, responds, adds an idea', 'Waits then answers', 'Interrupts', 'Withdraws / distracted'],
                ],
            },
            {
                kind: 'callout',
                id: 'tip',
                title: 'Teaching tip',
                tone: 'tip',
                lines: [
                    'Use a "talk token" (a bottle cap) — the learner holding it is the only one allowed to speak. It stops the loudest child owning every pair.',
                    'Model one terrible answer and one good answer first; Foundation Phase learners need the contrast.',
                    'Mark only 6 learners per day on the grid — a full class cycle takes 4 days, which is exactly the CAPS weekly oral programme.',
                ],
            },
        ],
    },
    {
        id: 'ce-gr1-3-maths-estimation-circuit',
        kind: 'classroom',
        title: 'Estimation Station Circuit',
        blurb: 'Six hands-on estimation stations with a class record sheet and a bar graph to build together — Mathematics for Grades 1–3, one session.',
        subtitle: 'Mathematics Grades 1–3 · Data Handling + Measurement · group circuit',
        grades: ['1', '2', '3'],
        learningArea: 'Mathematics',
        theme: 'meadow',
        art: 'doodle-supplies',
        pages: 2,
        tags: ['stations', 'estimation', 'data handling', 'group work'],
        fields: CLASSROOM_FIELDS,
        caps: {
            contentArea: 'Data Handling (Statistics) · Measurement · Numbers, Operations and Relationships',
            skills: [
                'estimate, then count to check, and say "more than / less than / about"',
                'collect, sort and record data in a table and a picture graph',
                'measure length with non-standard and standard units',
            ],
            terms: ['Term 2 · Weeks 5–8', 'Term 4 · Weeks 2–5'],
            asRef: 'CAPS Maths Data Handling weighting: Gr 1 5 % · Gr 2 5 % · Gr 3 5 %',
            blooms: ['Understand', 'Apply', 'Analyse'],
            timeOnTask: '40 min (6 stations × 5 min + 10 min graph)',
            setting: 'Classroom',
            marks: 12,
            capsNote:
                'Measurement is 9 % (Gr 1), 12 % (Gr 2) and 14 % (Gr 3) of the Mathematics programme; estimation is the CAPS-recommended entry point before formal measuring.',
            memo: [
                { ref: 'Stations', answer: 'Estimate within ±20 % for 2 marks each group; exact count correct = 1 mark.', marks: 6 },
                { ref: 'Graph', answer: 'Bars/pictures aligned to the grid + title + labels = 3 marks; answers read from graph = 3 marks.', marks: 6 },
            ],
        },
        blocks: [
            {
                kind: 'cards',
                id: 'stations',
                title: 'Station cards — print, cut, place on 6 tables',
                perRow: 3,
                cut: 'scalloped',
                cards: [
                    { face: '1️⃣ JARS', caption: 'How many marbles in the jar? Estimate · then count.', symbol: '🫙', note: 'Answer within ±20 % = 2 marks' },
                    { face: '2️⃣ HAND SPANS', caption: 'How many hand spans is the table? Estimate · then measure.', symbol: '🖐️', note: 'Record both numbers' },
                    { face: '3️⃣ BEANS', caption: 'Take 15 beans in one handful. Did you get close?', symbol: '🫘', note: 'Count and say more/less' },
                    { face: '4️⃣ PAVERS', caption: 'How many steps to the gate? Estimate · walk it.', symbol: '👟', note: 'Compare with a partner' },
                    { face: '5️⃣ SPOTTERS', caption: 'How many learners wear shoes with lights? Guess · then count.', symbol: '👞', note: 'Feeds the class graph' },
                    { face: '6️⃣ PENCILS', caption: 'Which pencil is longer? Guess · then line them up.', symbol: '✏️', note: 'Use the same starting point' },
                ],
            },
            {
                kind: 'grid',
                id: 'record',
                title: 'A · My estimation record sheet',
                columns: ['My estimate', 'Actual count', 'More than / less than / exact', 'Difference'],
                rows: ['1 Jar', '2 Hand spans', '3 Beans', '4 Steps', '5 Shoes', '6 Pencils'],
                marks: 6,
            },
            {
                kind: 'data-table',
                id: 'graph',
                title: 'B · Build the class graph on the chalkboard',
                headers: ['Item', 'Number of learners', 'Picture graph'],
                rows: [
                    ['👟 Shoes with lights', '', ''],
                    ['🎽 Red jerseys', '', ''],
                    [' School shirts', '', ''],
                    ['🧢 Caps', '', ''],
                ],
                pictogram: '🟢',
                questions: [
                    { text: 'Which was the MOST popular? How do you know?', lines: 1, marks: 1 },
                    { text: 'How many MORE learners chose school shirts than caps?', lines: 1, marks: 1 },
                    { text: 'Write a question for a partner to answer from this graph.', lines: 2, marks: 1 },
                ],
                marks: 6,
            },
            {
                kind: 'movement',
                id: 'rotate',
                title: 'Rotating the circuit (keep it tight!)',
                instruction: 'Blow the whistle every 5 minutes. Two groups may swap places while walking — that is your transition time.',
                space: '6 tables or floor spots around the room',
                steps: [
                    { text: 'Groups of 4 sit at their station. One "Reader", one "Recorder", one "Counter", one "Reporter".', symbol: '👥' },
                    { text: 'Estimate FIRST — no counting allowed until the estimate is written.', symbol: '🤔', reps: '1 min' },
                    { text: 'Count / measure and record.', symbol: '📏', reps: '3 min' },
                    { text: 'Whistle → move one table to the right.', symbol: '', reps: '30 sec' },
                    { text: 'Reporters share their surprise result with the class.', symbol: '🎤', reps: '5 min' },
                ],
            },
            {
                kind: 'callout',
                id: 'tip',
                title: 'Teaching tip — estimation talk',
                tone: 'tip',
                lines: [
                    'Refuse "I don\'t know": the rule is "give a number that is not zero". Confidence first, accuracy second.',
                    'Grade 1 records with a tally and a number only; Grade 3 adds the "difference" column — same sheet, different demand.',
                    'Reuse the class graph data for the next week\'s informal Data Handling task — CAPS wants the same data revisited.',
                ],
            },
            { kind: 'memo', id: 'memo', title: 'Memo / what to look for', items: [], total: 12 },
        ],
    },
    {
        id: 'ce-gr2-3-social-then-and-now',
        kind: 'classroom',
        title: 'Then and Now — Sorting the Past',
        subtitle: 'Life Skills · Beginning Knowledge (Social Sciences) · Grades 2–3',
        blurb:
            'Cut-out "then / now" picture-and-word cards, a timeline the class builds together, and interview questions learners ask a grandparent at home.',
        grades: ['2', '3'],
        learningArea: 'Life Skills — Beginning Knowledge',
        theme: 'tangerine',
        art: 'rainbow-banner',
        pages: 1,
        tags: ['history', 'sorting', 'timeline', 'family interview'],
        fields: CLASSROOM_FIELDS,
        caps: {
            contentArea: 'Beginning Knowledge — Social Sciences: my community and its history (then vs now)',
            skills: [
                'sort objects and pictures into then and now',
                'place 3 events in the correct sequence using "before, after, last"',
                'ask a grandparent or older community member one question and report the answer',
            ],
            terms: ['Term 1 · Weeks 5–8', 'Term 3 · Weeks 3–5'],
            asRef: 'CAPS LS Gr 2–3 Beginning Knowledge: past and present, my family, my community',
            blooms: ['Know', 'Understand', 'Analyse'],
            timeOnTask: '30 min + home interview',
            setting: 'Classroom',
            marks: 10,
            capsNote:
                'Social Sciences content in the Foundation Phase lives inside Beginning Knowledge; CAPS asks for local, personal history first (family, school, community) before national events.',
            memo: [
                { ref: 'Sort', answer: 'Then: candle, paraffin lamp, mortar & pestle, donkey cart, postal letter. Now: electric stove, blender, car, email/phone. Accept 10 correct sorts.', marks: 4 },
                { ref: 'Sequence', answer: '1 Grandmother was born → 2 She started school → 3 She finished school → 4 My mother was born → 5 I started Grade 2. (Any 3 in order = 3 marks.)', marks: 3 },
                { ref: 'Interview', answer: 'Question written + answer reported in own words + name of person asked = 3 marks.', marks: 3 },
            ],
        },
        blocks: [
            {
                kind: 'cards',
                id: 'sort',
                title: 'Sort cards — then · now',
                instruction: 'Cut out the cards. In your group, place each card on the THEN side or the NOW side of the string on the table. Stick one on each side of your book.',
                instructionLabel: 'Hlela · Sika',
                perRow: 4,
                cards: [
                    { face: '🕯️', caption: 'candle light' },
                    { face: '💡', caption: 'electric lamp' },
                    { face: '🪣', caption: 'water from the river' },
                    { face: '🚰', caption: 'tap in the kitchen' },
                    { face: '🥣', caption: 'mortar & pestle' },
                    { face: '🔌', caption: 'electric blender' },
                    { face: '🫏', caption: 'donkey cart' },
                    { face: '🚚', caption: 'delivery truck' },
                ],
            },
            {
                kind: 'task',
                id: 'sequence',
                title: 'A · Put these in order (1 = first, 5 = last)',
                instruction: 'Number the events in the correct order. Then answer: how do we know what happened first?',
                items: [
                    {
                        text: 'My grandmother finished school · My mother was born · My grandmother was born · I started Grade 2 · My mother started work',
                        lines: 2,
                        marks: 3,
                    },
                    { text: 'How did you know which came first? Write your clue.', lines: 2, marks: 1 },
                ],
                marks: 4,
            },
            {
                kind: 'checklist',
                id: 'interview',
                title: 'B · Ask a grandparent or an older neighbour tonight',
                style: 'heart',
                items: [
                    'What did you walk to school on? ______________________',
                    'What games did you play outside? ______________________',
                    'What food did your family eat on Sundays? ______________',
                    'What did you NOT have at my age? ______________________',
                ],
                footer: 'Tell the class tomorrow in 2 sentences. Who you asked: ____________________',
                marks: 3,
            },
            {
                kind: 'callout',
                id: 'inclusion',
                title: 'Inclusive education',
                tone: 'inclusion',
                lines: [
                    'Some learners live with grandparents or in child-headed households — never assume a parent is available; the interviewer may be any older person.',
                    'For learners who cannot write, allow a drawn timeline and an oral report recorded on the teacher\'s phone.',
                    'Avoid romanticising poverty: CAPS Social Sciences in the Foundation Phase is about change and fairness, so ask "who had to fetch water, and how has that changed for your family?"',
                ],
            },
            { kind: 'memo', id: 'memo', title: 'Memo', items: [], total: 10 },
        ],
    },
    {
        id: 'ce-grR-2-pe-movement-patterns',
        kind: 'classroom',
        title: 'Movement Patterns & Rhythm Game',
        subtitle: 'Life Skills · Creative Arts + Physical Education · Grades R–2',
        blurb:
            'Copy-the-leader rhythm and movement patterns using a picture-card sequence, with a 4-level observation rubric for the PE and Creative Arts marks.',
        grades: ['R', '1', '2'],
        learningArea: 'Life Skills — Physical Education',
        theme: 'lagoon',
        art: 'elly-nature',
        pages: 1,
        tags: ['PE', 'dance', 'rhythm', 'rubric', 'outdoor'],
        fields: CLASSROOM_FIELDS,
        caps: {
            contentArea: 'Creative Arts (Movement and Dance · Music) + Physical Education (movement skills)',
            skills: [
                'copy a 2–4 step movement pattern',
                'move to a steady beat / rhythm with the group',
                'create and lead their own 2-step pattern',
            ],
            terms: ['Term 1 · Weeks 2–10 (2 h per week allocation)', 'Term 3 · Weeks 1–6'],
            asRef: 'CAPS LS: Creative Arts 2 h/week · Physical Education 2 h/week',
            blooms: ['Apply', 'Evaluate'],
            timeOnTask: '25 min on the field or clear floor',
            setting: 'Classroom',
            marks: 8,
            capsNote:
                'Movement and Dance is assessed on performing AND creating; a rubric like this is the standard Foundation Phase record.',
            memo: [
                { ref: 'Copy', answer: 'Copies 3 of 4 steps correctly in sequence = 2 marks; rhythm maintained = 1 mark.', marks: 3 },
                { ref: 'Group', answer: 'Moves safely in space without collisions, keeps the beat = 2 marks.', marks: 2 },
                { ref: 'Create', answer: 'Own 2-step pattern, performed and repeatable by the class = 3 marks.', marks: 3 },
            ],
        },
        blocks: [
            {
                kind: 'movement',
                id: 'warmup',
                title: 'Warm-up · 3 minutes',
                instruction: 'Everybody in a circle, arms wide. Never touch a friend — space first, then moves.',
                space: 'Hall, field or desks pushed back',
                steps: [
                    { text: 'March on the spot, tall steps, arms swinging.', symbol: '🚶', reps: '× 8 counts' },
                    { text: 'Tip-toe quietly like a cat, then heavy feet like an elephant.', symbol: '🐘', reps: '× 6' },
                    { text: 'Shake the right hand 4 times, left hand 4 times, then freeze.', symbol: '🧊', reps: '× 2' },
                    { text: 'Breatve in through the nose for 4, out like a candle for 4.', symbol: '🌬️', reps: '× 3' },
                ],
            },
            {
                kind: 'cards',
                id: 'pattern',
                title: 'Pattern cards — the leader shows one card, the class copies',
                perRow: 4,
                cut: 'dashed',
                cards: [
                    { face: '👏👏', caption: 'clap · clap' },
                    { face: '🦵', caption: 'stomp right foot' },
                    { face: '🙆', caption: 'arms up, stretch tall' },
                    { face: '🌀', caption: 'turn around once' },
                    { face: '🐰', caption: '2 bunny hops' },
                    { face: '🤸', caption: 'touch toes' },
                    { face: '🕺', caption: 'slide left · slide right' },
                    { face: '🧍', caption: 'freeze like a statue' },
                ],
            },
            {
                kind: 'task',
                id: 'sequence-task',
                title: 'A · Our 4-step pattern',
                instruction: 'In your group, choose 4 cards, put them in order, stick them down and perform the pattern to the class with the drum beat.',
                items: [
                    { text: 'Write the numbers of the cards we chose (e.g. 2, 7, 1, 8):', lines: 1, marks: 2 },
                    { text: 'Draw our pattern in the 4 boxes below.', lines: 4, marks: 1 },
                    { text: 'Which step was hardest? What did you do to get it right?', lines: 2, marks: 1 },
                ],
                marks: 4,
            },
            {
                kind: 'rubric',
                id: 'rubric',
                title: 'Observation rubric (mark during the performance)',
                criteria: ['Copies the pattern', 'Moves to the beat', 'Safety & space', 'Creates & leads'],
                levels: ['4 · Fully competent', '3 · Largely competent', '2 · Partially competent', '1 · Not yet competent'],
                cells: [
                    ['Performs all 4 steps in order', '3 of 4 steps in order', '1–2 steps, needs prompting', 'Watches only'],
                    ['Stays on the beat all round', 'Mostly on the beat', 'Off beat, joins in late', 'Does not move to the beat'],
                    ['Keeps space, no collisions', 'Occasional bump, self-corrects', 'Needs reminders to stay apart', 'Unsafe / runs off'],
                    ['Leads own pattern, class copies', 'Own pattern needs 1 prompt', 'Copies only, cannot lead', 'Refuses to lead'],
                ],
            },
            {
                kind: 'callout',
                id: 'safety',
                title: 'Safety & inclusion',
                tone: 'safety',
                lines: [
                    'Shoes tied, jewellery removed, space checked for bag straps before any movement starts.',
                    'A learner in a wheelchair or with a physical disability chooses the 4-step pattern for their own body — the class then copies THAT pattern. This is CAPS-aligned, not a favour.',
                    'No learner is made to perform in front of the class; groups perform together so nobody stands alone.',
                ],
            },
            { kind: 'memo', id: 'memo', title: 'Marks to record', items: [], total: 8 },
        ],
    },
    {
        id: 'ce-gr2-3-guided-reading-roles',
        kind: 'classroom',
        title: 'Guided Reading Table — Role Cards',
        subtitle: 'Home Language Grades 2–3 · Reading & Viewing · 5-role guided reading group',
        blurb:
            'Sixteen minutes at the teacher\'s table with role cards (Reader, Word Catcher, Question Maker, Reteller, Recorder, Checker) plus a text-dependant question strip.',
        grades: ['2', '3'],
        learningArea: 'Home Language',
        theme: 'grape',
        art: 'elly-reading',
        pages: 1,
        tags: ['guided reading', 'roles', 'comprehension', 'small group'],
        fields: CLASSROOM_FIELDS,
        caps: {
            contentArea: 'Reading and Viewing · Listening and Speaking (supported/group reading)',
            skills: [
                'read a familiar text aloud with accuracy, pace and expression',
                'decode an unfamiliar word using context and letter-sound knowledge',
                'ask and answer literal and inferential questions about the text',
                'retell in sequence without looking at the text',
            ],
            terms: ['Term 1 – Term 4 · 3 sessions per week per group'],
            asRef: 'AS 2 & AS 4 — reading & viewing, language structures in context',
            blooms: ['Understand', 'Apply', 'Analyse', 'Evaluate'],
            timeOnTask: '16 min per group of 5–6',
            setting: 'Guided reading / group table',
            marks: 12,
            capsNote:
                'Home Language timetables allocate daily reading and viewing time; a guided group of 5–6 for 15–20 minutes is the CAPS-recommended structure in Grades 2–3.',
            memo: [
                { ref: 'Read', answer: '≥95 % accuracy for Gr 3 / ≥90 % for Gr 2 at 60+ wpm, with phrasing = 4 marks.', marks: 4 },
                { ref: 'Words', answer: '3 tricky words decoded and re-read in the sentence = 2 marks.', marks: 2 },
                { ref: 'Q&A', answer: '2 literal answers in full sentences (2) + 1 inference with text evidence (2) = 4 marks.', marks: 4 },
                { ref: 'Retell', answer: 'Beginning–middle–end, 3 events in order = 2 marks.', marks: 2 },
            ],
        },
        blocks: [
            {
                kind: 'cards',
                id: 'roles',
                title: 'Role cards — laminate once, use all year',
                perRow: 3,
                cut: 'scalloped',
                cards: [
                    { face: 'READER', caption: 'Reads first. Finger under the words, voice loud enough for the table.', symbol: '📖' },
                    { face: 'WORD CATCHER', caption: 'Stops on a tricky word. Asks: what sound? what would make sense?', symbol: '🔍' },
                    { face: 'QUESTION MAKER', caption: 'Must ask ONE question that is not answered in the first line.', symbol: '❓' },
                    { face: 'RETELLER', caption: 'Tells the story without looking: first … then … last.', symbol: '🗣️' },
                    { face: 'RECORDER', caption: 'Writes the group answer on the sheet in the neatest handwriting.', symbol: '✍️' },
                    { face: 'CHECKER', caption: 'Checks punctuation and that every answer is a FULL sentence.', symbol: '✅' },
                ],
            },
            {
                kind: 'task',
                id: 'questions',
                title: 'Question strip for any text (teacher asks, group answers)',
                instruction: 'Choose 4 questions. Put a tick next to the ones the group answered in full sentences.',
                items: [
                    { text: 'What is the text mostly about?', lines: 1, marks: 1 },
                    { text: 'Find the word that tells us how the character felt. What made you choose it?', lines: 2, marks: 2 },
                    { text: 'What do you think will happen next? Why?', lines: 2, marks: 2 },
                    { text: 'Which sentence is your favourite? Read it to us with feeling.', lines: 1, marks: 1 },
                    { text: 'Is the character right or wrong? Tell me your reason.', lines: 2, marks: 2 },
                ],
                marks: 8,
            },
            {
                kind: 'checklist',
                id: 'log',
                title: 'Weekly guided-reading log (5 groups a week)',
                items: [
                    'Mon · Group 1 (names): ____________________  ✔ read ✔ decode ✔ answer ✔ retell',
                    'Tue · Group 2 (names): ____________________  ✔ read ✔ decode ✔ answer ✔ retell',
                    'Wed · Group 3 (names): ____________________  ✔ read ✔ decode ✔ answer ✔ retell',
                    'Thu · Group 4 (names): ____________________  ✔ read ✔ decode ✔ answer ✔ retell',
                    'Fri · Group 5 / re-teach group: ____________  ✔ read ✔ decode ✔ answer ✔ retell',
                ],
                footer: 'Text used / title: ______________________________  Level: ____________',
            },
            {
                kind: 'callout',
                id: 'tip',
                title: 'Teaching tip — text selection',
                tone: 'tip',
                lines: [
                    'Rotate three texts: one at frustration level (taught by you), one at instructional level (the group), one independent (their choice).',
                    'Never let the group answer in single words — the Checker\'s job exists precisely for "make it a sentence".',
                    'Record the reading speed and one strategy used; that is your informal assessment entry for the week.',
                ],
            },
            { kind: 'memo', id: 'memo', title: 'Marks per learner (record in the class file)', items: [], total: 12 },
        ],
    },
];

export default CLASSROOM_TEMPLATES;
