import type { FoundationTemplate } from './types';
import { HOMEWORK_FIELDS } from './shared';

/**
 * Homework exercises — Grade R–3.
 *
 * Built on the CAPS Foundation Phase position that homework at this level is
 * short (10–20 minutes), oral-heavy, and only ever meaningful when a caregiver
 * is in the loop. Every sheet therefore states the time on task, the exact
 * task, a caregiver signature line, and — where marks apply — a memo so the
 * parent can check without guessing.
 */
export const HOMEWORK_TEMPLATES: FoundationTemplate[] = [
    {
        id: 'hw-grR-sound-hunt-at-home',
        kind: 'homework',
        title: 'Sound Hunt at Home',
        subtitle: 'Home Language Grade R · Phonics · 10 minutes with a grown-up',
        blurb:
            'A one-evening hunt for things that begin with this week\'s letter sounds, with a picture box for each find and a caregiver tick-list — no writing required.',
        grades: ['R'],
        learningArea: 'Home Language',
        theme: 'bubblegum',
        art: 'homework-bag',
        pages: 1,
        tags: ['Grade R', 'oral', 'no-writing', 'family task'],
        fields: HOMEWORK_FIELDS,
        caps: {
            contentArea: 'Phonics and Print Awareness · Listening and Speaking',
            skills: [
                'say the initial sound of a familiar home object',
                'blend 2–3 sounds orally (m-a → "ma")',
                'match a spoken sound to a printed letter',
            ],
            terms: ['Term 1 · Weeks 3–10 (1× per week)', 'Term 2 · Weeks 1–5'],
            asRef: 'HL Gr R — oral/aural work; no written homework is required in Grade R',
            blooms: ['Know', 'Apply'],
            timeOnTask: '10 minutes',
            setting: 'Homework',
            capsNote:
                'CAPS Grade R does not prescribe written homework; home tasks are oral and playful. Keep it to 10 minutes and never send home a task a learner cannot do without an adult.',
        },
        blocks: [
            {
                kind: 'callout',
                id: 'parent',
                title: 'For parents / caregivers — how to help',
                tone: 'parent',
                lines: [
                    'Do NOT correct the letter name: we teach the SOUND — "mmm", not "em".',
                    'Play it as a race: "Bring me something that starts with /s/!" Then clap together three times.',
                    'Let your child draw the object; they do not need to write words yet. If they can write, let them try.',
                    'Sign the box below. This is not a marked task — praise, do not test.',
                ],
            },
            {
                kind: 'checklist',
                id: 'hunt',
                title: 'Tonight\'s sound hunt — find 1 thing for each sound',
                instruction: 'Say the sound loudly. Find something at home that starts with that sound, then draw it in the box.',
                instructionLabel: 'Khangela · Zoba',
                style: 'star',
                items: [
                    '/m/  →  draw it:  ________________________________',
                    '/s/  →  draw it:  ________________________________',
                    '/a/  →  draw it:  ________________________________',
                    '/t/  →  draw it:  ________________________________',
                    '/p/  →  draw it:  ________________________________',
                ],
                footer: 'We hunted for ____ minutes. Did your child laugh at least once? Yes ☐  Ha-ha ☐',
            },
            {
                kind: 'task',
                id: 'say',
                title: 'Say it, tap it, blend it',
                instruction: 'Tap the table once for each sound your child hears, then push the taps together and say the word fast.',
                items: [
                    { text: 'm – a → "ma"  ·  Now you: s – u – n → ____________', lines: 1 },
                    { text: 'p – a – n → ____________', lines: 1 },
                    { text: 't – o – p → ____________', lines: 1 },
                ],
            },
            {
                kind: 'reward',
                id: 'reward',
                title: 'Brilliant work at home!',
                praise: [
                    'You hunted sounds like a detective! 🕵️',
                    'Bring this sheet back tomorrow — we will add your finds to our class word wall.',
                ],
                slots: 3,
            },
        ],
        options: { hideMemo: true },
    },
    {
        id: 'hw-gr1-number-shop-rands',
        kind: 'homework',
        title: 'Number Shop: Money and Counting at Home',
        subtitle: 'Mathematics Grade 1 · Numbers, Operations and Relationships · 15 minutes',
        blurb:
            'Count real objects, recognise coins with a caregiver, and solve two Rands-and-cents problems in the kitchen — with a parent-checkable memo at the bottom.',
        grades: ['1'],
        learningArea: 'Mathematics',
        theme: 'lagoon',
        art: 'elly-counting',
        pages: 1,
        tags: ['money', 'counting', 'parents can mark', 'Term 2'],
        fields: HOMEWORK_FIELDS,
        caps: {
            contentArea: 'Numbers, Operations and Relationships · Measurement (money)',
            skills: [
                'count a set of up to 100 objects in 2s, 5s and 10s',
                'recognise SA coins 5c, 10c, 20c, 50c and R1, R2; notes R5, R10, R20',
                'solve addition and subtraction problems with money up to R20',
            ],
            terms: ['Term 2 · Weeks 4–7'],
            asRef: 'CAPS Gr 1 Maths: money to R20 · counting in 2s, 5s, 10s',
            blooms: ['Know', 'Understand', 'Apply'],
            timeOnTask: '15 minutes',
            setting: 'Homework',
            marks: 12,
            capsNote:
                'Homework at Grade 1 must be work the learner can do independently; the caregiver\'s role is to supervise and sign, not to mark — the memo at the bottom allows both.',
            memo: [
                { ref: 'A', answer: '10s: 10, 20, 30, 40, 50 · 5s: 5, 10, 15, 20, 25 · 2s: 2, 4, 6, 8, 10', marks: 3 },
                { ref: 'B', answer: '10 spoons (or actual count reported), 6 cups, 4 shoes (2 pairs)', marks: 3 },
                { ref: 'C', answer: '50c + 20c = 70c · R2 + R5 = R7 · R10 − R6 = R4', marks: 3 },
                { ref: 'D', answer: 'Any total up to R20 correctly shown with coins/notes + sentence answer', marks: 3 },
            ],
        },
        blocks: [
            {
                kind: 'grid',
                id: 'A',
                title: 'A · Count on (say it out loud with a grown-up)',
                columns: ['+1', '+1', '+1', '+1'],
                rows: ['10 · 20 · 30', '5 · 10 · 15', '2 · 4 · 6'],
                marks: 3,
            },
            {
                kind: 'count',
                id: 'B',
                title: 'B · Kitchen count',
                instruction: 'Count the real things in your kitchen. Write the number in the boxes.',
                instructionLabel: 'Bala',
                items: [
                    { symbol: '🥄', count: 10, prompt: 'How many spoons?' },
                    { symbol: '🥛', count: 6, prompt: 'How many cups?' },
                    { symbol: '👟', count: 4, prompt: 'How many shoes?' },
                ],
                marks: 3,
            },
            {
                kind: 'task',
                id: 'C',
                title: 'C · Add the coins',
                instruction: 'Your grown-up can show you real coins from the house or draw them for you.',
                items: [
                    { text: '50c + 20c = ____', lines: 1, marks: 1 },
                    { text: 'R2 + R5 = ____', lines: 1, marks: 1 },
                    { text: 'Mama has R10. She spends R6. How much is left? ____', lines: 2, marks: 1 },
                ],
                marks: 3,
            },
            {
                kind: 'task',
                id: 'D',
                title: 'D · Shop with a grown-up tonight',
                instruction: 'Choose 2 items from the shopping list. Write the prices, then add them.',
                items: [
                    {
                        text: 'List: bread R12 · milk R20 · apples R9 · porridge R18 · soap R11 · buns R7  →  My two items and the total:',
                        lines: 3,
                        marks: 3,
                    },
                ],
                marks: 3,
            },
            {
                kind: 'callout',
                id: 'parent',
                title: 'Note to parents / caregivers',
                tone: 'parent',
                lines: [
                    'Use real money if you can — Rands and cents are learned in the hand, not on paper.',
                    'Do not do the sum for your child. Ask instead: "how did you work that out?"',
                    'Tick the memo at the bottom together and let your child see how many they got right.',
                ],
            },
            {
                kind: 'reward',
                id: 'reward',
                title: 'Homework star',
                praise: ['I did my maths homework without being told twice!'],
                slots: 5,
            },
            { kind: 'memo', id: 'memo', title: 'Parent memo (check together in 2 minutes)', items: [], total: 12 },
        ],
    },
    {
        id: 'hw-gr1-3-reading-log-week',
        kind: 'homework',
        title: 'One-Week Reading Log',
        subtitle: 'Home Language Grades 1–3 · Reading & Viewing · 10 minutes a night',
        blurb:
            'A five-night reading diary with minutes, a rating row of stars, a "best bit" line and a signature strip — the simplest way to prove daily reading happened.',
        grades: ['1', '2', '3'],
        learningArea: 'Home Language',
        theme: 'sunny',
        art: 'elly-reading',
        pages: 1,
        tags: ['reading diary', 'daily', 'parents sign', 'any term'],
        fields: HOMEWORK_FIELDS,
        caps: {
            contentArea: 'Reading and Viewing (independent reading for enjoyment)',
            skills: [
                'read an agreed text daily for 10 minutes with accuracy and expression',
                'state the best part and give a reason',
                'answer 2 questions about the text',
            ],
            terms: ['Term 1 · Week 2 → Term 4 · Week 9 (5 nights per week)'],
            asRef: 'AS 2 — reading for enjoyment; CAPS expects daily reading records',
            blooms: ['Apply', 'Evaluate'],
            timeOnTask: '10 minutes per night',
            setting: 'Homework',
            marks: 10,
            capsNote:
                'The reading diary doubles as evidence for the "informal assessment" record; 5 signed nights per week is the widely-used school convention for the Foundation Phase.',
            memo: [
                { ref: '5 nights', answer: 'Each night signed = 1 mark (5).', marks: 5 },
                { ref: 'Best bit', answer: 'Names the best part AND gives a reason = 2 marks.', marks: 2 },
                { ref: 'Words', answer: '3 new words the learner can now read = 1 mark each.', marks: 3 },
            ],
        },
        blocks: [
            {
                kind: 'grid',
                id: 'log',
                title: 'My reading log · this week',
                columns: ['Book / story title', 'Minutes', 'Read to (circle)', 'Stars (colour)', 'Grown-up sign'],
                rows: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                cellSize: 15,
                marks: 5,
            },
            {
                kind: 'task',
                id: 'reflect',
                title: 'About your best book this week',
                instruction: 'Answer in full sentences. You will read this out at the reading circle on Monday.',
                items: [
                    { text: 'The best part was … and I liked it because …', lines: 3, marks: 2 },
                    { text: 'Three new words I can now read: ____, ____, ____', lines: 1, marks: 3 },
                ],
                marks: 5,
            },
            {
                kind: 'callout',
                id: 'parent',
                title: 'Note to parents / caregivers',
                tone: 'parent',
                lines: [
                    'Ten minutes a night, five nights — that is all. Longer reading at this age turns readers off.',
                    'Three ways to help, in order of value: (1) listen to your child read aloud; (2) read TO your child; (3) talk about the story.',
                    'If your child is stuck on a word for more than 5 seconds, TELL them the word and keep moving — fluency and enjoyment matter more than decoding tonight.',
                    'Sign each night. A signed log is a record for the teacher, not a grade.',
                ],
            },
            {
                kind: 'checklist',
                id: 'classlink',
                title: 'Monday reading circle (teacher)',
                items: [
                    '5 nights signed → learner joins the Reading Star ring on the class wall',
                    'Fewer than 5 nights → quiet re-read at school with a partner (no punishment)',
                    'Learner read ABOVE grade level → lend the challenge book from the class library',
                ],
                footer: 'Class: ______  Week: ______  Readers: ____ / ____',
            },
            { kind: 'memo', id: 'memo', title: 'Marking memo', items: [], total: 10 },
        ],
    },
    {
        id: 'hw-gr2-weekly-homework-menu',
        kind: 'homework',
        title: 'Weekly Homework Menu (Gr 2)',
        subtitle: 'Mixed choice board · Languages + Mathematics · 4 nights × 15 minutes',
        blurb:
            'A "choose one per night" menu — reading, writing, a maths game and a Life Skills talk — so homework is purposeful without being a chore, plus a memo for each column.',
        grades: ['2'],
        learningArea: 'General',
        theme: 'grape',
        art: 'doodle-supplies',
        pages: 1,
        tags: ['choice board', 'mixed subjects', 'weekly', 'Term 3'],
        fields: HOMEWORK_FIELDS,
        caps: {
            contentArea: 'Home Language (all 4 content areas) · Mathematics (NOR + Measurement) · Life Skills',
            skills: [
                'read aloud and answer questions',
                'write 4 sentences with correct punctuation',
                'add and subtract to 200 in real-life contexts',
                'talk about a community issue with a caregiver',
            ],
            terms: ['Term 2 · Weeks 3–9', 'Term 3 · Weeks 2–8'],
            asRef: 'Weekly programme of assessment (Gr 2 informal / weekly checks)',
            blooms: ['Apply', 'Analyse'],
            timeOnTask: '15 minutes per night · 4 nights',
            setting: 'Homework',
            marks: 20,
            capsNote:
                'In Grades 2–3 the CAPS weekly programme expects one item per learning area to be checked and recorded each week — a choice board like this covers all three areas without 4 identical tasks.',
            memo: [
                { ref: 'Mon', answer: 'Read 6+ lines with expression; 2 answers in full sentences (5 marks).', marks: 5 },
                { ref: 'Tue', answer: '4 sentences, each with capital + full stop, sensible topic (5 marks: 1 per sentence, 1 for punctuation overall).', marks: 5 },
                { ref: 'Wed', answer: 'Answers within 200; method shown (5 marks). Accept counting on, place value, or number line.', marks: 5 },
                { ref: 'Thu', answer: 'Oral discussion with a caregiver + one written sentence of what was learned (5 marks).', marks: 5 },
            ],
        },
        blocks: [
            {
                kind: 'grid',
                id: 'menu',
                variant: 'table',
                title: 'Choose ONE column per night — tick when finished',
                columns: ['📖 Read', '✍️ Write', '🔢 Maths game', '🗣️ Talk'],
                rows: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
                cellSize: 11,
            },
            {
                kind: 'task',
                id: 'read',
                title: '📖 READ · any story from the class box or library',
                instruction: 'Read aloud to a grown-up. Then answer without looking at the book.',
                items: [
                    { text: 'Who is the main character and what do they want?', lines: 2, marks: 2 },
                    { text: 'What went wrong, and how was it fixed?', lines: 2, marks: 2 },
                    { text: 'One word I did not know at first: ____________  I read it by …', lines: 1, marks: 1 },
                ],
                marks: 5,
            },
            {
                kind: 'task',
                id: 'write',
                title: '✍️ WRITE · "The best thing about my street"',
                instruction: 'Four sentences. A capital letter and a full stop in every one. Underline your best word.',
                items: [{ text: 'The best thing about my street …', lines: 6, marks: 5 }],
                marks: 5,
            },
            {
                kind: 'task',
                id: 'maths',
                title: '🔢 MATHS GAME · kitchen numbers (play with a partner)',
                instruction: 'Say a number under 200. Your grown-up adds 10, you take away 5. Record your answers.',
                items: [
                    { text: 'Start 120 → +10 → −5 = ____', lines: 1, marks: 1 },
                    { text: 'Start 75 → +10 → −5 = ____', lines: 1, marks: 1 },
                    { text: 'Start 168 → +10 → −5 = ____', lines: 1, marks: 1 },
                    { text: 'You set a number and solve it yourself: ____ → +10 → −5 = ____', lines: 2, marks: 2 },
                ],
                marks: 5,
            },
            {
                kind: 'task',
                id: 'talk',
                title: '🗣️ TALK · community helper chat',
                instruction: 'Ask a grown-up at home: "Who helps our street stay clean and safe?" Then write what they said.',
                items: [
                    { text: 'They said:', lines: 2, marks: 3 },
                    { text: 'One thing I can do too:', lines: 1, marks: 2 },
                ],
                marks: 5,
            },
            {
                kind: 'callout',
                id: 'parent',
                title: 'Note to parents / caregivers',
                tone: 'parent',
                lines: [
                    'Choose the ORDER, not the work: pick one column per night and stop when it is done.',
                    'If a night is missed, do not report it as failure — tick the box on the weekend and note "busy day".',
                    'Homework is signed in the diary, not on this sheet, so the sheet comes back to school for the weekly record.',
                ],
            },
            { kind: 'memo', id: 'memo', title: 'Memo for parents who want to check', items: [], total: 20 },
        ],
    },
    {
        id: 'hw-gr3-family-timeline-project',
        kind: 'homework',
        title: 'Family Timeline Mini-Project',
        subtitle: 'Life Skills · Beginning Knowledge (Social Sciences) · weekend homework',
        blurb:
            'A 4-event family timeline, an interview record and a rubric — learners collect real dates from home and present on Monday. Week-end homework that is actually CAPS content.',
        grades: ['3'],
        learningArea: 'Life Skills — Beginning Knowledge',
        theme: 'tangerine',
        art: 'kids-classroom',
        pages: 1,
        tags: ['project', 'weekend', 'interview', 'rubric', 'Term 1'],
        fields: HOMEWORK_FIELDS,
        caps: {
            contentArea: 'Beginning Knowledge — Social Sciences: my family and its history (past → present sequencing)',
            skills: [
                'collect information from a family member (oral history)',
                'sequence 4 personal/family events using dates',
                'present findings to the class in 1 minute',
                'write a short paragraph about the past',
            ],
            terms: ['Term 1 · Weeks 4–7'],
            asRef: 'CAPS LS Gr 3 project / task-based assessment (1 per year)',
            blooms: ['Understand', 'Apply', 'Analyse', 'Evaluate'],
            timeOnTask: '40 min over the weekend + 1 min presentation',
            setting: 'Homework',
            marks: 20,
            capsNote:
                'Project / task-based assessment is one of the CAPS Foundation Phase programme-of-assessment types; a family timeline is the standard Grade 3 Beginning Knowledge task.',
            memo: [
                { ref: 'Timeline', answer: '4 events in correct order with years = 6 marks (1.5 each; accept 1 mark for order without year).', marks: 6 },
                { ref: 'Interview', answer: '3 questions asked, answers recorded in the learner\'s own words = 4 marks.', marks: 4 },
                { ref: 'Paragraph', answer: '5 sentences, capital letters/full stops, past tense attempted, relevant = 6 marks.', marks: 6 },
                { ref: 'Present', answer: 'Speaks clearly for 1 min, holds the poster, answers one question = 4 marks.', marks: 4 },
            ],
        },
        blocks: [
            {
                kind: 'grid',
                id: 'timeline',
                title: 'A · My family timeline (4 events, oldest on the left)',
                columns: ['1st (oldest)', '2nd', '3rd', '4th (latest)'],
                rows: ['What happened', 'Year', 'Who told me'],
                marks: 6,
            },
            {
                kind: 'task',
                id: 'interview',
                title: 'B · Interview a grandparent, aunt/uncle or older cousin',
                instruction: 'Ask the questions, write the answers in YOUR words (do not copy their exact words).',
                items: [
                    { text: 'What games did you play when you were my age?', lines: 3, marks: 1 },
                    { text: 'What was your walk to school like?', lines: 3, marks: 1 },
                    { text: 'What was difficult for your family, and how did they manage?', lines: 3, marks: 1 },
                    { text: 'What do you wish for me?', lines: 2, marks: 1 },
                ],
                marks: 4,
            },
            {
                kind: 'task',
                id: 'write',
                title: 'C · Write my paragraph',
                instruction: 'Five sentences about one event on your timeline. Use past tense words: was, went, lived, played, helped.',
                items: [{ text: 'A long time ago in my family …', lines: 8, marks: 6 }],
                marks: 6,
            },
            {
                kind: 'rubric',
                id: 'rubric',
                title: 'Assessment rubric (Monday presentation)',
                criteria: ['Timeline accuracy', 'Interview notes', 'Writing', 'Oral presentation'],
                levels: ['4 · Fully competent (70–100 %)', '3 · Largely competent (50–69 %)', '2 · Partially competent (30–49 %)', '1 · Not yet competent (0–29 %)'],
                cells: [
                    [
                        '4 events, ordered, with years',
                        '3 events ordered',
                        '2 events, order partly correct',
                        '1 event or no order',
                    ],
                    ['Own words + detail', 'Own words, brief', 'Copied answers', 'Not completed'],
                    ['5 sentences, correct punctuation, past tense', '4 sentences, few errors', '2–3 sentences, many errors', 'Fragments only'],
                    ['Clear, stands tall, answers a question', 'Clear to the front row', 'Quiet, reads only', 'Does not present'],
                ],
            },
            {
                kind: 'callout',
                id: 'parent',
                title: 'Note to parents / caregivers',
                tone: 'parent',
                lines: [
                    'The learner must write and draw. Please only talk; do not write for them or paste a printout of photos.',
                    'If there is no grandparent at home, any older person counts — a neighbour, an aunt, a church member. Never make a learner feel their family is the wrong shape.',
                    'Photographs are optional; if you send a printed photo, stick it on and write a caption underneath.',
                ],
            },
            { kind: 'memo', id: 'memo', title: 'Memo & mark summary', items: [], total: 20 },
        ],
    },
    {
        id: 'hw-gr2-3-homework-diary-signoff',
        kind: 'homework',
        title: 'Homework Diary & Weekly Sign-off',
        subtitle: 'Organisation sheet for Grades 2–3 · 1 page per week',
        blurb:
            'The weekly grid learners paste into their diary: task, subject, done-tick, minutes taken, parent sign, and a Monday teacher check box — plus an early-warning box for chronic non-submission.',
        grades: ['2', '3'],
        learningArea: 'General',
        theme: 'meadow',
        art: 'homework-bag',
        pages: 1,
        tags: ['organisation', 'diary', 'weekly', 'records'],
        fields: HOMEWORK_FIELDS,
        caps: {
            contentArea: 'Record-keeping & home–school partnership (CAPS SASL: parents must be informed of progress)',
            skills: ['recording own tasks', 'self-checking completion', 'communicating with the caregiver and teacher'],
            terms: ['Term 1 · Week 1 → Term 4 · Week 9 (weekly)'],
            asRef: 'SASL record-keeping / learner support',
            blooms: ['Apply', 'Evaluate'],
            timeOnTask: '2 minutes each night',
            setting: 'Homework',
            marks: undefined,
            capsNote:
                'CAPS Foundation Phase homework is not formally marked for content in most schools; the record of completion is what travels into the learner support file.',
        },
        blocks: [
            {
                kind: 'grid',
                id: 'week',
                title: 'This week\'s homework',
                columns: ['Task (copy from the board)', 'Subject', 'Done ✔', 'Minutes taken', 'Grown-up sign', 'Teacher check ☐'],
                rows: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                cellSize: 13,
            },
            {
                kind: 'checklist',
                id: 'me',
                title: 'My own homework habits',
                instruction: 'Tick the truth, not the wish. This is how we catch a problem in Week 3, not Week 9.',
                items: [
                    'I wrote my work down before I left the classroom.',
                    'I did my homework at the same place every night.',
                    'I did it before I watched TV or played.',
                    'I asked for help when I did not understand.',
                    'My bag had the exercise book I needed.',
                ],
                footer: 'This week I did my homework on ____ / 5 nights. My best night was ____________ because ______________.',
            },
            {
                kind: 'callout',
                id: 'escalate',
                title: 'Early-warning box (teacher)',
                tone: 'teacher',
                lines: [
                    'Fewer than 3 of 5 nights, two weeks running → phone the caregiver (log the call) and offer a 15-minute homework club.',
                    'Learner has no exercise book, not no homework → escalate through the class teacher to the HOD and check the DBE school-nutrition / stationery support lists.',
                    'Non-submission caused by home language barriers → send the task with a translated one-line instruction, not a detention.',
                    'Never mark homework for content in Grades R–1; praise effort and record completion.',
                ],
            },
            {
                kind: 'reward',
                id: 'reward',
                title: 'Five nights = five stickers',
                praise: ['A full row of five means you are a self-manager — that is a Grade 6 skill in a Grade 3 body!'],
                slots: 5,
            },
        ],
        options: { hideMemo: true },
    },
];

export default HOMEWORK_TEMPLATES;
