import type { FoundationTemplate } from './types';
import { PRACTICE_FIELDS } from './shared';

/**
 * Printable worksheets — Grade R–3.
 *
 * Authored against CAPS Foundation Phase content areas and ATP progression:
 * Grade R works inside 0–10 with letter-sounds; Grade 1 to 100; Grade 2 to 200
 * with tables 2/3/4/5; Grade 3 to 1 000 with common fractions. Every marked
 * sheet carries its own memo so the same file works for a teacher phot-copying
 * a class set and for a parent helping at home.
 */
export const WORKSHEET_TEMPLATES: FoundationTemplate[] = [
    {
        id: 'ws-grR-letter-sounds-tracing',
        kind: 'worksheet',
        title: 'Letter Sounds & Tracing: a · m · s · t · p',
        subtitle: 'Home Language Grade R · Phonics and Print Awareness · Term 1',
        blurb:
            'The first-sheet-of-the-year essential: trace five lowercase letters, hear the first sound, colour and cut-and-paste matching pictures.',
        grades: ['R'],
        learningArea: 'Home Language',
        theme: 'bubblegum',
        art: 'elly-reading',
        pages: 1,
        tags: ['phonics', 'handwriting', 'fine motor', 'Term 1'],
        fields: PRACTICE_FIELDS,
        caps: {
            contentArea: 'Phonics and Print Awareness (letter–sound correspondence, handwriting formation)',
            skills: [
                'recognise and name the letters a, m, s, t, p',
                'produce the initial sound of a familiar word',
                'form letters correctly from top to bottom, left to right',
            ],
            terms: ['Term 1 · Weeks 1–4'],
            asRef: 'HL Grade R: Listening & Speaking / Phonics & Print Awareness / Writing & Handwriting',
            blooms: ['Know', 'Understand', 'Apply'],
            timeOnTask: '15–20 min (whole-class, then table time)',
            setting: 'Classroom',
            marks: 15,
            capsNote:
                'Grade R Home Language teaches three integrated skills — listening & speaking, phonics & print awareness, and writing & handwriting — with language structure and thinking & reasoning woven through all of them.',
            memo: [
                { ref: 'A', answer: 'Each letter traced on the line and written independently on the free line: correct formation, starts at the top, sits on the baseline. 1 mark per letter × 5.', marks: 5 },
                { ref: 'B', answer: 'moon, man, mouse, milk begin with /m/. Do not mark the pictures; mark whether the learner can SAY the sound.', marks: 4 },
                { ref: 'C', answer: 'a→apple, m→moon, s→sun, t→table', marks: 4 },
                { ref: 'D', answer: 'Any sensible picture pasted under the matching letter column (accept a drawn object too).', marks: 2 },
            ],
        },
        blocks: [
            {
                kind: 'trace',
                id: 'A',
                title: 'A · Trace the letters, then write them yourself',
                titleXi: 'Landela emgceni',
                instruction: 'Start at the top and go down. Finger-trace the model first, then use your pencil.',
                style: 'font',
                items: [
                    { model: 'a m s', repeats: 2 },
                    { model: 't p', repeats: 2 },
                ],
                marks: 5,
            },
            {
                kind: 'colour-circle',
                id: 'B',
                title: 'B · Circle the pictures that begin with /m/',
                instruction: 'Say each word out loud with your teacher. If it starts like moon, circle it.',
                instructionLabel: 'Jikelezisa',
                actions: ['circle'],
                layout: 'grid',
                items: [
                    { text: '🌙', caption: 'moon' },
                    { text: '🐱', caption: 'cat' },
                    { text: '👨', caption: 'man' },
                    { text: '🚌', caption: 'bus' },
                    { text: '🐭', caption: 'mouse' },
                    { text: '🥛', caption: 'milk' },
                ],
                marks: 4,
            },
            {
                kind: 'match',
                id: 'C',
                title: 'C · Match the letter to the picture',
                instruction: 'Draw a line from the letter to the picture that begins with that sound.',
                instructionLabel: 'Xhumanisa',
                left: ['a', 'm', 's', 't'],
                right: ['🍎 apple', '🌙 moon', '🔥 sun', '🪑 table'],
                pairs: [
                    [1, 1],
                    [2, 2],
                    [3, 3],
                    [4, 4],
                ],
                guides: true,
                marks: 4,
            },
            {
                kind: 'cut-paste',
                id: 'D',
                title: 'D · Cut and paste the first sounds',
                instruction: 'Cut out the four boxes, then paste each one under the letter it starts with.',
                instructionLabel: 'Sika · Namathisela',
                pieces: ['🐜 ant', '🌙 moon', '☀️ sun', '🪑 table'],
                slots: ['a', 'm', 's', 't'],
            },
            {
                kind: 'callout',
                id: 'tip',
                title: 'Teaching tip',
                tone: 'tip',
                lines: [
                    'Say the SOUND (/a/ as in ant), never the letter name, for as long as learners are decoding.',
                    'Play "I spy" with the objects in the classroom after this sheet — CAPS Grade R expects oral work to outnumber written work.',
                    'Learners who cannot hold a pencil may complete section A with a finger in a tray of sand or porridge.',
                ],
            },
            { kind: 'memo', id: 'memo', title: 'Memo / marking guide', items: [], total: 15 },
        ],
    },
    {
        id: 'ws-grR-numbers-0-10',
        kind: 'worksheet',
        title: 'Counting, Tracing and Ordering 0–10',
        subtitle: 'Mathematics Grade R · Numbers, Operations and Relationships',
        blurb:
            'Count the classroom friends, write the numerals, ring the bigger group and complete a first pattern — all inside the Grade R number range.',
        grades: ['R'],
        learningArea: 'Mathematics',
        theme: 'lagoon',
        art: 'elly-counting',
        pages: 1,
        tags: ['number concept', 'counting', 'patterns', 'Term 1'],
        fields: PRACTICE_FIELDS,
        caps: {
            contentArea: 'Numbers, Operations and Relationships · Patterns, Functions and Algebra',
            skills: [
                'count a set of objects and write the numeral 0–10',
                'say which group is more / fewer',
                'continue an AB and ABC pattern',
            ],
            terms: ['Term 1 · Weeks 1–6', 'Term 2 · Weeks 1–4'],
            asRef: 'CAPS Gr R: number concept, range up to at least 10',
            blooms: ['Know', 'Apply'],
            timeOnTask: '20 min',
            setting: 'Classroom',
            marks: 18,
            capsNote:
                'CAPS Mathematics allocates 7 hours per week in the Foundation Phase; Grade R number work stays concrete — counting real objects before numerals are written.',
            memo: [
                { ref: 'A', answer: '4, 7, 5, 10, 3, 6, 8, 2 (one mark each).', marks: 8 },
                { ref: 'B', answer: 'Numerals 0–5 traced and written correctly; 2 must be "swan-shaped", 5 flat-topped.', marks: 3 },
                { ref: 'C', answer: 'Bigger group ringed: 7 bees vs 4 bees · 9 eggs vs 6 eggs. Cross on the smaller group.', marks: 4 },
                { ref: 'D', answer: 'Pattern: 🔴🔵🔴🔵🔴 → next is 🔵 · ABC: 🟡🟢🟡🟢 → next is 🟣.', marks: 3 },
            ],
        },
        blocks: [
            {
                kind: 'count',
                id: 'A',
                title: 'A · Count and write',
                instructionLabel: 'Bala',
                instruction: 'Count each group carefully, then write the number in the boxes.',
                compare: 'none',
                items: [
                    { symbol: '✋', count: 4 },
                    { symbol: '🥚', count: 7 },
                    { symbol: '🖍️', count: 5 },
                    { symbol: '⭐', count: 10 },
                    { symbol: '🐞', count: 3 },
                    { symbol: '🐟', count: 6 },
                    { symbol: '🦋', count: 8 },
                    { symbol: '🍊', count: 2 },
                ],
                marks: 8,
            },
            {
                kind: 'trace',
                id: 'B',
                title: 'B · Write the numbers',
                instruction: 'Trace 0 to 5, then write 6, 7, 8, 9 and 10 on your own lines.',
                style: 'manuscript',
                items: [
                    { model: '0 1 2', repeats: 2 },
                    { model: '3 4 5', repeats: 2 },
                    { model: '6 7 8 9 10', repeats: 1 },
                ],
                marks: 3,
            },
            {
                kind: 'count',
                id: 'C',
                title: 'C · Which group has MORE?',
                instruction: 'Ring the group with more. Put a cross (✗) on the group with fewer.',
                compare: 'largest-smallest',
                items: [
                    { symbol: '🐝', count: 7, prompt: 'Bees in the flower bed' },
                    { symbol: '🐝', count: 4, prompt: 'Bees on the hive' },
                    { symbol: '🥚', count: 9, prompt: 'Eggs in the nest' },
                    { symbol: '🥚', count: 6, prompt: 'Eggs in the basket' },
                ],
                marks: 4,
            },
            {
                kind: 'colour-circle',
                id: 'D',
                title: 'D · Complete the pattern',
                instruction: 'What comes next? Circle it, then colour the shapes.',
                actions: ['circle', 'colour'],
                items: [
                    { text: '🔴🔴🔵🔴 …', caption: 'next is 🔵 or 🔴?' },
                    { text: '🟡🟣🟡 …', caption: 'next is 🟣 or 🟡?' },
                ],
                marks: 3,
            },
            { kind: 'memo', id: 'memo', title: 'Memo', items: [], total: 18 },
        ],
    },
    {
        id: 'ws-grR-shapes-and-patterns',
        kind: 'worksheet',
        title: 'Shapes All Around Me',
        subtitle: 'Mathematics Grade R · Space and Shape (Geometry) + Patterns',
        blurb:
            'Colour by shape name, find circles and squares in the classroom, then finish and invent patterns — CAPS geometry and patterns in one friendly sheet.',
        grades: ['R'],
        learningArea: 'Mathematics',
        theme: 'grape',
        art: 'doodle-supplies',
        pages: 1,
        tags: ['2-D shapes', 'patterns', 'colouring', 'Term 2'],
        fields: PRACTICE_FIELDS,
        caps: {
            contentArea: 'Space and Shape (Geometry) · Patterns, Functions and Algebra',
            skills: [
                'recognise and name circles, squares, triangles and rectangles',
                'sort objects by shape',
                'copy, extend and create an AB pattern',
            ],
            terms: ['Term 2 · Weeks 3–6'],
            asRef: 'CAPS Gr R geometry: 2-D shapes/pictures in the environment',
            memo: [
                { ref: 'A', answer: 'circle→red · triangle→green · square→blue · rectangle→yellow. 1 mark per correct pair.', marks: 6 },
                { ref: 'B', answer: 'pizza→triangle · clock→circle · door→rectangle · window→square', marks: 4 },
                { ref: 'C', answer: '🔺 ·  · ■ (the pattern unit repeats)', marks: 3 },
                { ref: 'D', answer: 'Any correct real object: circle (plate, clock, wheel) · rectangle (door, book, fridge).', marks: 1 },
            ],
            blooms: ['Know', 'Understand', 'Apply'],
            timeOnTask: '20 min',
            setting: 'Classroom',
            marks: 14,
            capsNote:
                'Foundation Phase geometry is 2-D first and always linked to real objects; patterns are the first algebraic thinking in CAPS and are assessed by copying and extending.',
        },
        blocks: [
            {
                kind: 'colour-circle',
                id: 'A',
                title: 'A · Colour the shapes',
                instruction: 'Circles → red · Squares → blue · Triangles → green · Rectangles → yellow.',
                instructionLabel: 'Penda',
                actions: ['colour'],
                layout: 'grid',
                palette: [
                    ['red', '#ff5a5f'],
                    ['blue', '#2563eb'],
                    ['green', '#2ed573'],
                    ['yellow', '#ffdf40'],
                ],
                items: [
                    { text: '⭕', caption: 'circle' },
                    { text: '▲', caption: 'triangle' },
                    { text: '■', caption: 'square' },
                    { text: '▬', caption: 'rectangle' },
                    { text: '⬤', caption: 'circle' },
                    { text: '◀', caption: 'triangle' },
                ],
                marks: 6,
            },
            {
                kind: 'match',
                id: 'B',
                title: 'B · What shape is it?',
                instruction: 'Draw a line from the object to the shape it looks like.',
                left: ['🍕 slice of pizza', ' clock', ' door', ' window'],
                right: ['⭕ circle', '▲ triangle', '■ square', '▬ rectangle'],
                pairs: [
                    [1, 2],
                    [2, 1],
                    [3, 4],
                    [4, 3],
                ],
                marks: 4,
            },
            {
                kind: 'task',
                id: 'C',
                title: 'C · What shape comes next?',
                instruction: 'Look at the pattern. Draw the shape that comes next on the line.',
                instructionLabel: 'Zoba',
                items: [
                    { text: '🔵 🔺 🔵 🔺 ▢', lines: 1, marks: 1 },
                    { text: '⬤ ■ ⬤ ■ ▢', lines: 1, marks: 1 },
                    { text: '▲ ▲ ■ ▲ ▲ ▢', lines: 1, marks: 1 },
                ],
                marks: 3,
            },
            {
                kind: 'task',
                id: 'D',
                title: 'D · Shape hunt at home',
                instruction: 'Look around your house tonight. Draw or write what you find.',
                items: [
                    { text: 'One thing shaped like a circle:', lines: 1 },
                    { text: 'One thing shaped like a rectangle:', lines: 1 },
                ],
                marks: 1,
            },
            { kind: 'memo', id: 'memo', title: 'Memo', items: [], total: 14 },
        ],
    },
    {
        id: 'ws-gr1-hl-sight-words-sentences',
        kind: 'worksheet',
        title: 'Sight Words and Simple Sentences',
        subtitle: 'Home Language Grade 1 · Reading and Viewing · Writing and Presenting',
        blurb:
            'Twelve high-frequency words, a gap-fill story, a sentence-scramble and a copywriting frame — the Grade 1 reading and writing bundle.',
        grades: ['1'],
        learningArea: 'Home Language',
        theme: 'sunny',
        art: 'elly-reading',
        pages: 1,
        tags: ['sight words', 'sentence building', 'handwriting', 'Term 1–2'],
        fields: PRACTICE_FIELDS,
        caps: {
            contentArea: 'Reading and Viewing · Writing and Presenting · Language Structures and Conventions',
            skills: [
                'read agreed high-frequency words on sight',
                'build a simple sentence with a capital letter and full stop',
                'write 2–3 sentences on a familiar topic',
            ],
            terms: ['Term 1 · Weeks 3–8', 'Term 2 · Weeks 1–4'],
            asRef: 'HL Gr 1 AS1 (reading aloud) & AS3 (writing)',
            blooms: ['Know', 'Apply'],
            timeOnTask: '25 min',
            setting: 'Classroom',
            marks: 20,
            capsNote:
                'Grade 1 Home Language receives 7–8 hours per week; sight vocabulary is taught daily for 10–15 minutes and re-used in the writing frame on this sheet.',
            memo: [
                { ref: 'A', answer: 'the, my, is, are, can, like, see, we, he, she, and, this (read aloud, no sounding out needed).', marks: 4 },
                { ref: 'B', answer: '1 the · 2 my · 3 is · 4 can · 5 like · 6 see', marks: 6 },
                { ref: 'C', answer: '1 I like my dog. · 2 We can see the bus. · 3 This is my school. · 4 He is big.', marks: 4 },
                { ref: 'D', answer: 'Any 3 sentences, each with a capital letter, a full stop and a sensible idea about home. 1 mark per correct sentence + 1 for capitals/full stops.', marks: 6 },
            ],
        },
        blocks: [
            {
                kind: 'word-bank',
                id: 'A',
                title: 'A · Read the words aloud with your teacher',
                instruction: 'Point with your finger and read each word. Then write them in the correct gap in B.',
                instructionLabel: 'Funda · Bhala',
                words: ['the', 'my', 'is', 'are', 'can', 'like', 'see', 'we', 'he', 'she', 'and', 'this'],
                sentences: [
                    'This ___ my bag.',
                    'I like ___ dog.',
                    'We ___ see the bus.',
                    'She ___ reading.',
                    'They ___ playing outside.',
                    'He ___ jump very high.',
                ],
                marks: 4,
            },
            {
                kind: 'task',
                id: 'B',
                title: 'B · Write the words in the sentences',
                instruction: 'Use a word from the box for every gap. One word is a trick — it is not needed.',
                items: [{ text: 'Rewrite sentence 1 in your best handwriting.', lines: 2 }],
                marks: 6,
            },
            {
                kind: 'cut-paste',
                id: 'C',
                title: 'C · Cut the word cards and build the sentences',
                instruction: 'Cut out each sentence strip and paste it under the heading it belongs to. The capital letter tells you who the sentence is about!',
                pieces: ['I like my dog.', 'We can see the bus.', 'This is my school.', 'He is big.'],
                slots: ['1', '2', '3', '4'],
                contexts: ['About me:', 'About us:', 'About my school:', 'About him:'],
                marks: 4,
            },
            {
                kind: 'trace',
                id: 'D',
                title: 'D · My writing frame',
                instruction: 'Trace one sentence, then write three sentences about your home. Remember: capital letter, full stop.',
                items: [{ model: 'I live with my family.', repeats: 1 }],
                frames: ['My favourite place at home is …', 'I like to play with …', 'At night we …'],
                marks: 6,
            },
            { kind: 'memo', id: 'memo', title: 'Memo and marking guide', items: [], total: 20 },
        ],
    },
    {
        id: 'ws-gr1-maths-add-subtract-100',
        kind: 'worksheet',
        title: 'Adding and Subtracting to 100',
        subtitle: 'Mathematics Grade 1 · Numbers, Operations and Relationships',
        blurb:
            'Number bonds, tens-and-ones place value, column addition without regrouping, and three money word problems in South African rands — with a full memo.',
        grades: ['1'],
        learningArea: 'Mathematics',
        theme: 'meadow',
        art: 'elly-counting',
        pages: 1,
        tags: ['addition', 'subtraction', 'place value', 'money', 'Term 2–3'],
        fields: PRACTICE_FIELDS,
        caps: {
            contentArea: 'Numbers, Operations and Relationships (addition and subtraction, number sentences, problem solving)',
            skills: [
                'recall addition and subtraction facts to 10 and to 20',
                'use place value (tens and ones) to add and subtract numbers to 100',
                'solve word problems with Rands up to R20 and coins 5c–R5',
            ],
            terms: ['Term 2 · Weeks 2–6', 'Term 3 · Weeks 1–5'],
            asRef: 'CAPS Gr 1 Maths: addition & subtraction, number sentences (topic 1.9–1.11)',
            blooms: ['Know', 'Understand', 'Apply', 'Analyse'],
            timeOnTask: '30 min',
            setting: 'Classroom',
            marks: 25,
            capsNote:
                'Content-area weighting for Grade 1 Mathematics is: Numbers/Operations/Relationships 65 %, Patterns 10 %, Space & Shape 11 %, Measurement 9 %, Data Handling 5 % — this sheet targets the 65 % strand.',
            memo: [
                { ref: 'A', answer: '7+3=10 · 6+4=10 · 9+1=10 · 10−6=4 · 10−3=7 · 8+2=10', marks: 6 },
                { ref: 'B', answer: '34 = 3 tens 4 ones · 60 = 6 tens 0 ones · 47 = 4 tens 7 ones · 100 = 10 tens', marks: 4 },
                { ref: 'C', answer: '23+14=37 · 45+30=75 · 58−25=33 · 96−41=55 · 62+27=89 · 79−36=43', marks: 6 },
                { ref: 'D1', answer: 'R12 + R7 = R19', marks: 2 },
                { ref: 'D2', answer: 'R20 − R14 = R6 change', marks: 3 },
                { ref: 'D3', answer: '4 × R2 = R8; R10 − R8 = R2 left', marks: 4 },
            ],
        },
        blocks: [
            {
                kind: 'grid',
                id: 'A',
                title: 'A · Lightning round — number bonds to 10',
                variant: 'boxes',
                instruction: 'Say each fact out loud, then write the answer.',
                columns: ['7 + 3', '6 + 4', '9 + 1', '10 − 6', '10 − 3', '8 + 2'],
                rows: ['Answer'],
                cellSize: 14,
                marks: 6,
            },
            {
                kind: 'grid',
                id: 'B',
                title: 'B · Tens and ones',
                columns: ['Number', 'Tens', 'Ones', 'Total'],
                rows: ['34', '60', '47', '100'],
                filled: { '0,0': '34', '1,0': '60', '2,0': '47', '3,0': '100' },
                marks: 4,
            },
            {
                kind: 'task',
                id: 'C',
                title: 'C · Calculate',
                instruction: 'Put tens under tens and ones under ones. You do not need to borrow.',
                instructionLabel: 'Bala',
                items: [
                    { text: '23 + 14 =', lines: 1, marks: 1 },
                    { text: '45 + 30 =', lines: 1, marks: 1 },
                    { text: '58 − 25 =', lines: 1, marks: 1 },
                    { text: '96 − 41 =', lines: 1, marks: 1 },
                    { text: '62 + 27 =', lines: 1, marks: 1 },
                    { text: '79 − 36 =', lines: 1, marks: 1 },
                ],
                marks: 6,
            },
            {
                kind: 'task',
                id: 'D',
                title: 'D · Word problems at the spaza shop',
                instruction: 'Draw a quick picture or use coins. Show what you did and write the answer.',
                items: [
                    { text: 'A loaf of bread costs R12. A packet of milk costs R7. How much for both?', lines: 2, marks: 2 },
                    { text: 'Thabo buys an apple for R14 and pays with a R20 note. How much change?', lines: 2, marks: 3 },
                    { text: 'One pencil costs R2. Sipho buys 4 pencils and pays with R10. How much is left?', lines: 3, marks: 4 },
                ],
                marks: 9,
            },
            { kind: 'memo', id: 'memo', title: 'Memo (parents: please use this when you check)', items: [], total: 25 },
        ],
    },
    {
        id: 'ws-gr1-ls-living-non-living',
        kind: 'worksheet',
        title: 'Living and Non-living Things',
        subtitle: 'Life Skills · Beginning Knowledge (Natural Sciences) · Grade 1',
        blurb:
            'Sort, tick, explain and observe — a first science investigation with an outdoor walk, built for CAPS Beginning Knowledge in Grade 1.',
        grades: ['1'],
        learningArea: 'Life Skills — Beginning Knowledge',
        theme: 'meadow',
        art: 'elly-nature',
        pages: 1,
        tags: ['science', 'observing', 'sorting', 'outdoor walk', 'Term 3'],
        fields: PRACTICE_FIELDS,
        caps: {
            contentArea: 'Beginning Knowledge — Natural Sciences: Living and non-living things',
            skills: [
                'sort objects and organisms into living / non-living',
                'give reasons for a sort using the 7 life processes at a Grade 1 level (grow, need food and water, can reproduce, feel/respond)',
                'observe and record in the environment',
            ],
            terms: ['Term 3 · Weeks 2–4'],
            asRef: 'CAPS LS Gr 1 Beginning Knowledge: "Living and non-living things"',
            blooms: ['Know', 'Understand', 'Analyse'],
            timeOnTask: '10 min teaching + 20 min sheet + 15 min walk',
            setting: 'Guided reading / group table',
            marks: 15,
            capsNote:
                'Beginning Knowledge receives 1 hour per week in Grades 1–2 and 2 hours in Grade 3; practical, enquiry-based work in the school environment is the required method.',
            memo: [
                { ref: 'A', answer: 'Living: dog, sunflower, learner, snail. Non-living: stone, chair, bicycle, plastic bottle.', marks: 4 },
                { ref: 'B', answer: 'It grows · It needs water · It eats · It has babies (any 3).', marks: 3 },
                { ref: 'C', answer: 'Stone: cannot grow, does not need food or water, has no babies. Accept any two sensible reasons.', marks: 2 },
                { ref: 'D', answer: '3 living + 3 non-living found outside, correctly sorted.', marks: 4 },
                { ref: 'E', answer: 'Any sensible sentence, e.g. "The grass is living because it grows and needs water."', marks: 2 },
            ],
        },
        blocks: [
            {
                kind: 'grid',
                id: 'A',
                title: 'A · Sort the pictures',
                columns: ['🐕 dog', ' sunflower', '🪨 stone', '🚗 car', '👧 learner', '🐌 snail', '🪑 chair', '🧴 bottle'],
                rows: ['Living (L)', 'Non-living (NL)'],
                variant: 'table',
                instruction: 'Write L under the living things and NL under the non-living things.',
                instructionLabel: 'Hlela',
                cellSize: 12,
                marks: 4,
            },
            {
                kind: 'task',
                id: 'B',
                title: 'B · How do you know it is living?',
                instruction: 'Tick the 3 things ONLY living things do.',
                items: [
                    {
                        text: 'Circle / tick what a living thing does:',
                        options: ['It grows.', 'It needs water.', 'It is bright-coloured.', 'It has babies.', 'It can be broken.'],
                        marks: 3,
                    },
                    { text: 'Why is a stone NOT living? Write two reasons.', lines: 2, marks: 2 },
                ],
                marks: 5,
            },
            {
                kind: 'checklist',
                id: 'C',
                title: 'C · Outdoor walk — record what you see',
                instruction: 'Walk around the school with your partner. Write what you found in each box.',
                style: 'box',
                items: [
                    'Living thing 1: ______________________',
                    'Living thing 2: ______________________',
                    'Living thing 3: ______________________',
                    'Non-living thing 1: ____________________',
                    'Non-living thing 2: ____________________',
                    'Non-living thing 3: ____________________',
                ],
                footer: 'We worked safely and did not touch unknown plants or insects. ✔ Teacher sign: ____________',
                marks: 4,
            },
            {
                kind: 'task',
                id: 'D',
                title: 'D · Write your finding',
                instruction: 'Finish the sentence in a full sentence with a capital letter and a full stop.',
                items: [{ text: 'I know the … is living because …', lines: 2 }],
                marks: 2,
            },
            {
                kind: 'callout',
                id: 'safety',
                title: 'Safety first',
                tone: 'safety',
                lines: [
                    'No learner puts a plant, insect or berry in their mouth during the walk.',
                    'Stay inside the marked area; carry an eggbox or tray so finds are carried, not pocketed.',
                    'Wash hands with soap when we come back inside.',
                ],
            },
            { kind: 'memo', id: 'memo', title: 'Memo', items: [], total: 15 },
        ],
    },
    {
        id: 'ws-gr2-hl-nouns-verbs-punctuation',
        kind: 'worksheet',
        title: 'Nouns, Verbs and Punctuation',
        subtitle: 'Home Language Grade 2 · Language Structures and Conventions',
        blurb:
            'Sort words into naming/doing columns, fix messy sentences with capitals and full stops, and rewrite a paragraph with correct punctuation.',
        grades: ['2'],
        learningArea: 'Home Language',
        theme: 'bubblegum',
        art: 'kids-classroom',
        pages: 1,
        tags: ['grammar', 'punctuation', 'LSC', 'Term 2'],
        fields: PRACTICE_FIELDS,
        caps: {
            contentArea: 'Language Structures and Conventions (taught in context of reading and writing)',
            skills: [
                'identify nouns (person, place, animal, thing) and verbs (doing words)',
                'use capital letters for names, places and sentence starts',
                'use the full stop, question mark and exclamation mark correctly',
            ],
            terms: ['Term 2 · Weeks 3–6'],
            asRef: 'HL Gr 2 AS4 — language structures and conventions',
            blooms: ['Understand', 'Analyse'],
            timeOnTask: '25 min',
            setting: 'Classroom',
            marks: 20,
            capsNote:
                'CAPS requires Language Structures and Conventions to be taught in context, not as isolated grammar drills — every item on this sheet is drawn from the same story text.',
            memo: [
                { ref: 'A', answer: 'Nouns: teacher, Cape Town, dog, Thabo · Verbs: runs, sings, eats, jumps. 2 marks per correct column run.', marks: 8 },
                { ref: 'B', answer: '1 Where do you live? 2 My name is Lerato. 3 We play netball on Mondays. 4 Look at that big wave!', marks: 4 },
                { ref: 'C', answer: 'Correct capital letters (Monday, Zanele, Durban, uShaka), full stops, question mark. Award 1 mark per correct fix.', marks: 6 },
                { ref: 'D', answer: 'Any 2 nouns and 2 verbs used in 2 sentences, with a capital letter and a full stop.', marks: 4 },
            ],
        },
        blocks: [
            {
                kind: 'grid',
                id: 'A',
                title: 'A · Naming words or doing words?',
                columns: ['teacher', 'runs', 'Cape Town', 'sings', 'dog', 'eats', 'Thabo', 'jumps'],
                rows: ['Noun (n)', 'Verb (v)'],
                instruction: 'Write n under the naming words and v under the doing words. Two of these can be BOTH — think before you write!',
                cellSize: 12,
                marks: 8,
            },
            {
                kind: 'task',
                id: 'B',
                title: 'B · Add the missing mark',
                instruction: 'Write a full stop, a question mark or an exclamation mark at the end of each sentence.',
                items: [
                    { text: 'Where do you live', options: ['.', '?', '!'], marks: 1 },
                    { text: 'My name is Lerato', options: ['.', '?', '!'], marks: 1 },
                    { text: 'We play netball on Mondays', options: ['.', '?', '!'], marks: 1 },
                    { text: 'Look at that big wave', options: ['.', '?', '!'], marks: 1 },
                ],
                marks: 4,
            },
            {
                kind: 'task',
                id: 'C',
                title: 'C · Rewrite the paragraph',
                instruction: 'Rewrite with correct capital letters and full stops. Six capital letters and five full stops are missing.',
                items: [
                    {
                        text: 'on monday zanele went to durban. she saw the sea at uShaka. she ate a fish and chips. did you go to durban? yes! it was the best day.',
                        lines: 4,
                    },
                ],
                marks: 6,
            },
            {
                kind: 'word-bank',
                id: 'D',
                title: 'D · Use the words in your own sentences',
                instruction: 'Write two sentences: one with a naming word from the box, one with a doing word.',
                words: ['teacher', 'market', 'springbok', 'dances', 'shares', 'laughed'],
                sentences: ['Noun sentence: ___', 'Verb sentence: ___'],
                marks: 4,
            },
            { kind: 'memo', id: 'memo', title: 'Memo', items: [], total: 20 },
        ],
    },
    {
        id: 'ws-gr2-maths-arrays-time',
        kind: 'worksheet',
        title: 'Equal Groups, Arrays and O\'Clock Time',
        subtitle: 'Mathematics Grade 2 · NOR + Patterns + Measurement',
        blurb:
            'Repeated addition from arrays, the 2/3/4/5 tables, equal sharing with remainders, and reading o\'clock and half-past on an analogue clock.',
        grades: ['2'],
        learningArea: 'Mathematics',
        theme: 'lagoon',
        art: 'elly-counting',
        pages: 1,
        tags: ['multiplication', 'arrays', 'sharing', 'time', 'Term 3'],
        fields: PRACTICE_FIELDS,
        caps: {
            contentArea: 'Numbers, Operations and Relationships · Patterns, Functions and Algebra · Measurement (time)',
            skills: [
                'represent equal groups as repeated addition and multiplication (tables 2, 3, 4, 5)',
                'solve equal sharing and grouping problems, including remainders',
                'read time to the hour and half-hour on an analogue clock',
            ],
            terms: ['Term 3 · Weeks 1–6'],
            asRef: 'CAPS Gr 2 Maths topics 1.13–1.15 (multiplication, division) & 4.1 (time)',
            blooms: ['Know', 'Understand', 'Apply'],
            timeOnTask: '30 min',
            setting: 'Classroom',
            marks: 25,
            capsNote:
                'Grade 2 weighting: Numbers/Operations/Relationships 60 %, Patterns 10 %, Space & Shape 13 %, Measurement 12 %, Data Handling 5 %.',
            memo: [
                { ref: 'A', answer: '3 groups of 4: 4+4+4=12, 3×4=12 · 5 groups of 2: 2+2+2+2+2=10, 5×2=10', marks: 4 },
                { ref: 'B', answer: '2×7=14 · 3×6=18 · 4×5=20 · 5×8=40 · 9×2=18 · 6×3=18', marks: 6 },
                { ref: 'C', answer: '20 ÷ 4 = 5 each · 15 ÷ 2 = 7 each, remainder 1 · 27 ÷ 5 = 5 each, remainder 2', marks: 6 },
                { ref: 'D', answer: '🔢 4 × 8 = 32; doubles: 15+15=30, 24+24=48', marks: 4 },
                { ref: 'E', answer: 'School 07:00 · break 10:00 · lunch 13:00 (accept half-past variants if drawn correctly).', marks: 5 },
            ],
        },
        blocks: [
            {
                kind: 'task',
                id: 'A',
                title: 'A · From the picture to the number sentence',
                instruction: 'Look at the groups. Write the addition sentence AND the multiplication sentence.',
                items: [
                    { text: '🟢🟢🟢 | 🟢🟢🟢 | 🟢🟢🟢  (3 groups of 4)', lines: 2, marks: 2 },
                    { text: '🔵🔵 | 🔵🔵 | 🔵🔵 | 🔵🔵 | 🔵🔵  (5 groups of 2)', lines: 2, marks: 2 },
                ],
                marks: 4,
            },
            {
                kind: 'grid',
                id: 'B',
                title: 'B · Rapid recall — tables 2, 3, 4 and 5',
                variant: 'boxes',
                instruction: 'Answer in 5 minutes. Do not use your fingers — use your doubling and building-up strategies.',
                columns: ['2 × 7', '3 × 6', '4 × 5', '5 × 8', '9 × 2', '6 × 3'],
                rows: ['Answer'],
                cellSize: 15,
                marks: 6,
            },
            {
                kind: 'task',
                id: 'C',
                title: 'C · Sharing fairly at the picnic',
                instruction: 'Draw the objects into the plates. Write the division sentence and any remainder.',
                items: [
                    { text: '20 biscuits shared equally among 4 learners', lines: 2, marks: 2 },
                    { text: '15 oranges shared between 2 baskets', lines: 2, marks: 2 },
                    { text: '27 pencils put into 5 tins', lines: 3, marks: 2 },
                ],
                marks: 6,
            },
            {
                kind: 'grid',
                id: 'D',
                title: 'D · Patterns and doubling',
                variant: 'table',
                columns: ['Pattern', 'Next 2 numbers', 'Double', 'Half of it'],
                rows: ['4; 8; 12; 16', '5; 10; 15; 20', '15', '24'],
                marks: 4,
            },
            {
                kind: 'task',
                id: 'E',
                title: 'E · Draw the clock hands',
                instruction: 'Draw the hour hand and the minute hand on each clock face.',
                items: [
                    { text: '🕐 School starts at 07:00', lines: 1, marks: 1 },
                    { text: '🕐 Break time is 10:00', lines: 1, marks: 1 },
                    { text: '🕐 Lunch is at half past one (13:30)', lines: 1, marks: 2 },
                    { text: 'Write what you do at 19:00 tonight.', lines: 1, marks: 1 },
                ],
                marks: 5,
            },
            { kind: 'memo', id: 'memo', title: 'Memo', items: [], total: 25 },
        ],
    },
    {
        id: 'ws-gr3-hl-poem-comprehension',
        kind: 'worksheet',
        title: 'Poem: "The Taxi Rank in the Morning"',
        subtitle: 'Home Language Grade 3 · Reading and Viewing (rhyme, rhythm, meaning)',
        blurb:
            'An original CAPS-style poem with comprehension, vocabulary work, a rhyme hunt and a 5-line write-back — with a full memo and mark allocation.',
        grades: ['3'],
        learningArea: 'Home Language',
        theme: 'grape',
        art: 'rainbow-banner',
        pages: 2,
        tags: ['poetry', 'comprehension', 'vocabulary', 'writing', 'Term 2'],
        fields: PRACTICE_FIELDS,
        caps: {
            contentArea: 'Reading and Viewing (texts for enjoyment) · Writing and Presenting · Language Structures and Conventions',
            skills: [
                'read a poem aloud with the correct rhythm and stress',
                'identify rhyme, repetition and a comparison in a poem',
                'answer literal and inferential questions in full sentences',
                'write an imaginative response of at least 5 lines',
            ],
            terms: ['Term 2 · Weeks 5–8'],
            asRef: 'HL Gr 3 AS2 (reading & viewing) + AS3 (writing & presenting)',
            blooms: ['Understand', 'Analyse', 'Evaluate', 'Apply'],
            timeOnTask: '15 min reading · 25 min questions',
            setting: 'Classroom',
            marks: 30,
            capsNote:
                'Gr 3 listening/reading texts are short (250–400 words for reading); poetry is expected to be read aloud for pleasure before it is analysed.',
            memo: [
                { ref: '1.1', answer: 'At the taxi rank / in the morning, before school.', marks: 1 },
                { ref: '1.2', answer: '"hooter" / "beep" / "toot" — any 2 sounds.', marks: 2 },
                { ref: '1.3', answer: 'line 1 (street) rhymes with line 4 (feet)? Accept "street / feet" and "day / away" as the rhyme pairs.', marks: 2 },
                { ref: '2.1', answer: 'The minibus taxi is compared to a big yellow bee (it buzzes and is busy).', marks: 2 },
                { ref: '2.2', answer: 'The repetition of "hup, hallo" shows everyone greeting each other / it sounds busy and cheerful.', marks: 2 },
                { ref: '2.3', answer: 'She is counting her change / she is hurrying to be on time for school.', marks: 2 },
                { ref: '3.1', answer: 'rhyme — words that end with the same sound (street / feet).', marks: 1 },
                { ref: '3.2', answer: 'rhythm — the beat of the poem, like a taxi engine.', marks: 1 },
                { ref: '3.3', answer: 'comparison — saying one thing is like another.', marks: 1 },
                { ref: '4', answer: '5 lines: capital letter + full stop each, at least one rhyme, sensible content. 2 marks handwriting/spelling.', marks: 8 },
            ],
        },
        blocks: [
            {
                kind: 'comprehension',
                id: 'passage',
                title: 'Read the poem aloud twice, then answer',
                passageTitle: 'The Taxi Rank in the Morning',
                passage: [
                    'Before the sun is fully awake,',
                    'the taxi rank is already wide awake:',
                    'a hooter goes beep, a taxi toots,',
                    'soldies shout "hup! hup!" in their street shoes.',
                    '',
                    'A big yellow taxi, busy as a bee,',
                    'carries my schoolbag and my book and me.',
                    'Nomsa counts her change, one coin, two coins —',
                    'the meter is ticking, the morning is in a hurry.',
                ],
                passageArt: 'kids-classroom',
                vocabulary: [
                    { word: 'hooter', ask: 'What does the hooter do? Say the sound like the taxi.' },
                    { word: 'soldier / soldie', ask: 'Who sells things at the taxi rank?' },
                    { word: 'meter', ask: 'Where do you hear a meter ticking?' },
                    { word: 'busy as a bee', ask: 'Is that true or just a comparison? Explain.' },
                ],
                questions: [
                    { text: 'Where and when does the poem happen?', lines: 1, marks: 1 },
                    { text: 'Write down TWO sounds you can hear in the poem.', lines: 1, marks: 2 },
                    { text: 'Find TWO pairs of rhyming words in stanza 1.', lines: 2, marks: 2 },
                    { text: 'What is the taxi compared to, and why?', lines: 2, marks: 2 },
                    { text: 'Why do the soldies say "hup! hup!"? What does the repetition tell you about the rank?', lines: 2, marks: 2 },
                    { text: 'How does Nomsa feel? Use a clue from the poem to support your answer.', lines: 2, marks: 2 },
                ],
            },
            {
                kind: 'task',
                id: 'terms',
                title: 'Poetry toolbox · match the term to the meaning',
                instruction: 'Write the letter of the correct meaning next to each poetry term.',
                items: [
                    { text: 'rhyme', options: ['A. the beat of a poem', 'B. words with the same ending sound', 'C. saying one thing is like another'], marks: 1 },
                    { text: 'rhythm', options: ['A. the beat of a poem', 'B. words with the same ending sound', 'C. saying one thing is like another'], marks: 1 },
                    { text: 'comparison', options: ['A. the beat of a poem', 'B. words with the same ending sound', 'C. saying one thing is like another'], marks: 1 },
                ],
                marks: 3,
            },
            {
                kind: 'trace',
                id: 'model',
                title: 'Model line — copy for rhythm',
                instruction: 'Copy the line below keeping the same rhythm, then write your own 5 lines: "My way to school".',
                items: [{ model: 'The taxi is busy as a bee.', repeats: 1 }],
                marks: 8,
            },
            {
                kind: 'task',
                id: 'write',
                title: 'Write back · My way to school (5 lines)',
                instruction: 'Write at least 5 lines. Include ONE rhyme pair and ONE comparison. Use a capital letter and a full stop in every line.',
                items: [{ text: 'My way to school', lines: 8 }],
                marks: 8,
            },
            {
                kind: 'callout',
                id: 'tip',
                title: 'Teaching tip — before the questions',
                tone: 'tip',
                lines: [
                    'Read the poem aloud yourself first with exaggerated rhythm; Grade 3 learners copy your phrasing.',
                    'Let learners mark their own rhyme pairs in pencil with coloured highlighting before they write full answers.',
                    'For learners who read slowly, pair them for "echo reading" — you read a line, they read it back.',
                ],
            },
            {
                kind: 'rubric',
                id: 'rubric',
                title: 'Writing rubric (use for section "Write back")',
                criteria: ['Content & ideas', 'Rhyme & rhythm', 'Sentences & punctuation', 'Handwriting & spelling'],
                levels: ['4 · Fully competent', '3 · Largely competent', '2 · Partially competent', '1 · Not yet competent'],
                cells: [
                    [
                        '5+ relevant lines, clear picture of the journey',
                        'Mostly relevant, some repetition',
                        'Only 2–3 lines or off topic',
                        'Copied from the model only',
                    ],
                    ['Rhyme pair + comparison both work', 'One of the two is attempted', 'Rhyme is missing, rhythm flat', 'No attempt at rhyme or comparison'],
                    ['Every sentence correct', '2–3 errors that do not block meaning', 'Many errors, meaning is unclear', 'Fragments throughout'],
                    ['Neat, all high-frequency words correct', 'Readable, few spelling errors', 'Difficult to read, many errors', 'Illegible'],
                ],
            },
            { kind: 'memo', id: 'memo', title: 'Memo and mark allocation', items: [], total: 30 },
        ],
    },
    {
        id: 'ws-gr3-maths-fractions-perimeter-money',
        kind: 'worksheet',
        title: 'Fractions, Perimeter and Rands & Cents',
        subtitle: 'Mathematics Grade 3 · NOR + Space & Shape + Measurement',
        blurb:
            'Common fractions of a set, perimeter of rectangles in cm, and money problems to R100 with change — three CAPS strands on one marked sheet.',
        grades: ['3'],
        learningArea: 'Mathematics',
        theme: 'tangerine',
        art: 'elly-counting',
        pages: 2,
        tags: ['fractions', 'perimeter', 'money', 'Term 3–4'],
        fields: PRACTICE_FIELDS,
        caps: {
            contentArea: 'Numbers, Operations and Relationships (common fractions) · Space and Shape (perimeter) · Measurement (money, length)',
            skills: [
                'identify and use ½, ¼ and ⅓ of a set and of a shape',
                'measure and calculate the perimeter of rectangles in centimetres',
                'solve problems with Rands and cents up to R100, including change',
            ],
            terms: ['Term 3 · Weeks 2–6', 'Term 4 · Weeks 1–4'],
            asRef: 'CAPS Gr 3: fractions 58 % strand + measurement 14 % + geometry 13 %',
            blooms: ['Understand', 'Apply', 'Analyse'],
            timeOnTask: '35 min',
            setting: 'Assessment',
            marks: 30,
            capsNote:
                'By the end of Grade 3 the CAPS number range includes whole numbers to at least 1 000 and common fractions; formal fraction notation (½, ¼, ⅓, ⅕) is introduced in Grade 3.',
            memo: [
                { ref: 'A', answer: '½ of 12 = 6 · ¼ of 20 = 5 · ⅓ of 15 = 5 · ½ of 30 = 15', marks: 4 },
                { ref: 'B', answer: '1: 3 + 4 + 3 + 4 = 14 cm · 2: 10 + 5 + 10 + 5 = 30 cm · 3: square 5 × 4 = 20 cm', marks: 6 },
                { ref: 'C', answer: 'R45 + R28 = R73 · R100 − R73 = R27 change · 4 × R6 = R24 · R24 + R35 = R59', marks: 8 },
                { ref: 'D', answer: '½ more than ¼ (shading shown); 3 shaded out of 4 = ¾; accept 2/4 = ½.', marks: 6 },
                { ref: 'E', answer: 'Any multi-step answer with a valid method, e.g. 2 exercise books at R14 = R28; R50 − R28 = R22.', marks: 6 },
            ],
        },
        blocks: [
            {
                kind: 'task',
                id: 'A',
                title: 'A · Fractions of a set',
                instructionLabel: 'Bala',
                instruction: 'Draw the objects, then circle the fraction asked for.',
                items: [
                    { text: 'Half (½) of 12 pencils', lines: 2, marks: 1 },
                    { text: 'A quarter (¼) of 20 erasers', lines: 2, marks: 1 },
                    { text: 'A third (⅓) of 15 buttons', lines: 2, marks: 1 },
                    { text: 'Half of 30 marbles', lines: 2, marks: 1 },
                ],
                marks: 4,
            },
            {
                kind: 'grid',
                id: 'B',
                title: 'B · Measure and add to find the perimeter',
                columns: ['Shape', 'Side 1', 'Side 2', 'Side 3', 'Side 4', 'Perimeter (cm)'],
                rows: ['Rectangle 3 × 4', 'Rectangle 10 × 5', 'Square, side 5 cm'],
                marks: 6,
            },
            {
                kind: 'task',
                id: 'C',
                title: 'C · Money at the stationer\'s',
                instruction: 'A ruler costs R6 · a pad R28 · a pack of pens R45 · glue R14 · a maths book R35 · pencil R3.',
                items: [
                    { text: 'A pack of pens and a pad cost how much altogether?', lines: 2, marks: 2 },
                    { text: 'Lwande pays with a R100 note for those two items. How much change?', lines: 2, marks: 3 },
                    { text: 'Four rulers cost how much?', lines: 1, marks: 1 },
                    { text: 'A maths book and a glue stick cost how much?', lines: 2, marks: 2 },
                ],
                marks: 8,
            },
            {
                kind: 'colour-circle',
                id: 'D',
                title: 'D · Shade the fraction',
                instruction: 'Colour the fraction named under each shape. Then write the fraction for the last shape.',
                actions: ['colour', 'write'],
                layout: 'grid',
                items: [
                    { text: '▣', caption: 'shade ½ (2 of 4)' },
                    { text: '◫', caption: 'shade ¼' },
                    { text: '◫◫', caption: 'shade ¾ of 4 parts' },
                    { text: '◧', caption: 'what fraction is shaded?' },
                ],
                marks: 6,
            },
            {
                kind: 'task',
                id: 'E',
                title: 'E · Problem solving (show your method)',
                instruction: 'Use words, a drawing OR a number sentence. Marks are given for the method, not only the answer.',
                items: [
                    {
                        text: 'You have R50. You buy 2 exercise books at R14 each and a pen for R8. Do you have enough? How much is left?',
                        lines: 4,
                        marks: 6,
                    },
                ],
                marks: 6,
            },
            {
                kind: 'callout',
                id: 'tip',
                title: 'Teaching tip',
                tone: 'tip',
                lines: [
                    'Give each group a tape measure or a piece of string for the perimeter section — Grade 3 must MEASURE, not only add.',
                    'Use real coins and notes (or printed class sets) for section C; the DBE workbook expects notes to R100 handled confidently.',
                ],
            },
            { kind: 'memo', id: 'memo', title: 'Memo (step marks)', items: [], total: 30 },
        ],
    },
];

export default WORKSHEET_TEMPLATES;
